Update CONTRIBUTING.md
lfn-cnti/bestpractices pull request #103
Opened 2021-03-23 17:43 UTC by xmulligan

2021-03-23 17:50 UTC, taylor requested changes

2021-03-23 17:50 UTC, taylor commented on CONTRIBUTING.md
> +The CNF WG community follows the CNCF [Code of Conduct](https://github.com/cncf/cnf-wg/blob/master/interested-parties.md).
@xmulligan why is the link going to interested parties for the code of conduct?

2021-03-23 18:10 UTC, xmulligan commented on CONTRIBUTING.md
> +The CNF WG community follows the CNCF [Code of Conduct](https://github.com/cncf/cnf-wg/blob/master/interested-parties.md).
sorry put it in the wrong place somehow

2021-04-01 16:11 UTC, xmulligan commented
fixed in #107

2021-04-01 16:11 UTC, closed without merging