Add super-linter GitHub action
lfn-cnti/bestpractices pull request #120
Opened 2021-03-31 01:34 UTC by electrocucaracha

This linter helps to detect Markdown syntax issues and restricts the number of characters to 80. This [article](https://cirosantilli.com/markdown-style-guide/#line-wrapping) lists some benefits to wrapping long lines in Markdown documents.

2021-03-31 12:23 UTC, xmulligan commented
it looks like some of the links were taken away in the best_cnf_dev.md. Is this a problem we can fix in the linter?

2021-03-31 14:46 UTC, iawells commented
LGTM.  Nothing I've commented on is in need of addressing.

2021-03-31 14:46 UTC, iawells approved these changes

2021-03-31 14:46 UTC, iawells commented on CONTRIBUTING.md
> +## Where to Contribute
I guess the heading nesting was broken here?

2021-03-31 14:46 UTC, iawells commented on ccdps/0001-cnf-conformance-definition-proposal-process.md
>  ## **Summary**
Bolding a title is odd thing to do, for fixing in a future change.

2021-03-31 15:07 UTC, electrocucaracha reviewed
BTW, there are several typos that I didn't fix them in this PR

2021-03-31 15:07 UTC, electrocucaracha commented on CONTRIBUTING.md
> +## Where to Contribute
That's right, [heading levels have to be increased by one](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time)

2021-03-31 15:15 UTC, electrocucaracha commented
> it looks like some of the links were taken away in the best_cnf_dev.md. Is this a problem we can fix in the linter?

@xmulligan do you mean the example links to CCDP or the links in the table contents?

2021-04-02 19:44 UTC, taylor requested changes
Linting is great for feedback. It is "bad" for auto changes (in this case)

2021-04-02 19:44 UTC, taylor commented on .github/workflows/linkcheck.yml
> +# yamllint disable-line rule:truthy
@electrocucaracha will the linter complain or automatically change the documents?

I prefer the latter as it could do something we do not want it to do. eg. removing a link that is added for a upcoming document before that document is committed. changing intentional formatting items like  bold or indentions.

2021-04-02 19:44 UTC, taylor commented on .markdown-lint.yml
> +    "line_length": 80,
I did not hear an agreement on forcing 80 characters.

2021-04-02 19:44 UTC, taylor commented on CONTRIBUTING.md
> +Welcome to the Cloud Native Network Function (CNF) Working Group! This is an
The PR is for adding a new github action, but most of the changes are actual formatting changes. I think it should be split

2021-04-02 19:44 UTC, taylor commented on CONTRIBUTING.md
> +charter](https://github.com/cncf/cnf-wg/blob/master/charter.md).
Wow this is a terrible change.  This means the 80 character is forcing breaks where I would not expect them.  Smart editors will not break on a word for instance. This is breaking in the link text which at a minimum looks weird and I'm not clear if thats valid for writing markdown.

Some markdown editors+viewers will automatically render a carriage return as a HTML break (&lt;BR/&gt;) so this type of auto-breaking could cause problems for them as well. :/

I'm a thumbs down for 80 char forced limit and double thumbs down for auto changing all content to 80 chars. 👎 👎

2021-04-02 19:47 UTC, iawells commented on CONTRIBUTING.md
> +charter](https://github.com/cncf/cnf-wg/blob/master/charter.md).
You can't criticise the linter. It's super :)

The point it was fixing is diffs. I do agree, though, that it's forced breaks on stupid places in the links, ones that are probably not going to be helpful. Can we config it better?

2021-04-03 01:14 UTC, electrocucaracha commented on .github/workflows/linkcheck.yml
> +# yamllint disable-line rule:truthy
@taylor this will complain for syntax issues. Some linters included in the GH can support auto-correct functionality but they need to be executed locally.

2021-04-03 01:16 UTC, electrocucaracha commented on .markdown-lint.yml
> +    "line_length": 80,
Agree, we can define length on next meeting. At least there is a [vim way](https://stackoverflow.com/a/3033455) to wrap those lines

2021-04-03 01:18 UTC, electrocucaracha commented on CONTRIBUTING.md
> +Welcome to the Cloud Native Network Function (CNF) Working Group! This is an
Sadly, line length is not the only issues reported by this GH action. There are some Markdown issues and spaces detected.

2021-04-03 01:28 UTC, electrocucaracha commented on CONTRIBUTING.md
> +charter](https://github.com/cncf/cnf-wg/blob/master/charter.md).
Setting the `line-length` config value to `false` will disable it. The benefit that I've seen is on certain reviews (like this [one](https://github.com/cncf/cnf-wg/pull/95#discussion_r604293377)) where diff is not highlighted properly (but I'm not sure if it's caused by the browser, the line length, or another reason)

2021-04-05 16:25 UTC, jeffsaelens commented
@electrocucaracha remove line length prior to merge

2021-04-07 20:59 UTC, taylor approved these changes
lgtm

2021-04-12 17:35 UTC, agentpoyo approved these changes
LGTM

FYI, Conflicting files though:
_charter.md
doc/best_cnf_dev.md_

2021-04-14 01:03 UTC, iawells commented
I closed the line length issue - it comes with more problems than it solves - and I'm fine with the rest of this.

2021-04-14 01:03 UTC, iawells approved these changes

2021-04-15 22:03 UTC, lixuna approved these changes

2021-04-20 21:32 UTC, iawells commented
Merged link fixes from main.

2021-04-20 22:15 UTC, taylor approved these changes
lgtm

2021-04-20 22:20 UTC, jeffsaelens approved these changes
LGTM

2021-04-20 22:23 UTC, agentpoyo approved these changes
LGTM

2021-04-20 23:46 UTC, iawells approved these changes

2021-04-20 23:50 UTC, merged