add PR approval process
lfn-cnti/bestpractices pull request #123
Opened 2021-04-01 16:34 UTC by xmulligan

2021-04-01 16:40 UTC, jeffsaelens requested changes
A couple of quick fixes.

2021-04-01 16:40 UTC, jeffsaelens commented on charter.md
> +Use cases and best practices need approval from at least two tech leads to be merged. Approval from three community members can substitute for one tech lead vote. Merging may be veoted by the co-chai
```suggestion
Use cases and best practices need approval from at least two tech leads to be merged. Approval from three community members can substitute for one tech lead vote. Merging may be vetoed by the co-chairs with a vote of at least 2/3.
```

2021-04-01 16:40 UTC, jeffsaelens commented on charter.md
> +Changes to fix broken links, typos, small gramatical phrasing, or other editorial issues can be merged with the approval any co-chair or tech lead.
```suggestion
Changes to fix broken links, typos, small grammatical phrasing, or other editorial issues can be merged with the approval of any co-chair or tech lead.
```

2021-04-01 16:53 UTC, xmulligan commented
@jeffsaelens thanks for the grammar updates, should have done it in a word doc first 😅

2021-04-01 17:47 UTC, iawells approved these changes

2021-04-05 16:42 UTC, jeffsaelens requested changes
During the WG call, it was discussed that we need more clarity on roles.

2021-04-05 16:42 UTC, jeffsaelens commented on charter.md
> +Use cases and best practices need approval from at least two tech leads to be merged. Approval from three community members can substitute for one tech lead vote. Merging may be vetoed by the co-chai
Need to establish specifically what a tech lead is. Is it one tech lead or both that can be replaced by 3 community votes?

2021-04-05 16:42 UTC, jeffsaelens commented on charter.md
> +Charter updates need approval from at least two co-chairs. A co-chair vote can be replaced by the approval of two tech leads.
@fkautz "This is somewhat of a low bar for replacing the co-chair"

2021-04-09 01:10 UTC, taylor commented
See discussion for minimal process with delegation to community on all but a few items https://github.com/cncf/cnf-wg/discussions/130

2021-04-15 21:33 UTC, taylor commented
@xmulligan are you willing to close this PR out in favor of https://github.com/cncf/cnf-wg/pull/131

2021-04-15 23:51 UTC, electrocucaracha commented on charter.md
> +Changes to fix broken links, typos, small grammatical phrasing, or other editorial issues can be merged with the approval of any co-chair or tech lead.
This last criteria covers the rest of the cases so what about something like 
```suggestion
Any other change like fix broken links, typos, small grammatical phrasing, or other editorial issues can be merged with the approval of any co-chair or tech lead.
```

2021-04-16 17:28 UTC, xmulligan commented
@taylor I'll leave it open until one or the other is merged so people have ideas for different options

2021-04-22 22:42 UTC, taylor commented
> @taylor I'll leave it open until one or the other is merged so people have ideas for different options

@xmulligan close?  re: #131

2021-04-23 08:33 UTC, closed without merging