Expand on best practice areas
lfn-cnti/bestpractices pull request #128
Opened 2021-04-05 18:29 UTC by iawells

Fix up the titles so that they're more consistently using the same part
of speech.

Add a paragraph of description to each section.

Reorder the sections slightly ('install/start' comes before
'configure/manage' in a real life schenario; no reason the sections
should be the other way around).

(I note that these areas might also be areas for use cases.)

2021-04-05 20:03 UTC, jeffsaelens approved these changes
LGTM

2021-04-05 20:50 UTC, iawells commented on doc/best_cnf_dev.md
>  * [4.0 Microservice](#4.0)
```suggestion
* [4.0 Microservices](#4.0)
```

2021-04-05 21:45 UTC, taylor requested changes

2021-04-05 21:45 UTC, taylor commented on doc/best_cnf_dev.md
> +## 2.0 Installation and Upgrade
```suggestion
## 1.0 Installation and Upgrade
```

2021-04-06 07:19 UTC, CsatariGergely approved these changes

2021-04-06 08:04 UTC, xmulligan approved these changes

2021-04-09 01:06 UTC, taylor approved these changes
lgtm

2021-04-09 06:34 UTC, CsatariGergely approved these changes

2021-04-09 15:56 UTC, sishbi requested changes

2021-04-09 15:56 UTC, sishbi commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
Can 'billing records' be generalised to something like 'subscriber activity data'

2021-04-09 15:58 UTC, iawells commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
Yes, certainly.  Can you propose a change I can accept? (The doc icon with '+-' on it in the github comment toolbar)

2021-04-09 16:01 UTC, sishbi commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
OK, I will try to find the button and then submit a PR on your PR (or whatever the correct term is)

2021-04-09 16:14 UTC, iawells commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
It should just be a change as a part of a comment on this pull request.

<img width="789" alt="Screenshot 2021-04-09 at 09 13 03" src="https://user-images.githubusercontent.com/1719713/114209807-e6c48800-9913-11eb-835a-0ede61dafd4f.png">

(See the icon above the word 'comment' in the screenshot?  If not, we may need to add a permission bit for you.)

2021-04-09 16:16 UTC, Smitholi67 commented on doc/best_cnf_dev.md
> +How to get critical data about when things are going wrong and how to determine what must be done to put them right.  Using logs and metrics from all components in the system to narrow down the area
Is it fair to aspire for most of this to be automated?  If so, maybe it can read:

How to get critical data about when things are going wrong and to determine what must be done to put them right with limited or no human intervention.  Using logs and metrics from all components in the system to narrow down the area where a problem exists, determine root cause, and correct.

2021-04-09 16:19 UTC, iawells commented on doc/best_cnf_dev.md
> +How to get critical data about when things are going wrong and how to determine what must be done to put them right.  Using logs and metrics from all components in the system to narrow down the area
I see your point and I agree.  I might reword it to make it more that this is consumable by an automated system or a human being than prioritise automation over humans.  We have to serve both audiences anyway.

I don't disagree with you that automation is actually more important, but the humans involved sometimes do :)

2021-04-09 16:20 UTC, iawells commented on doc/best_cnf_dev.md
> +How to get critical data about when things are going wrong and how to determine what must be done to put them right.  Using logs and metrics from all components in the system to narrow down the area
```suggestion
How to get critical data about when things are going wrong and how to determine what must be done to put them right.  The detection and correction may be through the actions of an operator or via an automated system.  Using logs and metrics from all components in the system to narrow down the area where a problem exists, and to drill down into that area to determine a root cause and a fix.
```

2021-04-09 16:21 UTC, iawells commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
(If this is a problem don't spend much time on it; just tell me it's all screwed up for you and I'll propose the fix.)

2021-04-09 16:21 UTC, Smitholi67 commented on doc/best_cnf_dev.md
> +How to get critical data about when things are going wrong and how to determine what must be done to put them right.  Using logs and metrics from all components in the system to narrow down the area
Thanks, this looks good to me.

2021-04-09 16:22 UTC, Smitholi67 approved these changes

2021-04-09 16:26 UTC, sishbi approved these changes

2021-04-09 16:26 UTC, sishbi commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
```suggestion
Management of short-lived and long lived state, including state associated with network flows, configuration data, subscriber activity data and other data according to the varying requirements of resiliency, rate of change, access rate and persistence.
```

2021-04-09 16:27 UTC, sishbi commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
@iawells I think I did the right thing, let me know if not...

2021-04-09 16:28 UTC, iawells commented on doc/best_cnf_dev.md
> +Management of short-lived and long lived state, including state associated with network flows, configuration data, billing records and other data according to the varying requirements of resiliency,
Perfect, thanks.  I'll talk to @taylor and @jeffsaelens about adding this to the reviewer help.

2021-04-12 16:55 UTC, merged