Acceptance process delegation for most items + exceptions
lfn-cnti/bestpractices pull request #131
Opened 2021-04-09 01:29 UTC by taylor

This adds the approval process section which 
- delegates most responsibility for accepting changes to the community as outlined in the CONTRIBUTING guide
- exception list of items requiring additional approval

ref: 
- discussion https://github.com/cncf/cnf-wg/discussions/130
- approval process issue #74

2021-04-09 01:39 UTC, taylor commented
@electrocucaracha the link checks are going against master instead of the branch with the change.  anything to do?

cc: @iawells

2021-04-09 01:50 UTC, electrocucaracha commented on GOVERNANCE.md
> +1. [Governance](https://github.com/cncf/cnf-wg/blob/master/governance.md)
Can you try with upper case? It seems to be case sensitive.
```suggestion
1. [Governance](https://github.com/cncf/cnf-wg/blob/master/GOVERNANCE.md)
```

2021-04-09 05:24 UTC, iawells commented on GOVERNANCE.md
> +1. [Governance](https://github.com/cncf/cnf-wg/blob/master/governance.md)
They should be relative links, as I mentioned in another pull request. A branch of fork needs to be consistent with itself, not with master in the main repo.

2021-04-09 05:25 UTC, iawells commented on GOVERNANCE.md
> +1. [Governance](https://github.com/cncf/cnf-wg/blob/master/governance.md)
(It needed fixing before; you just happen to have tripped over why.)

2021-04-09 08:19 UTC, sishbi commented on GOVERNANCE.md
> +    - This would be Best Practices which the CNF WG promotes in an approved list. Eg. Baseline Best Practices
Should there be a 'stub' file for the approvedlist, such as 'approved-list.md' ?

2021-04-09 08:20 UTC, sishbi approved these changes

2021-04-09 12:21 UTC, xmulligan commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
Where do people find those reviewers? If someone new is coming to the repo, they won't know who to tag

2021-04-09 12:22 UTC, xmulligan commented on CONTRIBUTING.md
> +1. Reviewers will review the PR and give their feedback: approve, request change, comment w/o approval
Who are "Reviewers"? Who can be one?

2021-04-09 12:23 UTC, xmulligan commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may accepted after approval of 5 community reviewers.
Who a "community reviewer" is needs to be defined somewhere. What about adding a requirement that they come from at least 3 different companies?

2021-04-09 12:24 UTC, xmulligan commented on GOVERNANCE.md
> +To encourage contributions the CNF WG has a more relaxed stance on changes and delegates the acceptance for most items to the community as outlined in CONTRIBUTING.md. The small list of exceptions ar
```suggestion
To encourage contributions, the CNF WG has a more relaxed stance on changes and delegates the acceptance for most items to the community as outlined in CONTRIBUTING.md. The small list of exceptions are listed below which require a more thorough decision making process to achieve our desired outcome of fair representation and technical excellence.
```

2021-04-09 16:41 UTC, jeffsaelens commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
Could we add an LFR (Looking For Reviewers) label?

2021-04-09 18:11 UTC, Smitholi67 approved these changes
Looks good to me.  Agree with the comment by @sishbi that the best practices baseline should sit in a separate file.  Thinking forward it might be good to maintain different versions of these best practices as they continue to mature.  This would be useful if the best practices are to be used in a badging process down the road.

2021-04-09 18:12 UTC, taylor commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
@xmulligan ideally we could use github teams to add all reviewers to the team. Then you can tag the whole group like: @cncf/cnf-wg-reviewers. Unfortunately teams only allow org members and not "outside collaborators".  

Someone new can click the review button on the PR and select folks, but we do have people listed who may not be active or just happen to have access via the org level permissions.  
![image](https://user-images.githubusercontent.com/26697/114221046-63fef580-9932-11eb-9237-6b3d39d4c539.png)

One option is to create a new org for all of the CNF initiatives. We thought about this in the past, but only had cnf-testbed at the time. Now there are 4.  If we did this we could create teams and add everyone who is participating to the new "CNCF CNF" org.

An alternative approach to deal with the github limitations are to to create a file in the repo we can add the github user handle (and probably name) for anyone that would like to be a reviewer. K8s and many projects uses a file called OWNERS to list reviewers and other roles for tagging.

From there someone can manually look at the file and pick some user names to tag (with the reviewers button or via comment) or we can add a bot like many projects have which supports using an owners file.

Many projects and communities use automation with something like an OWNERS file including the K8s community.  They use prow and the bot has a ton of features -- https://github.com/kubernetes/test-infra/blob/master/prow/README.md.  We can probably go with something simpler if we want to automate things.

Github supports some automation via a CODEOWNERS file, but it has limitations such as automatically notifying everyone that is listed.  That could get spammy of course if everyone is notified for every new PR to review vs a subset. See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**TL;DR**
- Couple of options
    - Create a file with a list of the reviewers
    - Create new CNCF CNF org (eg. cncf-cnf) and use org teams
- Decide on manual or automation

2021-04-09 18:13 UTC, taylor commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
@jeffsaelens yes for a label.  Who will look for the label though?  If we automate or its manually noticed and an action to choose reviewers happens when the label is there we still need a list of reviewers somewhere.

2021-04-09 18:16 UTC, taylor commented on CONTRIBUTING.md
> +1. Reviewers will review the PR and give their feedback: approve, request change, comment w/o approval
@xmulligan any community member can be a reviewer.

Maybe it should say Community Reviewers or Community Member?

We can grant github read access to the repo to allow the reviewer to be tagged in a PR in the reviews section.

2021-04-09 18:22 UTC, taylor commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may accepted after approval of 5 community reviewers.
Yes for a definition being somewhere.  I was thinking anyone in the community can say they would like to review.  So this is not a select set for the default reviews.  Open to anyone in the community. We can add other types of reviewers later if needed.

Not sure that its necessary at this time to limit reviews from the same org/company yet for the items not in the Additional Approval Items list.  We could modify the CONTRIBUTING guide when we see a problem or after further thought. This path was to keep it simple for the defaults.

Specifically for non-controversial items we want to lower the barrier for making contributions.  If the barrier is too low we adjust later. If something needs more discussion, eg. its something that is more "controversial", then maybe it gets added to the other list.

2021-04-09 18:28 UTC, taylor commented on GOVERNANCE.md
> +    - This would be Best Practices which the CNF WG promotes in an approved list. Eg. Baseline Best Practices
@sishbi possibly.  it does not seem needed for this PR, IMO though.  We do have https://github.com/cncf/cnf-wg/blob/master/doc/best_cnf_dev.md which somewhat is communicating a baseline set of practices for cnf developers.  Do you think its necessary for this PR or could it be addressed later?

2021-04-09 18:28 UTC, taylor commented on GOVERNANCE.md
> +    - This would be Best Practices which the CNF WG promotes in an approved list. Eg. Baseline Best Practices
I do think, the definition of approved best practices and/or the name in the list could use some some clarity.

If its not apparent there is not a restriction on proposing a best practice.  There is not a restriction on accepting a PR to add a proposal to the repository. The restriction is in communicating that the CNF WG now advocates the proposed / draft best practice should be adopted. This would also tie into any type of conformance program. We want to make sure that best practices that are included in a conformance program go through additional approval.

2021-04-09 18:49 UTC, sishbi commented on GOVERNANCE.md
> +    - This would be Best Practices which the CNF WG promotes in an approved list. Eg. Baseline Best Practices
@taylor Maybe the fix is to add a link to that doc as I missed it when I first read through the wiki
Is that the current approved list? Or the current draft list?

2021-04-09 19:04 UTC, iawells commented
> the link checks are going against master instead of the branch with the change. anything to do?

Could have sworn I said this earlier but maybe it was another PR: the link checks should be relative links (so that they point to the PR's documents) and never absolute links to both the main repo and the main branch.   Broken links is one of the reasons why, but of course another is you can't easily review a document set for consistency when its crosslinks take you to inconsistent versions.

While we do want someone to go through the lot and deal with it, for now I suggest we weed them out as we find them, which means this wants fixing up as you do this PR.

2021-04-09 19:06 UTC, iawells commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
To get us started (until we find a nice technical solution or something else) I would basically say 'tag at least 5 reviewers OR tag a co-chair who will find reviewers for you'.  It doesn't have to be perfect just yet, only functional.

2021-04-09 19:13 UTC, iawells commented
Speaking to intentions a moment:

- first, we need people to review and merge things (this is all a bit woolly at the moment and we seem to have a bit of merge hesitancy; this PR makes it clear when merges should happen)
- then, we need to develop use cases and best practices (so we need a procedure that works specifically for them right now)
- finally, we need to set a baseline for release (at which point we'll need an approval process, and we'll need to ensure people don't modify old baselines, and so on)

I like the way this is put together, because it codifies the bits that we _need_ without getting to in-depth in the things we haven't reached just yet.  That works for me because I think we'll learn things on the journey - rather than having a stab at the later bits right now, we will write them up a bit closer to when we need them and we understand how we work a little bit more clearly.

2021-04-09 19:16 UTC, iawells requested changes

2021-04-09 19:16 UTC, iawells commented on CONTRIBUTING.md
> +1. Reviewers will review the PR and give their feedback: approve, request change, comment w/o approval
I see potential reviewers as any community member for the moment.  We can get more specific in the future, but for the moment this lets us get moving (and is, in practice, writing down what we're already doing).

2021-04-09 20:44 UTC, jeffsaelens commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may accepted after approval of 5 community reviewers.
I think the last paragraph is what's important. For basic house keeping, we should make things simple to keep things moving smoothly. Company separation for grammar/spelling fixes, or adding events to a list somewhere etc... don't need any special protection. 

As we begin to produce best practices, and things that have impact, we can tighten up what a role to approve merges would look like.

2021-04-14 00:56 UTC, iawells commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
Indeed: if we make a team of 'standard reviewers' it can be their first responsibility to spread the joy to others (which works slightly better than a label would, imo)

2021-04-15 13:36 UTC, ildikov commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
Is this step a must?

As GH sends notification emails, I wonder if the notification about tagging will be lost or rather just a duplicate of the notification about the new PR. Would this be better as a step to take if the PR sits unreviewed for longer than X?

2021-04-15 13:36 UTC, ildikov commented on CONTRIBUTING.md
> +1. Reviewers will review the PR and give their feedback: approve, request change, comment w/o approval
If we have a list of identified roles I think it's better to document that somewhere and refer to that list where needed as opposed to trying to create descriptive terms like 'community reviewer'. As everyone in the community should be able and encouraged to review, saying 'community reviewer' creates a confusing distinction as I don't think we will have non-community reviewers.

2021-04-15 13:36 UTC, ildikov commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may accepted after approval of 5 community reviewers.
```suggestion
- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may be accepted after approval of 5 community reviewers.
```

2021-04-15 21:38 UTC, taylor commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
@ildikov do you mean comment tagging (team or individuals) or something else

I was taking @iawells comment
>tag at least 5 reviewers OR tag a co-chair who will find reviewers for you'
to mean typing the usernames into the choose reviewers box on the top right of a pull request re: screenshot https://github.com/cncf/cnf-wg/pull/131#discussion_r610820564 with _"Request up to 15 reviewers"_

2021-04-15 21:41 UTC, taylor commented on CONTRIBUTING.md
> +- Tag at least 5 reviewers
@iawells @ildikov see latest update to CONTRIBUTING guide:
- Choose at least 5 reviewers OR choose a co-chair who will find reviewers for you

2021-04-15 21:51 UTC, taylor commented on CONTRIBUTING.md
> +1. Reviewers will review the PR and give their feedback: approve, request change, comment w/o approval
@iawells @ildikov see latest update to contributing guide:

Reviewers - Any community member
- Everyone in the community is able to and encouraged to do reviews

2021-04-15 21:55 UTC, taylor commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may accepted after approval of 5 community reviewers.
@xmulligan see [latest update to contributing guide](https://github.com/cncf/cnf-wg/blob/minimal-approval-process-with-exception-list/CONTRIBUTING.md#acceptance-of-contributions)

Reviewers - Any community member
- Everyone in the community is able to and encouraged to do reviews

2021-04-15 22:05 UTC, taylor commented on GOVERNANCE.md
> +    - This would be Best Practices which the CNF WG promotes in an approved list. Eg. Baseline Best Practices
@sishbi see [latest update to GOVERNANCE.md](https://github.com/cncf/cnf-wg/blob/minimal-approval-process-with-exception-list/GOVERNANCE.md#additional-approval-items) with a link to the dev doc

We have no draft list yet.  That document was created to give some structure for a potential list of best practices.  It could be the "approved" list or a list of all of them including non-approved.

2021-04-15 22:07 UTC, taylor commented on GOVERNANCE.md
> +To encourage contributions the CNF WG has a more relaxed stance on changes and delegates the acceptance for most items to the community as outlined in CONTRIBUTING.md. The small list of exceptions ar
```suggestion
To encourage contributions the CNF WG has a more relaxed stance on changes and delegates the acceptance for most items to the community as outlined in CONTRIBUTING.md. The small list of exceptions are listed below which require a more thorough decision making process to achieve our desired outcome of fair representation and technical excellence.
```

2021-04-15 22:11 UTC, taylor commented
@iawells links should now be relative

https://github.com/cncf/cnf-wg/pull/131#issuecomment-816896649

2021-04-15 22:22 UTC, jeffsaelens approved these changes
changes look good.

2021-04-15 23:32 UTC, electrocucaracha commented on CONTRIBUTING.md
> +- Choose at least 5 reviewers OR choose a co-chair who will find reviewers for you
Given the current co-chairs are listed in the governance document maybe they can be referenced
```suggestion
- Choose at least 5 reviewers OR choose a [co-chair](https://github.com/cncf/cnf-wg/blob/main/GOVERNANCE.md#chairs) who will find reviewers for you
```

2021-04-15 23:32 UTC, electrocucaracha commented on CONTRIBUTING.md
> +### Acceptance of Contributions
```suggestion
### Acceptance criteria for Contributions
```

2021-04-17 17:56 UTC, electrocucaracha commented on CONTRIBUTING.md
> +- Spelling, grammar, and adding new interested parties require 1 reviewer
Maybe we can apply [lazy consensus](https://community.apache.org/committers/lazyConsensus.html) here

2021-04-17 18:43 UTC, agentpoyo requested changes

2021-04-17 18:43 UTC, agentpoyo commented on GOVERNANCE.md
> +    - Proposing a best practice is okay with the default process. Marking it as accepted and listing it as a CNF WG approved Best Practice requires additional review and approval
`Proposing a best practice is welcome and encouraged with the default process.`

Reads better than using okay.

2021-04-19 17:01 UTC, agentpoyo requested changes

2021-04-19 17:01 UTC, agentpoyo commented on GOVERNANCE.md
> +    - Proposing a best practice is okay with the default process. Marking it as accepted and listing it as a CNF WG approved Best Practice requires additional review and approval
```suggestion
    - Proposing a best practice is encouraged with the default process. Marking it as accepted and listing it as a CNF WG approved Best Practice requires additional review and approval.
```

2021-04-19 17:10 UTC, pgoyal01 commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may be accepted after approval of 5 community reviewers.
Should there be a requirement on the diversity of reviewers (such as not more than 2 from the same company, at least X from each company industry, not from the PR author company, etc,

2021-04-19 17:10 UTC, pgoyal01 commented on CONTRIBUTING.md
> +- Spelling, grammar, and adding new interested parties require 1 reviewer
Should there be a restriction that the approver is not from same company as the author

2021-04-19 17:15 UTC, pgoyal01 commented on CONTRIBUTING.md
> +1. After required number of approvals from reviewers is reached the PR may be merged
Should there be an add that the issues/questions raised have been addressed? Co-chair should ensure prior to merge -- co-chairs responsible for merge or insist a co-chair approval.

2021-04-19 17:15 UTC, pgoyal01 commented on CONTRIBUTING.md
> +1. After required number of approvals from reviewers is reached the PR may be merged
Are approvals to be ignored that were made prior to non-trivial changes?

2021-04-20 22:21 UTC, taylor commented on CONTRIBUTING.md
> +- Spelling, grammar, and adding new interested parties require 1 reviewer
@pgoyal01 that might be a good idea. @xmulligan had a related suggestion about reviewers.  

For now I suggest we leave it more open, then modify if we see it as a problem.  The CONTRIBUTING.md can be updated based on the criteria we list here.  Eg. 5 community reviewers.

2021-04-21 19:05 UTC, agentpoyo approved these changes
LGTM

2021-04-21 19:06 UTC, electrocucaracha approved these changes

2021-04-21 19:10 UTC, rannyh approved these changes
LGTM

2021-04-21 19:13 UTC, pgoyal01 approved these changes

2021-04-21 19:40 UTC, lixuna commented on CONTRIBUTING.md
> +- Choose at least 5 reviewers OR choose a [co-chair](https://github.com/cncf/cnf-wg/blob/main/GOVERNANCE.md#chairs) who will find reviewers for you
suggestion to change link from (https://github.com/cncf/cnf-wg/blob/main/GOVERNANCE.md#chairs) to (GOVERNANCE.md#chairs)

2021-04-21 19:43 UTC, lixuna commented on GOVERNANCE.md
> +To encourage contributions, the CNF WG has a more relaxed stance on changes and delegates the acceptance for most items to the community as outlined in CONTRIBUTING.md. The small list of exceptions a
```suggestion
To encourage contributions, the CNF WG has a more relaxed stance on changes and delegates the acceptance for most items to the community as outlined in [CONTRIBUTING.md](CONTRIBUTING.md). The small list of exceptions are listed below which require a more thorough decision making process to achieve our desired outcome of fair representation and technical excellence.
```

2021-04-21 19:43 UTC, lixuna commented on GOVERNANCE.md
> +The process for accepting changes to content in the CNF WG repository (including adding new content) for any item not in the [Additional Approval Items list](#DD) below will follow the acceptance and
```suggestion
The process for accepting changes to content in the CNF WG repository (including adding new content) for any item not in the [Additional Approval Items list](#DD) below will follow the acceptance and approval process outlined in the [CONTRIBUTING guide](CONTRIBUTING.md).
```

2021-04-21 19:44 UTC, lixuna commented on CONTRIBUTING.md
> +- Choose at least 5 reviewers OR choose a [co-chair](https://github.com/cncf/cnf-wg/blob/main/GOVERNANCE.md#chairs) who will find reviewers for you
```suggestion
- Choose at least 5 reviewers OR choose a [co-chair](GOVERNANCE.md#chairs) who will find reviewers for you
```

2021-04-21 19:48 UTC, taylor commented
@lixuna all your items have been addressed. Please re-review

2021-04-21 20:03 UTC, iawells commented on CONTRIBUTING.md
> +<<<<<<< HEAD
oopsy

2021-04-21 20:06 UTC, iawells approved these changes

2021-04-21 20:06 UTC, taylor commented on CONTRIBUTING.md
> +<<<<<<< HEAD
oops

2021-04-21 20:11 UTC, taylor commented on CONTRIBUTING.md
> +1. After required number of approvals from reviewers is reached the PR may be merged
@pgoyal01 I try to re-request reviews for non-trivial changes on PRs.

2021-04-21 20:13 UTC, taylor commented on CONTRIBUTING.md
> +1. After required number of approvals from reviewers is reached the PR may be merged
@pgoyal01 I'm trying to go through and address all comments in the PR.

If you want it in the CONTRIBUTING.md then please open a new issue and/or PR.

Also remember we can always go back and open a new PR to address anything we consider a mistake or now want to see differently.

2021-04-21 20:15 UTC, taylor commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may be accepted after approval of 5 community reviewers.
@pgoyal01 this could be brought up as a new issue, discussion, or PR.

2021-04-21 20:20 UTC, lixuna approved these changes
lgtm

2021-04-21 22:09 UTC, jeffsaelens commented
There is a ton going on here. There have been previous approvals, and 3 current ones. Could we get some fresh eyes on this? We may be at the point where we want to merge this, and then cut a new PR for additional modifications.

2021-04-21 22:31 UTC, taylor commented
@jeffsaelens unfortunately github does not show approvers in the history unless they have specific permission for the repo.  That's why you don't find @electrocucaracha in the history and yet has has approved in the reviewers area (✔️ ).


Reviewers from today who have approved: @iawells @lixuna @agentpoyo @rannyh @pgoyal01 @electrocucaracha 

The past reviewers are: @sishbi @Smitholi67

2021-04-21 23:39 UTC, iawells approved these changes
Still good with this in its current state.

2021-04-22 06:27 UTC, rabi-abdel approved these changes
It will be good to define who can be considered a community member (it could be simply any one).

2021-04-22 07:00 UTC, ildikov approved these changes

2021-04-22 08:50 UTC, xmulligan commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may accepted after approval of 5 community reviewers.
```suggestion
#### Acceptance of PRs for merging

- Spelling, grammar, and new interested parties require 1 apporval for merging
- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may merged after approval of 5 community reviewers.
```

2021-04-22 08:53 UTC, xmulligan commented on CONTRIBUTING.md
> +- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may be accepted after approval of 5 community reviewers.
```suggestion
- Other changes with exception to those listed in the [Governance Additional Approval Items list](GOVERNANCE.md#additional-approval-items) may be merged after approval of 5 community reviewers.
```

2021-04-22 14:03 UTC, xmulligan commented on CONTRIBUTING.md
> +- Everyone in the community is able to and encouraged to do reviews
```suggestion
- Everyone in the community is able to and encouraged to do reviews. Anyone can be a part of the CNF WG community.
```

2021-04-22 14:43 UTC, xmulligan approved these changes

2021-04-22 15:54 UTC, jeffsaelens approved these changes

2021-04-22 22:30 UTC, merged

2021-04-23 07:16 UTC, sishbi reviewed
Some minor edits in PR #155