removing tech leads
lfn-cnti/bestpractices pull request #145
Opened 2021-04-22 13:52 UTC by xmulligan

it seems we are moving away from having tech leads to this should be reflected in the governance see #131

2021-04-22 16:02 UTC, iawells commented
I think a better way of describing this is we'll add them when we have something specific for them to do, but I agree that until then we'd be better off not speculating about the process and role.

2021-04-22 16:02 UTC, iawells approved these changes

2021-04-22 17:06 UTC, taylor approved these changes
lgtm

2021-04-22 21:34 UTC, Smitholi67 approved these changes
Lgtm.  Agree that Tech Leads can be added when there becomes a need.

2021-04-22 22:27 UTC, taylor commented
@xmulligan fixed merge conflict. check to make sure it looks correct (mainly deleted the sections headers you had deleted that were in main)

2021-04-23 01:03 UTC, jeffsaelens approved these changes
Update looks solid.

2021-04-23 03:16 UTC, rannyh requested changes
LGTM

2021-04-23 06:34 UTC, sishbi commented
LGTM

2021-04-23 06:34 UTC, sishbi approved these changes

2021-04-23 08:37 UTC, xmulligan commented on GOVERNANCE.md
> +Co-chairs will be elected for one year terms and may run for reelection.
```suggestion
### Timeline

Co-chairs will be elected for one year terms and may run for reelection.
```

2021-04-23 08:39 UTC, xmulligan commented on GOVERNANCE.md
```suggestion

### Voting Procedure
```

2021-04-23 08:49 UTC, xmulligan commented
@taylor those weren't supposed to be deleted, but I made this PR before #146 was merged into main so it looks like I deleted them. I've added them back in. Otherwise I think it is ready to merge and it has 5 approvals

2021-04-23 13:25 UTC, Smitholi67 approved these changes

2021-04-23 14:09 UTC, merged