clarify interested parties
lfn-cnti/bestpractices pull request #147
Opened 2021-04-22 14:06 UTC by xmulligan

fixes #87

2021-04-22 14:20 UTC, xmulligan commented on interested-parties.md
> +The interested parties listed below are used for voting purposes as outlined in the [Governance doc](GOVERNANCE.md). See the [contributing doc](CONTRIBUTING.md) for more information about getting inv
```suggestion

The interested parties listed below are used for voting purposes as outlined in the [Governance doc](GOVERNANCE.md). See the [contributing doc](CONTRIBUTING.md) for more information about getting involved and participating in the community.
```

2021-04-22 16:09 UTC, iawells approved these changes
Will conflict with @taylor's work when merging but should work together with it; we want both.

2021-04-22 17:10 UTC, taylor reviewed
I don't think any clarification or specificity is necessary.  

The list can be used for multiple purposes, including simply showing anyone who cares that there are interested parties.

FYI, in the K8s+CNCF interested parties lists that I have seen so far, I do not see a reason for the list.

2021-04-23 02:36 UTC, jeffsaelens approved these changes
LGTM

2021-04-27 15:05 UTC, Smitholi67 reviewed
LGTM.  I wonder if, however, we should be listing company/organization first since that is what we are sorting on.  Just a thought.

2021-04-27 16:54 UTC, taylor commented
I think a more general message and intent should be used, such as the following

> A WG is good mechanism, for interested parties, to share their thoughts and ideas around a concern such as Chaos Engingeering which, while a relatively new discipline, is rapidly becoming a mainstream concern for many companies adopting cloud native practices and tools.

from https://medium.com/chaosiq/federating-chaos-engineering-with-a-cncf-working-group-c08c85c2ad18

2021-04-27 17:22 UTC, taylor requested changes

2021-04-27 17:22 UTC, taylor commented on interested-parties.md
> +The interested parties listed below are used for voting purposes as outlined in the [Governance doc](GOVERNANCE.md). See the [contributing doc](CONTRIBUTING.md) for more information about getting inv
```suggestion
To express your interest in the cloud native networking topics under discussion in this working group, please add your name and organization name to this document via a Pull Request.

Being listed in this document may grant you some rights within the group, such as voting capabilities as outlined in the [Governance doc](GOVERNANCE.md).  See the [contributing doc](CONTRIBUTING.md) for more information about getting involved and participating in the community. 

Note: adding yourself to this list does not imply any obligation (including legal) for you nor your organization.
```

2021-04-27 17:23 UTC, taylor commented on interested-parties.md
> +The interested parties listed below are used for voting purposes as outlined in the [Governance doc](GOVERNANCE.md). See the [contributing doc](CONTRIBUTING.md) for more information about getting inv
@xmulligan this change would address #87 items including the concerns (via the note) while keeping it open for other uses.

2021-04-27 18:38 UTC, iawells commented on interested-parties.md
> +The interested parties listed below are used for voting purposes as outlined in the [Governance doc](GOVERNANCE.md). See the [contributing doc](CONTRIBUTING.md) for more information about getting inv
I'm good with this suggestion.

2021-04-30 21:32 UTC, taylor approved these changes
lgtm

2021-05-04 15:59 UTC, lixuna approved these changes
LGTM

2021-05-04 16:03 UTC, lixuna commented on interested-parties.md
> +Being listed in this document may grant you some rights within the group, such as voting capabilities as outlined in the [Governance doc](GOVERNANCE.md).  See the [contributing doc](CONTRIBUTING.md)
```suggestion
Being listed in this document may grant you some rights within the group, such as voting capabilities as outlined in the [Governance doc](GOVERNANCE.md).  See the [contributing doc](CONTRIBUTING.md) for more information about getting involved and participating in the community.
```

2021-05-04 16:03 UTC, lixuna commented on interested-parties.md
> +Being listed in this document may grant you some rights within the group, such as voting capabilities as outlined in the [Governance doc](GOVERNANCE.md).  See the [contributing doc](CONTRIBUTING.md)
remove trailing space per linter error

2021-05-10 16:24 UTC, rabi-abdel approved these changes
Approved

2021-05-10 16:27 UTC, rannyh approved these changes
LGTM

2021-05-10 16:28 UTC, sishbi approved these changes
LGTM

2021-05-10 16:28 UTC, iawells approved these changes

2021-05-10 16:29 UTC, merged