Expand contributing documentation
lfn-cnti/bestpractices pull request #157
Opened 2021-04-23 14:02 UTC by xmulligan

Many of these updates are pulled from SIG Contributor experience documentation 
https://github.com/cncf/project-template/blob/main/CONTRIBUTING.md

2021-04-24 00:26 UTC, jeffsaelens requested changes
I'm a big fan of these additions. In the checklist section we reference submitting code, which we aren't doing here at the moment. Maybe in a future PR we add to the bottom of the contributing.md doc some links of where those looking to submit code might go to do so? Repos like the CNF Testbed and other opensource projects supporting this effort in parallel.

2021-04-24 00:26 UTC, jeffsaelens commented on CONTRIBUTING.md
> +- [Use cases](use-case/) and user stories (these are used to define best practices)
Defined reads odd to me. Maybe something like provide context to a best practice? I'm not sure if that is right easier, but in my mind the use case provides the justification for the best practices existence in the first place. Its also what we'd ultimately measure the BP against.

2021-04-24 00:26 UTC, jeffsaelens commented on CONTRIBUTING.md
> +feedback on others’ ideas, and even sharing your own ideas, and experiences.
```suggestion
feedback on others’ ideas. Simply sharing your own ideas, and experiences can help in ways you might not initially realize.
```

2021-04-24 00:26 UTC, jeffsaelens commented on CONTRIBUTING.md
> +systems will run some checks on your new code. We require that your pull request
might need to change this verbiage up a tiny bit since we aren't necessarily contributing code here to this repo atm. Maybe just something as simple as "your updates" or "your documentation"?

2021-04-24 00:31 UTC, iawells commented on CONTRIBUTING.md
> +- [Use cases](use-case/) and user stories (these are used to define best practices)
'select'?

2021-04-25 16:27 UTC, xmulligan commented on CONTRIBUTING.md
> +systems will run some checks on your new code. We require that your pull request
How about "contribution"?

2021-04-25 16:27 UTC, xmulligan commented on CONTRIBUTING.md
> +systems will run some checks on your new code. We require that your pull request
```suggestion
systems will run some checks on your new contribution. We require that your pull request
```

2021-04-25 16:28 UTC, xmulligan commented on CONTRIBUTING.md
> +- [Use cases](use-case/) and user stories (these are used to define best practices)
I'll take both of your suggestions

2021-04-25 16:28 UTC, xmulligan commented on CONTRIBUTING.md
> +- [Use cases](use-case/) and user stories (these are used to define best practices)
```suggestion
- [Use cases](use-case/) and user stories (these are used to provide context for and select best practices)
```

2021-04-25 16:33 UTC, xmulligan commented on CONTRIBUTING.md
> +  - [See the template for more details](/use-case/NNNN-UC-template.md)
```suggestion
  - [See the template for more details](use-case/NNNN-UC-template.md)
```

2021-04-25 16:33 UTC, xmulligan commented on CONTRIBUTING.md
> +  - [See the template for more details](/cbpps/NNNN-cbpp-template.md)
```suggestion
  - [See the template for more details](cbpps/NNNN-cbpp-template.md)
```

2021-04-25 21:43 UTC, jeffsaelens approved these changes
Changes/Updates LGTM

2021-04-25 22:16 UTC, xmulligan commented
I'm not sure why the test is failing because I'm not editing the Governance doc and in both branches, there is a line after "Voting Procedures" header 🤷

2021-04-26 22:34 UTC, taylor approved these changes
lgtm

2021-04-26 22:34 UTC, taylor commented
@electrocucaracha @iawells what about having the linter only run against the files that were updated rather than every file in the repo every time?

2021-04-27 13:33 UTC, Smitholi67 commented on CONTRIBUTING.md
> +Once you see an issue that you'd like to work on, please post a comment saying
Where should we post such a comment about starting to work on something?   Is this exclusively for working on Issues or does it apply to eventual PRs?  For example, @sishbi and I have started to prepare a Use Case but we are currently drafting something outside Github.  We will eventually create a PR.   The question is whether we are wanting to know about "Work in Progress" items?

2021-04-27 13:41 UTC, sishbi commented on CONTRIBUTING.md
> +Once you see an issue that you'd like to work on, please post a comment saying
@Smitholi67 I *think* we are meant to post a comment to this discussion: https://github.com/cncf/cnf-wg/discussions/39 to put a line in the sand about starting a new use-case.
@taylor Is that correct?

2021-04-27 14:07 UTC, xmulligan commented
@jeffsaelens that is a very good point. I've added a contributing code section in the latest commit

2021-04-27 14:07 UTC, jeffsaelens commented on CONTRIBUTING.md
> +Once you see an issue that you'd like to work on, please post a comment saying
@sishbi if it builds upon that use case, then you can definitely add it there. If it is a brand new use case, I'd start a fresh discussion. @Smitholi67 The trend we've seen is people will start a discussion (this is a great way to generate some movement on anything you want to dive in to), get some feedback and put in a PR.

2021-04-27 14:08 UTC, jeffsaelens commented on CONTRIBUTING.md
> +- [Kubernetes Network Plumbing](https://github.com/k8snetworkplumbingwg) implementes a common standard addressing how one may attach multiple networks to pods in Kubernetes
love it.

2021-04-27 17:49 UTC, lixuna requested changes
updated grammar and relative links

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +CNF WG doesn't develop any code, but it's work feeds into many groups that do develop code both upstream and downstream. If you want to take the work of the CNF WG and put it into code, check out:
```suggestion
CNF WG doesn't develop any code, but its work feeds into many groups that do develop code both upstream and downstream. If you want to take the work of the CNF WG and put it into code, check out:
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +- [Kubernetes Network Plumbing](https://github.com/k8snetworkplumbingwg) implementes a common standard addressing how one may attach multiple networks to pods in Kubernetes
```suggestion
- [Kubernetes Network Plumbing](https://github.com/k8snetworkplumbingwg) implements a common standard addressing how one may attach multiple networks to pods in Kubernetes
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +feedback on others’ ideas. Simply sharing your own ideas, and experiences can help in ways you might not initially realize.
```suggestion
your feedback. Simply sharing your own ideas, and experiences can help in ways you might not initially realize.
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +Over time, we hope that you feel comfortable voicing your opinions, giving
```suggestion
Over time, we hope that you feel comfortable voicing your opinions and giving
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +### [Come to Meetings](https://github.com/cncf/cnf-wg#meetings)
```suggestion
### [Come to Meetings](#meetings)
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
>  - Go to the [GitHub Discussion board](https://github.com/cncf/cnf-wg/discussions)
```suggestion
- Go to the [GitHub Discussion board](discussions)
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
>  Review, contribute to, create new [GitHub issues](https://github.com/cncf/cnf-wg/issues).
```suggestion
Review, contribute to, create new [GitHub issues](issues).
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +for any contributor. [good first issue](https://github.com/cncf/cnf-wg/labels/good%20first%20issue) has extra information to
```suggestion
for any contributor. [good first issue](labels/good%20first%20issue) has extra information to
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +help you make your first contribution. [help wanted](https://github.com/cncf/cnf-wg/labels/help%20wanted) are issues
```suggestion
help you make your first contribution. [help wanted](labels/help%20wanted) are issues
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +don’t know where to start or can't find a suitable issue, you can reach out to one of the [co-chairs](https://github.com/cncf/cnf-wg#current-co-chairs).
```suggestion
don’t know where to start or can't find a suitable issue, you can reach out to one of the [co-chairs](#current-co-chairs).  
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +Reviews and comments on open [Pull Requests](https://github.com/cncf/cnf-wg/pulls) are always appreciated.
```suggestion
Reviews and comments on open [Pull Requests](pulls) are always appreciated.
```

2021-04-27 17:49 UTC, lixuna commented on CONTRIBUTING.md
> +The best way to reach us with a question when contributing is to ask on
```suggestion
The best way to reach us with a question when contributing is to ask on:
```

2021-04-27 17:54 UTC, taylor requested changes

2021-04-27 17:54 UTC, taylor commented on CONTRIBUTING.md
> +feedback on others’ ideas. Simply sharing your own ideas, and experiences can help in ways you might not initially realize.
```suggestion
Over time, we hope that you feel comfortable voicing your opinions, ideas and providing feedback with the community. Sharing your own ideas, and experiences can help in ways you might not initially realize.
```

2021-04-27 18:36 UTC, electrocucaracha commented on CONTRIBUTING.md
> +- We use Github Actions to test all pull requests. We require that all tests succeed on a pull request before it is merged.
this repo contains a *Makefile* for running linting tasks locally,  so executing `make lint`  could be another way to check things before GH actions.

2021-04-28 10:03 UTC, xmulligan commented on CONTRIBUTING.md
> +- We use Github Actions to test all pull requests. We require that all tests succeed on a pull request before it is merged.
```suggestion
- We use Github Actions to test all pull requests. We require that all tests succeed on a pull request before it is merged. This repo also contains a *Makefile* for running linting tasks locally. Executing `make lint`  is another way to check your work before GitHub actions.
```

2021-04-28 10:03 UTC, xmulligan commented on CONTRIBUTING.md
> +- We use Github Actions to test all pull requests. We require that all tests succeed on a pull request before it is merged.
thanks, I've just added it

2021-04-28 10:05 UTC, xmulligan commented on CONTRIBUTING.md
> +Once you see an issue that you'd like to work on, please post a comment saying
maybe we should document this process somewhere? in the use case file or template?

2021-04-28 11:06 UTC, xmulligan commented on CONTRIBUTING.md
> +###
```suggestion
### Code Contributions
```

2021-04-28 11:08 UTC, xmulligan commented
@lixuna it seems all the relative links you added broke the lint and return 404. Can you check them again?

2021-04-28 15:38 UTC, lixuna commented
@xmulligan I see that 5 of the relative links I added are showing errors in the linter. These links are not part of code or documentation, but are core GitHub functions, eg. discussions, issues, labels, pull requests. 

I'll look into if GitHub supports relative links to those areas and adjust the links accordingly.

ERROR: 5 dead links found!
[✖] discussions → Status: 400
[✖] issues → Status: 400
[✖] labels/good%20first%20issue → Status: 400
[✖] labels/help%20wanted → Status: 400
[✖] pulls → Status: 400

2021-04-28 15:50 UTC, lixuna requested changes
Reverting back to absolute links for core GitHub functions: discussions, issues, labels, pulls

2021-04-28 15:50 UTC, lixuna commented on CONTRIBUTING.md
> +- Go to the [GitHub Discussion board](discussions)
```suggestion
- Go to the [GitHub Discussion board](https://github.com/cncf/cnf-wg/discussions)
```

2021-04-28 15:50 UTC, lixuna commented on CONTRIBUTING.md
> +Review, contribute to, create new [GitHub issues](issues).
```suggestion
Review, contribute to, create new [GitHub issues](https://github.com/cncf/cnf-wg/issues).
```

2021-04-28 15:50 UTC, lixuna commented on CONTRIBUTING.md
> +for any contributor. [good first issue](labels/good%20first%20issue) has extra information to
```suggestion
for any contributor. [good first issue](https://github.com/cncf/cnf-wg/labels/good%20first%20issue) has extra information to
```

2021-04-28 15:50 UTC, lixuna commented on CONTRIBUTING.md
> +help you make your first contribution. [help wanted](labels/help%20wanted) are issues
```suggestion
help you make your first contribution. [help wanted](https://github.com/cncf/cnf-wg/labels/help%20wanted) are issues
```

2021-04-28 15:50 UTC, lixuna commented on CONTRIBUTING.md
> +Reviews and comments on open [Pull Requests](pulls) are always appreciated.
```suggestion
Reviews and comments on open [Pull Requests](https://github.com/cncf/cnf-wg/pulls) are always appreciated.
```

2021-04-28 16:11 UTC, taylor commented
Following up on what @lixuna said regarding relative link usage.  I see no documentation from GitHub on relative links to their built-in services.  Eg. 
- https://guides.github.com/features/mastering-markdown/ 
- https://docs.github.com/en/github/writing-on-github

The documentation (and code) uses a branch, while the services do not. It looks like using '../..' would work to reference services (from the top level.  More ../ would be needed for subdirs).  Not elegant.

Here are some tests with the links https://github.com/taylor/github-markdown-testing#link-test

I suggest for now we use full urls for those services.

2021-04-28 16:13 UTC, taylor approved these changes

2021-04-30 18:37 UTC, sishbi commented on CONTRIBUTING.md
> +Once you see an issue that you'd like to work on, please post a comment saying
Yes that would be good. The use case template mentions the discussion I stated so that would need editing

2021-04-30 18:38 UTC, sishbi requested changes

2021-04-30 18:38 UTC, sishbi commented on CONTRIBUTING.md
> +5 approvals from the community are needed to merge PRs so your review is greatly appreciated.
```suggestion
Up to 5 approvals from the community are needed to merge PRs so your review is greatly appreciated.
```

2021-04-30 21:28 UTC, taylor commented on CONTRIBUTING.md
> +5 approvals from the community are needed to merge PRs so your review is greatly appreciated.
Hmmm... 5 approvals are currently needed for most PRs.  Not sure about this wording @sishbi

2021-05-01 07:23 UTC, sishbi commented on CONTRIBUTING.md
> +5 approvals from the community are needed to merge PRs so your review is greatly appreciated.
Because some PRs only need a single approval so stating 5 approvals here is not correct and the clarification of how many approvals are needed is described later in the document

2021-05-03 17:59 UTC, xmulligan commented on CONTRIBUTING.md
> +5 approvals from the community are needed to merge PRs so your review is greatly appreciated.
That's a good point, thanks for the catch

2021-05-03 18:04 UTC, xmulligan commented on CONTRIBUTING.md
> +Once you see an issue that you'd like to work on, please post a comment saying
@sishbi I've tried to make it more clear in this PR. Does that help? https://github.com/cncf/cnf-wg/pull/157/commits/be3a10533b1c853a3ace4e0192124b825024cfb7

2021-05-04 06:24 UTC, sishbi approved these changes

2021-05-04 15:27 UTC, lixuna approved these changes
LGTM, thanks!

2021-05-04 15:31 UTC, fkautz approved these changes

2021-05-04 15:32 UTC, Smitholi67 approved these changes
lgtm

2021-05-04 15:32 UTC, iawells approved these changes
Good candidate for a squash during merge.

2021-05-04 15:33 UTC, tokt approved these changes
LGTM

2021-05-04 15:34 UTC, ildikov commented on CONTRIBUTING.md
> +before you submit your code:
```suggestion
before you submit your change:
```

2021-05-04 15:35 UTC, ildikov commented on CONTRIBUTING.md
> +before you submit your code:
As we say above that "CNF WG doesn't develop any code" it might get confusing if we refer to code here. Could be fixed in a follow up PR, not a blocking issue.

2021-05-04 15:41 UTC, lixuna commented
The linter error does not seem valid @electrocucaracha @iawells 

```
2021-05-03 18:05:17 [ERROR]   Found errors in [markdownlint] linter!
2021-05-03 18:05:17 [ERROR]   Error code: 1. Command output:
------
/github/workspace/GOVERNANCE.md:61 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Voting Procedure"]
```


I can see that the `main` branch showed this error with the GOVERNANCE.md's "### Voting Procedure" header missing a blank line after the header, but someone has addressed the problem in this [`expand-contributing` branch](https://github.com/cncf/cnf-wg/edit/expand-contributing/GOVERNANCE.md).  

There are blank lines above and below the header named "Voting Procedure" in the [`expand-contributing` branch](https://github.com/cncf/cnf-wg/edit/expand-contributing/GOVERNANCE.md), as the linter would expect.

Does the linter run against all branches or only the branch for the current PR?

2021-05-04 15:46 UTC, taylor requested changes

2021-05-04 15:46 UTC, taylor commented on CONTRIBUTING.md
> +- We use Github Actions to test all pull requests. We require that all tests succeed on a pull request before it is merged. This repo also contains a *Makefile* for running linting tasks locally. Exe
```suggestion
- We use Github Actions to test all pull requests. We prefer that all tests succeed on a pull request before it is merged. This repo also contains a *Makefile* for running linting tasks locally. Executing `make lint`  is another way to check your work before GitHub actions.
```

I suggest making passing preferred, but optional as the linting (at least) has problematic failures and is unreliable.  For example, see:
- https://github.com/cncf/cnf-wg/pull/157#issuecomment-826398602
- https://github.com/cncf/cnf-wg/pull/157#issuecomment-832041412

2021-05-04 15:48 UTC, taylor approved these changes

2021-05-04 15:51 UTC, ildikov approved these changes

2021-05-04 15:53 UTC, electrocucaracha approved these changes

2021-05-04 15:54 UTC, merged