CNF definition
lfn-cnti/bestpractices pull request #161
Opened 2021-04-26 21:05 UTC by jeffsaelens

Update to the glossary with second crack at the CNF definition. The term cloud native will be referenced with the assumption that it too will be spelled out in more detail in the glossary. This PR will be for a single definition that the group can focus on. Please reference discussions #136 and #27 .

2021-04-26 22:46 UTC, taylor requested changes

2021-04-26 22:46 UTC, taylor commented on GOVERNANCE.md
> +
note: this is to fix the linter complaints

2021-04-26 22:46 UTC, taylor commented on doc/glossary.md
> +**Cloud-Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices and has been
```suggestion
**Cloud-Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices which can be delivered and has been developed using Cloud Native Principles including loose coupling, immutable infrastructure, declarative APIs, and a “repeatable deployment process”.
```

2021-04-26 22:46 UTC, taylor commented on doc/glossary.md
> +**Cloud-Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices and has been
@jeffsaelens added delivery since we talk about both development and the deployment of CNFs.

2021-04-27 03:23 UTC, jeffsaelens commented on doc/glossary.md
> +**Cloud-Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices and has been
@xmulligan pulled the hyphens out of the other pages. Turns out the style guide tosses grammar out with the bath water ;-) other than that, I like the changes.

2021-04-27 07:42 UTC, CsatariGergely approved these changes

2021-04-27 08:56 UTC, xmulligan approved these changes

2021-04-27 18:00 UTC, taylor approved these changes
lgtm

2021-04-27 18:25 UTC, electrocucaracha commented
I'm okay with this definition but IMHO this relies on the Cloud-Native application definition which is in the same document and it's not defined yet so it seems to partially defining it.

2021-04-27 18:43 UTC, xmulligan commented
@electrocucaracha that's actually a really good point, we are defining it with something we haven't defined and isn't really defined elsewhere

2021-04-28 01:34 UTC, jeffsaelens commented
> @electrocucaracha that's actually a really good point, we are defining it with something we haven't defined and isn't really defined elsewhere

Agreed, why I called out in the PR that this definition is assuming that we are going to more clearly define Cloud Native above in this glossary. Its the loose definition of that term that makes everything else more difficult to define.

2021-05-05 15:52 UTC, electrocucaracha commented
> > @electrocucaracha that's actually a really good point, we are defining it with something we haven't defined and isn't really defined elsewhere
> 
> Agreed, why I called out in the PR that this definition is assuming that we are going to more clearly define Cloud Native above in this glossary. Its the loose definition of that term that makes everything else more difficult to define.

Maybe we can use/refer to the [CNCF glossary definition](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md)

2021-05-10 16:37 UTC, sishbi commented
I approve...

2021-05-10 16:40 UTC, jeffsaelens reviewed
Check newest iteration

2021-05-10 16:40 UTC, jeffsaelens commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices which can be
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF has been developed using Cloud Native Principles and allows for a “repeatable deployment process”.
```

2021-05-10 16:41 UTC, sishbi approved these changes

2021-05-10 16:42 UTC, Smitholi67 approved these changes

2021-05-10 16:47 UTC, electrocucaracha commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices which can be
What about adding a link to the glossary definition 
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements network functionality. A CNF has been developed using Cloud Native Principles and allows for a “repeatable deployment process”.
```

2021-05-10 16:50 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF has been developed using Cloud Native Principles a
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements network functionality. A CNF has been developed using Cloud Native Principles and allows for a “repeatable deployment process”.
```

2021-05-10 16:52 UTC, electrocucaracha approved these changes

2021-05-10 16:57 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements network functionality. A CNF is developed using Cloud Native Principles to enable desired behavior such as “repeatable deployment process”.
```

2021-05-10 16:58 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements
Repeatable deployment process is a desired behaviour.

2021-05-10 17:01 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) developed using Cloud Native principles that implements network functionality. 
```

2021-05-10 17:05 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that implements
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) developed using Cloud Native principles that provides network functionality. 
```

- Pankaj

2021-05-10 17:06 UTC, v1k0d3n approved these changes
LGTM

2021-05-10 17:07 UTC, electrocucaracha approved these changes

2021-05-10 17:08 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) developed using
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md), developed using cloud native principles, that provides network functionality. 
```

2021-05-10 17:12 UTC, v1k0d3n approved these changes
LGTM

2021-05-10 17:17 UTC, taylor commented on doc/glossary.md
> +**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md), developed using
```suggestion
**Cloud Native Network Function** - A cloud native network function (CNF) is a [cloud native application](https://github.com/cncf/glossary/blob/main/definitions/cloud_native_apps.md) that provides network functionality, which is developed using cloud native principles. 
```

2021-05-10 17:30 UTC, merged