add 5G RAN use cases
lfn-cnti/bestpractices pull request #168
Opened 2021-05-10 10:49 UTC by ashishsanjaysharma

2021-05-10 16:36 UTC, iawells commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> The cloud native platform should be able to maintain the synchronization/timing of the telco workloads.
While this statement is true, we need a threshold to test against, I think.  There doesn't seem to be a universal opinion of what a platform should provide.  RAN vendors express themselves in different ways, such 'you will put this content in this platform config file' (one option, possibly of many) and 'if the application passes its system tests you have it right' (true, but that testing is very late in the process and doesn't allow the platform to be independent of the application).  We actually need 'the application runs if the platform *behaves* in this way' if we want the application to be properly independent of the platform. 

Also, there are two different elements of what's going on here and they're being mixed up.  One is how the PTPSyncE clock is provided to the application, which is necessary for the application to run.  The other is the real-time behaviour of the platform, and please note that there is no detailed specification of what real-time means - what it means to a UI developer and to someone doing hardware control is very different, and RAN falls somewhere between those two.

This use case is very good, but we need to add some details to it to make it testable, and we will probably have to add more in the future (let's not assume we must have it perfectly correct first time or we'll never commit anything).

2021-05-10 21:13 UTC, fkautz requested changes

2021-05-10 21:13 UTC, fkautz commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> Kubernetes could have a time-sensitive gateway or a particular gateway that keeps track of synchronization/timing distributed from the network or GPS to workloads. This would help workload maintain
Should this be in kubernetes? Why not drive this as a requirement from the host? Are you expecting the workloads to process the PTP packet, or is the kernel dealing with this? It may be better to expose this through the clock_gettime syscall if the syscall overhead isn't too high.

Also, if accuracy is paramount, we might need to consider CPU pinning here since the clock for each core is independent. Hopefully we don't need to do this though.

2021-05-10 21:13 UTC, fkautz commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> In container-based virtualized systems(vDU/vCU) or CNFs, the platform manages the workloads. In cloud native design, a monolithic vDU or vCU would result in many individual workloads. 5G has critic
In a Linux container, the clock is likely not virtualized. We should confirm though.

2021-05-10 21:47 UTC, iawells commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> Kubernetes could have a time-sensitive gateway or a particular gateway that keeps track of synchronization/timing distributed from the network or GPS to workloads. This would help workload maintain
You need accurate time sync; I'm not actually clear if clock_gettime is what is used to retrieve the clock or if there's more to it, since there's no concrete guarantee on how long a Linux syscall takes to return when you call it.  A RAN vendor would be welcome here to speak on this with more certainty.  I understand that PTP is generally processed by the host (and therefore the platform) and not passed to the app as raw packets but as deduced timing information.

You also, independently (though for similar reasons), need RT behaviour down to a high level of precision - specifically, delivering a specific quantity of CPU to a vDU within a given time period (in the msec frame).  This is not an easy thing to guarantee with conventional pre-emptive multitasking systems.   CPU pinning is very likely to be required to help with that, but there's more than that to it.

CPU pinning is in fact not a guarantee of anything at the application level; it's a guarantee that certain things won't happen in the system, with an _implication_ that performance will be better as a result (but no promises as to the achieved performance level).  NUMA is another feature of the same type.  Alone, they don't get you to the guarantee mentioned above.

The key distinction here is between 'guarantee' and 'best effort'.  Best effort is not enough for some of the work running here.  Statistically analysed best effort (e.g. '90% of the time you get this') might be acceptable, but it's hard to prove that's what you're getting, because you're proving a negative - specifically it's hard to demonstrate that there aren't rare cases (once a week, say) where that guarantee doesn't hold.  Things like web apps are fine with best effort, because what they're effectively asking for a weak statistical guarantee ('don't delay a web response by 100ms too often') and it's so all-encompassing that exceptions are vanishingly rare and can be addressed one by one by the ops team - so this is where our workloads differ from the norm.

2021-05-13 17:04 UTC, sishbi requested changes
I don't fully understand the RAN terminology but I can read along.
The formatting of these 2 use cases needs fixing to remove the additional quoted text marker: '>'
Also the lists should use '-' to create a bulleted list.

This has an interesting proposal for using a multi-network interface CNI that enables cross-Pod IPC communication

2021-05-13 17:04 UTC, sishbi commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> PTP - Precision Time Protocol
```suggestion
- PTP - Precision Time Protocol
```
This list should use a bullet '-' instead of the '>' symbol as the list doesn't render correctly otherwise.

2021-05-13 17:04 UTC, sishbi commented on use-case/5G_RAN/0002-UC-multi-interface.md
> +> DU - Distributed Unit  support  RLC, MAC, Physical layers
Needs an explanation of what 'RLC' and 'MAC' mean

2021-05-13 21:57 UTC, electrocucaracha commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +- [x] Operations
```suggestion
- [x] Development
- [x] Deployment
- [x] System integration
- [x] Network integration
- [ ] Lifecycle management
- [x] Operations
```

2021-05-13 21:57 UTC, electrocucaracha commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> PTP - Precision Time Protocol
@sishbi suggestion applies to the rest of the document

2021-05-13 21:57 UTC, electrocucaracha commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> The K8s egress/ingress gateway is limited to web-based traffic. They are not aware of time stamped packets, like PTP packets. These packets are time-critical and they do not identify or process dif
I just wondering if [Service Topology awareness](https://kubernetes.io/docs/concepts/services-networking/service-topology/) can help on this Kube-Native approach

2021-05-17 16:48 UTC, taylor commented
Discussion for timing on K8s and linux hosts -> https://github.com/cncf/cnf-wg/discussions/174

2021-06-14 17:26 UTC, iawells commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> In container-based virtualized systems(vDU/vCU) or CNFs, the platform manages the workloads. In cloud native design, a monolithic vDU or vCU would result in many individual workloads. 5G has critic
What would a 'virtualised' clock mean, exactly?  I'm unclear on your point.

2021-07-12 16:55 UTC, pgoyal01 commented on use-case/5G_RAN/0001-UC-sync-timing-ran.md
> +> In container-based virtualized systems(vDU/vCU) or CNFs, the platform manages the workloads. In cloud native design, a monolithic vDU or vCU would result in many individual workloads. 5G has critic
"In cloud native design, a monolithic vDU or vCU would result in many individual workloads" is the intent here to say that a redesign of a monolithic application will result in multiple components? If that is the case, let us say so clearly.

2021-07-12 22:34 UTC, taylor commented
We are merging this PR into a new branch, https://github.com/cncf/cnf-wg/tree/wip-5g_ran_use_cases, where we will continue to work on items outlined in the the PR comments and Monday CNF WG meeting.  We may create a PR for each use case when adding to main.

2021-07-12 22:35 UTC, merged