New use case: Onboarding of CNFs to the platform
lfn-cnti/bestpractices pull request #175
Opened 2021-05-18 13:56 UTC by vukg

Here is new use case that covers challenges with packaging, distribution and deployment of CNFs - what we colloquially call CNF "onboarding". I am looking forward to hear the feedback from the community. There is for sure improvement potential for this PR, but there is already enough material for comments.

Bests,
Vuk

2021-05-25 14:30 UTC, xmulligan commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For
```suggestion
CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For that they expect to receive well documented installation procedures, references for typical continuous deployment realisations with that particular or similar CNFs as well as comprehensive deployment troubleshooting guide. As already mentioned in (UC0001)[0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md], CNF DevOps team also expects to get suite of tests from CNF vendor. Tests could then be deployed in continous testing pipeline to automatically verify that CNF is running properly (production grade) on the platform and that the deployment qualifies for SLA.
```

2021-05-25 14:30 UTC, xmulligan commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +The starting point of onboarding shall be extension of platfrom with any requiremetns and dependencies that are coming from CNF. When all conditions on the platform level are met, the deployment of C
```suggestion
The starting point of onboarding shall be extension of platform with any requiremetns and dependencies that are coming from CNF. When all conditions on the platform level are met, the deployment of CNF shall proceed.
```

2021-05-25 14:30 UTC, xmulligan commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +Finally, the CNFs are frequently delivered as Helm charts. However, these Helm charts often do not cover all dependencies that enables reconciling the deployments in propper way. They also install CR
```suggestion
Finally, the CNFs are frequently delivered as Helm charts. However, these Helm charts often do not cover all dependencies that enables reconciling the deployments in proper way. They also install CRDs which are not managed well by Helm.
```

2021-06-14 14:56 UTC, electrocucaracha reviewed
Linting suggestions

2021-06-14 14:56 UTC, electrocucaracha commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For
```suggestion
CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For that they expect to receive well documented installation procedures, references for typical continous deployment realisations with that particular or similar CNFs as well as comprihensive deployment troubleshooting guide. As already mentioned in [UC0001](0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md), CNF DevOps team also expects to get suite of tests from CNF vendor. Tests could then be deployed in continous testing pipeline to automatically verify that CNF is running properly (production grade) on the platform and that the deployment qualifies for SLA.
```

2021-06-14 14:56 UTC, electrocucaracha commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +* https://learnk8s.io/production-best-practices
```suggestion
- [The Chart Best Practices Guide](https://helm.sh/docs/chart_best_practices/)
- [GitOps](https://www.gitops.tech/)
- [Kubernetes production best practices](https://learnk8s.io/production-best-practices)
```

2021-07-13 09:00 UTC, CsatariGergely requested changes

2021-07-13 09:00 UTC, CsatariGergely commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF vendor expects that CSP platform and environment (e.g. Network) are fulfiling certain requirements and preconditions for CNF to be able to achieve production grade deployment. These requirements
How about Anuket RA2. It's main target is to "standardize" the "certain requirements and preconditions".

2021-07-13 09:00 UTC, CsatariGergely commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +The starting point of onboarding shall be extension of platform with any requiremetns and dependencies that are coming from CNF. When all conditions on the platform level are met, the deployment of C
```suggestion
The starting point of onboarding shall be extension of platform with any requirements and dependencies that are coming from CNF. When all conditions on the platform level are met, the deployment of CNF shall proceed.
```

2021-07-13 09:00 UTC, CsatariGergely commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +Most of the CNFs today, especially complex ones, are packaged in such way that only trained professional service teams of the CNF vendor can reasonably deploy them. The documentation and manuals that
Shouldn't be the DevOps team a cross organisational team?

2021-07-23 10:00 UTC, xmulligan commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For
```suggestion
CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For that they expect to receive well documented installation procedures, references for typical continuous deployment realisations with that particular or similar CNFs as well as comprehensive deployment troubleshooting guide. As already mentioned in (UC0001)[0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md], CNF DevOps team also expects to get suite of tests from CNF vendor. Tests could then be deployed in continuous testing pipeline to automatically verify that CNF is running properly (production grade) on the platform and that the deployment qualifies for SLA.
```

2021-07-23 11:17 UTC, vukg commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +Most of the CNFs today, especially complex ones, are packaged in such way that only trained professional service teams of the CNF vendor can reasonably deploy them. The documentation and manuals that
Hi Gergely,
When CNF DevOps and Cloud-native Platform DevOps work together it is cross-organisational. It is also advisable that CNF DevOps team has also members who possess CKA-like knowledge and who can deal with deployments, but it depends on the size of the organisation.

Does that make sense?
-Vuk

2021-07-23 11:19 UTC, vukg commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF vendor expects that CSP platform and environment (e.g. Network) are fulfiling certain requirements and preconditions for CNF to be able to achieve production grade deployment. These requirements
Anuket to my knowledge is perscriptive when it comes to selection of components and their versions. It does not provide generalized requirements. However, number of requirements could be derived from it.

2021-07-23 11:20 UTC, vukg commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For
for some reason I can not commit your suggestion @electrocucaracha , but it is fine by me. Can someone e.g. @taylor committ it?

2021-07-26 12:25 UTC, xmulligan commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +The practices already exist outside of CNF world, but are not very well followed by CNF vendors. Some of the practices are here:
```suggestion
The practices already exist outside of CNF world, but are not very well followed by CNF vendors. Some of the practices are here:

```

2021-07-26 12:25 UTC, xmulligan commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +The practices already exist outside of CNF world, but are not very well followed by CNF vendors. Some of the practices are here:
for linting

2021-08-09 16:13 UTC, iawells commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF vendor expects that CSP platform and environment (e.g. Network) are fulfiling certain requirements and preconditions for CNF to be able to achieve production grade deployment. These requirements
```suggestion
CNF vendor expects that CSP platform and environment (e.g. Network) are fulfilling certain requirements and preconditions for CNF to be able to achieve production grade deployment. These requirements are different from CNF to CNF.
```

2021-08-09 16:13 UTC, iawells commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +The starting point of onboarding shall be extension of platform with any requiremetns and dependencies that are coming from CNF. When all conditions on the platform level are met, the deployment of C
```suggestion
The starting point of onboarding shall be extension of platform with any requirements and dependencies that are coming from CNF. When all conditions on the platform level are met, the deployment of CNF shall proceed.
```

2021-09-20 16:18 UTC, jeffsaelens approved these changes
This is a good starting point. I'll add the user story as an additional PR in the near future.

2021-09-20 16:19 UTC, fkautz approved these changes

2021-09-20 16:19 UTC, taylor approved these changes
lgtm

2021-09-20 16:19 UTC, Smitholi67 approved these changes

2021-09-20 16:21 UTC, electrocucaracha approved these changes

2021-09-20 16:25 UTC, merged

2021-09-20 16:27 UTC, tliron commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF vendors need to start preparing CNFs for shipping as regular cloud software that is well docummented and that can be deployed and configured by CNF DevOps team. Following established best practic
Spelling mistake: "docummented"

2021-09-20 16:28 UTC, tliron commented on use-case/0004-UC-onboarding-of-CNF-to-the-CSP-platform.md
> +CNF DevOps team expects to deploy and configure the CNF application on their own, preferably directly via automation pipelines and in interaction and cooperation with CNPD and CSP Network teams. For
Wrong markdown for UC001 link (first brackets, then parentheses)