Initial draft for a no root in containers best practice
lfn-cnti/bestpractices pull request #182
Opened 2021-07-22 19:41 UTC by taylor

This covers the least privilege best practice of avoiding running processes as root in containers

See least privilege issue #67 and discussion https://github.com/cncf/cnf-wg/discussions/20

Co-authored-by: Ian Wells <iawells@cisco.com>

2021-07-23 11:27 UTC, vukg commented
/lgtm
one of very important practices that we for example enforce at admission

2021-07-23 16:03 UTC, electrocucaracha reviewed
Are "no root" and "non-root" terms the same? If that's true the document uses those interchangeably so I'll be nice to clarify it.

2021-07-23 16:03 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
IMHO Application's bugs is a generic term which cover many aspects. AFAIU, the main idea is to reduce the attack surface by limiting the permissions.

```suggestion
Avoiding the usage of root user in containers improves the security reducing the attack surface on vulnerabilities .  It is also part of a defense in depth strategy against external compromises.
```

2021-07-23 16:03 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process included using a user cgroup, which means that the containers' users are distinct
> containers' users are distinct from the platform's users

This is true as long as the Container Runtime is using user namespaces to map the users

https://docs.docker.com/engine/security/userns-remap/

2021-07-23 16:03 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +- Do not run the container is privileged
What about using [rootless](https://www.docker.com/blog/experimenting-with-rootless-docker/) solutions like [usernetes](https://github.com/rootless-containers/usernetes)? Or using another runtime like [Kata Containers](https://katacontainers.io/)?

2021-07-23 16:28 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +- Do not run the container is privileged
Apparently this [KEP](https://github.com/kubernetes/enhancements/pull/2101) is going to address some of this issues as well

2021-07-23 17:17 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +- Do not run the container is privileged
rootless installs of k8s are interesting but not what we're trying to address here, this is specifically about the use of container root in apps and that's about the use of system root in the platform.

Kata containers (and clearcontainers) are interesting side cases; they're not using 'containers' in the conventional case, a constrained use of the host kernel, but looking at lightweight virtualisation to run container workloads in individual VMs.  Testing the 'don't use root' would certainly work differently there because there's no way that the container runtime isn't going to use root somewhere - but if it's compatible with container payloads all the reasoning and recommendations should still apply.

I need to read the user-accessible namespace (KEP) thing in more depth.  It depends how you access other namespaces.  Switching namespaces requires more than container root, normally; it requires CAP_NET_ADMIN.  I don't know what their thinking is regarding privileges, there.

2021-07-26 16:08 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
The second sentence reads weird (flow is off).

2021-07-26 16:08 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +Both of these benefit the CNF developer directly, improving the quality of the CNF.  Validation of the best practice is the responsibility of the CNF developer.
Both of what?

2021-07-26 16:08 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
This isn't written as a goal.

2021-07-26 16:08 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +When building a container, the container should be build to run its processes as a non-root user.  setsid processes should not be required to do the work inside a container.
My suggested change button is MIA, build should be built*

2021-07-26 16:08 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +Container images are frequently built from upstream image versions made from OS deployments.  These will include things like setsid binaries as a part of their base configuration.  If CNF developers
This leads into another best practice around scanning and onboarding CNFs :-)

2021-07-26 16:08 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +Inside a compliant application, all containers will avoid use of root.
Do we want to flesh out here what tests we would like to see? If it's in the test suite already, then we're good to go. If it is not, we could bring those to the test suite team. This could be a way to provide the CNF-WG folks who want to write some code an opportunity to contribute automated tests to CNG-TS.

2021-07-26 16:41 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Inside a compliant application, all containers will avoid use of root.
Re-writing to remove the word "compliant"

```suggestion
An application which follows this best practice will not have any containers with processes running as root
```

cc: @tliron @iawells

2021-07-26 17:35 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
```suggestion
Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run these images securely.
```

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Both of these benefit the CNF developer directly, improving the quality of the CNF.  Validation of the best practice is the responsibility of the CNF developer.
```suggestion
This best practice benefits the CNF developer, improving the quality of the CNF and reducing the developer's likelihood of having to diagnose problems with the CNF.  Validation of the best practice is the responsibility of the CNF developer.
```

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
It is not exclusively that.  Running processes as non-root means that software flaws should be identifiable earlier.  It does mean that compromises can't get so far, and that's a major part of its benefit, but it's not the only benefit.

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
What would a goal look like?

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +When building a container, the container should be build to run its processes as a non-root user.  setsid processes should not be required to do the work inside a container.
```suggestion
When building a container, the container should be built to run its processes as a non-root user.  setsid processes should not be required to do the work inside a container.
```

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process included using a user cgroup, which means that the containers' users are distinct
Do we need to write that down as its own best practice?

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Container images are frequently built from upstream image versions made from OS deployments.  These will include things like setsid binaries as a part of their base configuration.  If CNF developers
Acceptance testing stages should be in the receiving process, yep.  That's a process, though, not a best practice, so I wonder how we write that down.

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +## Test Plan
```suggestion
## Test Objectives
```

2021-07-26 17:44 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +## Test Plan
(per @jeffsaelens' other pull request and comments)

2021-07-26 18:10 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
@electrocucaracha a root process could cause unintended corruption or delete files that accidentally, both of which might be considered general bugs vs security specific.  This is part of why we did not keep this practice specific to security.

2021-07-26 18:15 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process included using a user cgroup, which means that the containers' users are distinct
Seems like the user namespace mapping would be good additional best practice.

@iawells I think the suggestion is to change the phrasing slightly to not say users will be distinct. @electrocucaracha correct me if I am misunderstanding.

Here is an update based on that understanding:

```suggestion
The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process includes using a user cgroup, which means that the containers' users can be distinct from the platform's users and do not include most dangerous elevated rights. An exception to that separation is if the container runtime is not using user name spaces to map the users.
```

2021-07-26 18:18 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
```suggestion
- Improve the security and behaviour of applications when bugs occur.
- Add to the defense in depth strategy against external compromises.
```

2021-07-26 18:18 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
@jeffsaelens are you looking for something worded more like that ☝🏻

2021-07-26 18:20 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Container images are frequently built from upstream image versions made from OS deployments.  These will include things like setsid binaries as a part of their base configuration.  If CNF developers
@jeffsaelens add to a new or existing discussion https://github.com/cncf/cnf-wg/discussions.

Maybe something like:
- Applications should be auditable for security vulernabilities when onboarding by a receiving party.

2021-07-27 14:09 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +Avoiding the root user in containers improves the security and behaviour of applications when bugs occur.  It is also part of a defense in depth strategy against external compromises.
Yes 👍🏻

2021-07-27 14:10 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +When building a container, the container should be build to run its processes as a non-root user.  setsid processes should not be required to do the work inside a container.
```suggestion
When building a container, the container should be built to run its processes as a non-root user.  setsid processes should not be required to do the work inside a container.
```

And suddenly I can suggest edits.

2021-07-27 17:36 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process included using a user cgroup, which means that the containers' users are distinct
```suggestion
The root user in a container has less Linux Kernel capabilities and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
```

https://docs.docker.com/engine/security/#linux-kernel-capabilities
https://d3oypxn00j2a10.cloudfront.net/assets/img/Docker%20Security/WP_Intro_to_container_security_03.20.2015.pdf

AFAIK Cgroups allow you to allocate resources among user-defined groups of tasks (processes) running on a system.

2021-07-27 17:39 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process included using a user cgroup, which means that the containers' users are distinct
It's confusing.  You're correct, and this wants fixing - it's a user namespace, not a cgroup, so we used the wrong word; but namespaces and (some) cgroups (for instance, the PID cgroup) do very similar things.

2021-07-27 19:23 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +- CNF WG discussion: https://github.com/cncf/cnf-wg/discussions/20
Maybe this [CVE](https://seclists.org/oss-sec/2019/q1/119) has to be referred here

2021-08-02 16:14 UTC, wavell reviewed
+1

2021-08-02 16:26 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Avoid compromised apps causing more damage.
```suggestion
- Avoid compromised apps from causing more damage.
```

2021-08-02 16:33 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer rights and is distinct from the platform's root.  The containerization process included using a user cgroup, which means that the containers' users are distinct
"A container's root user has fewer less Linux Kernel permissions and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature)."

2021-08-02 16:37 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer Linux Kernel capabilities and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
```suggestion
A container's root user has fewer Linux Kernel privileges and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
```

2021-08-02 16:37 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +- CNF WG discussion: https://github.com/cncf/cnf-wg/discussions/20
yes to adding to the references @electrocucaracha

2021-08-02 16:42 UTC, electrocucaracha commented on cbpps/0002-no-root-in-containers.md
> +
```suggestion
- [CVE-2019-5736: runc container breakout](https://seclists.org/oss-sec/2019/q1/119)

```

2021-08-02 16:46 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +- Do not run the container is privileged
```suggestion
- Do not run the container in privileged mode
```

2021-08-02 16:49 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +### Alternatives
```suggestion
### Alternatives / Related Practices
```

2021-08-02 16:53 UTC, tliron commented on cbpps/0002-no-root-in-containers.md
> +### Alternatives
I think this section's purpose is unclear. We *do* need a lot more discussion on:
* You think you need to root in order to achieve X, but actually you don't! There's a specific solution Y that can achieve what you need without root.
* When you do need root (there is no solution Y), what can you do to minimize the risks?

2021-08-16 15:43 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Inside a compliant application, all containers will avoid use of root.
The CNF Test Suite is looking to use [Falco's user_must_run_as_non_root test](https://github.com/falcosecurity/falco/blob/master/test/psps/user_must_run_as_non_root.yaml). The ticket for adding the test is https://github.com/cncf/cnf-testsuite/issues/920

2021-08-16 16:00 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +- Do not run the container is privileged
Added the info you suggested @electrocucaracha

2021-08-16 16:54 UTC, taylor commented
Alternative best practice name: "Container should execute process as non-root user"

2021-08-16 18:42 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Inside a compliant application, all containers will avoid use of root.
We've listed here what we'd like to test for, and we've listed a Falco test identifier with no indication of what it's actually testing for.  Can we make the two meet in the middle?

(We will also need to specify a given version of the Falco test, since future versions might test for something different.)

2021-08-16 18:45 UTC, iawells commented
> Alternative best practice name: "Container should execute process as non-root user"

We're asking for no process ever to run as root in a container, not just the first process so we might want to phase that slightly less ambiguously (or it might be read as 'the *first* process will not be launched as root'); but 'no root in containers' is really no better.

2021-08-17 15:31 UTC, pgoyal01 commented
@iawells would an alternative such as, "Container should execute a process as non-root user" or "Containers should execute processes as non-root user" or "Processes within containers should be executed as a non-root user" or ...

2021-08-17 17:31 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +# CBPP-000N: No root in containers
```suggestion
# CBPP-000N: Container should execute process(es) as non-root user
```

2021-09-27 16:10 UTC, jeffsaelens commented on cbpps/0002-no-root-in-containers.md
> +_TBD: the user stories for access control need writing_
@jeffsaelens add to user story

2021-09-29 23:23 UTC, denverwilliams approved these changes

2021-09-30 07:22 UTC, xmulligan approved these changes

2021-09-30 13:40 UTC, agentpoyo approved these changes
LGTM

2021-09-30 14:51 UTC, michaelspedersen reviewed
Generally looks good, but I have a couple comments and questions as I am a little unclear about the use of "privileged" and "privileges" throughout the BP

2021-09-30 14:51 UTC, michaelspedersen commented on cbpps/0002-no-root-in-containers.md
> +- What about using rootless solutions like usernetes? Or using another runtime like Kata Containers?
Is this supposed to be included (seems more like a WIP note)

2021-09-30 14:51 UTC, michaelspedersen commented on cbpps/0002-no-root-in-containers.md
> +SE-Linux based environments will require dropping root privileges. Example: OpenShift
Is this related to executing as root user or setting 'privileged: true' flag in Docker/K8s when creating the container? If it's related to the privileged flag then I would not consider this motivation by itself.

2021-09-30 14:51 UTC, michaelspedersen commented on cbpps/0002-no-root-in-containers.md
> +A container's root user has fewer Linux Kernel privileges and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
would it make sense to change "privileges" to "capabilities" here (as you can add/remove individual privileges to a container, but privileged is more of a "catch-all")

2021-09-30 14:51 UTC, michaelspedersen commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
I think this example is only partially relevant when talking about non-root. The updated rules could still compromise the firewall and it's functionality regardless of root user. As for compromising the container, this user story is practically identical to the one above.

2021-09-30 14:51 UTC, michaelspedersen commented on cbpps/0002-no-root-in-containers.md
> +We specifically want to run unprivileged process so that their access is limited.  Of course, if access is limited then the CNF developer must ensure that access is still available to the things the
A little unclear on the meaning of "unprivileged". Is this from a container or root user standpoint? Also consider changing "**their** access" in the first sentence to CNF developers

2021-09-30 14:51 UTC, taylor commented
@pgoyal01 please review again. Your items have been resolved and user stories have been added.

2021-09-30 15:00 UTC, ildikov reviewed
Hi,

I have only one nit pick in line, please check.

This patch also seem to contain quite some unrelated changes. I don't know if that's because of a rebase or it's intentionally addressing multiple issues, it would be great to avoid this in the future if possible as it makes reviewing harder.

Thanks,
Ildikó

2021-09-30 15:00 UTC, ildikov commented on cbpps/0002-no-root-in-containers.md
> +- What about using rootless solutions like usernetes? Or using another runtime like Kata Containers?
If we keep these as questions I think they should be a top level item as they don't seem to belong to this list.

2021-09-30 15:24 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
"these images" -- which?
```suggestion
Containers have a list of their users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run these processes securely.
```

2021-09-30 15:29 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer Linux Kernel capabilities and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
I think we are using "privileges"
```suggestion
The root user in a container has fewer privileges than the privileges of the platform's root (if the container runtime enables user namespaces remap feature).
```

2021-09-30 15:34 UTC, wavell approved these changes

2021-09-30 15:34 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +Unix access enforcement (user/group) will be respected. As an added advantage, fine-grained access enforcement, such as SELinux, will also hold.
we are referring to Linux throughout
```suggestion
User/group access enforcement will be respected. As an added advantage, fine-grained access enforcement, such as in SELinux, will also hold.
```

2021-09-30 15:38 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +A OpenVSwitch VNF was containerized and is running on a K8s cluster. It retrieves its routing scripts and logic are defined an externally from remote service. It then applies them to the running cont
Sentence issue
```suggestion
An OpenVSwitch VNF was containerized and is running on a K8s cluster. It retrieves its routing scripts and logic, which are defined externally, from a remote service. It then applies them to the running container instance.
```

2021-09-30 15:39 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest resources it downloaded have been compromised on the central system. The  OpenVSwitch runs compromised code which takes over the container’s process with its own malicious c
```suggestion
Unfortunately, the latest resources it downloaded have been compromised. The  OpenVSwitch runs the compromised code which takes over the container’s process with its own malicious code.
```

2021-09-30 15:48 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +A container's root user has fewer Linux Kernel privileges and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
That one is awkward - poor wording choice, perhaps, but the basic thing that a root user can do with the capabilities typically granted to it (i.e. without any addition privileges added) is change the filesystem regardless of ownership and run things as any user.  There's no reason why that should be needed to run software, and it means that no file in the container is truly immutable.

2021-09-30 15:53 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
Agreed.  This is a flaw in the software design.  In fact, it starts saying 'rules' can be downloaded and ends up saying 'code can be run' - 'code' is not 'rules'. I don't think it's conveying what it intended to say.

It's better phrased as an argument that a container should hold all the code it's going to run and not e.g. download and run executables either (a) at all (ideally) or (b) with excessive privilege (if it must).  Firewalls are not native code, and even if they're a full programming language (typically they're not, so the example is a bit off) then the answer is sandboxing.

2021-09-30 15:54 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +We specifically want to run unprivileged process so that their access is limited.  Of course, if access is limited then the CNF developer must ensure that access is still available to the things the
I think we want to clear up the ambiguity by using 'non-root'.

2021-09-30 20:33 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
@pgoyal01 it's referring to the container images.  Maybe we should say container images?

2021-09-30 20:33 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
@iawells thoughts?

2021-09-30 20:34 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +SE-Linux based environments will require dropping root privileges. Example: OpenShift
@michaelspedersen this best practice is only about executing processes as a non-root user.

2021-09-30 20:36 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +A container's root user has fewer Linux Kernel privileges and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
@michaelspedersen when this is applied to just the case of users running a process vs privliege=true/false for a container do you think the word choice of "privileges" works or do you think "capabilities" is still a better choice?

2021-09-30 20:42 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +- What about using rootless solutions like usernetes? Or using another runtime like Kata Containers?
that was accidental.  I'll remove that. thanks @michaelspedersen

2021-09-30 20:43 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +- What about using rootless solutions like usernetes? Or using another runtime like Kata Containers?
These questions were a mistake and have been removed @ildikov

2021-09-30 20:46 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
@iawells @michaelspedersen is the suggestion to update this user story or remove it entirely and only keep the OpenVSwitch one?

2021-09-30 20:49 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
You might want to keep it handy for future use but it doesn't seem to be relevant to this.  I think the more relevant use case is 'in the event that someone gets malicious code to run in this CNF you don't want the code to have elevated system rights'.  Your use case doesn't quite reflect that.

2021-09-30 20:51 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
And I haven't seen the OVS one in context, but I think you'd have the same problems with it: you're trying to say 'we inject malicious code' which could make use of the system rights levels, but you're actually saying 'we inject malicious _intent_' which is unlikely to make use of those additional rights.

2021-09-30 20:51 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +We specifically want to run unprivileged process so that their access is limited.  Of course, if access is limited then the CNF developer must ensure that access is still available to the things the
updated @michaelspedersen @iawells

2021-09-30 20:53 UTC, pgoyal01 commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
@taylor "container images" would be OK but since that would be first use, we should change "these" to "the"

2021-09-30 20:59 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Containers have a list of their own users independent of the host system, one of which is UID 0, the root user. Containers should run processes as a user other than root which makes it easier to run
Changed to "the container images" @pgoyal01

2021-09-30 21:01 UTC, pgoyal01 approved these changes

2021-09-30 21:05 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
@iawells so need to expand one of the example user stories to have something that would not be accessible without having the exploited process running as the root user.  Thoughts?

2021-09-30 21:24 UTC, iawells commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
So we have two possibilities here.

This user story speaks to 'I can tell OVS to drop a firewall if I can get into its control stream and that would be bad'.  That could better be phrased as 'between the trusted input to an orchestrator or a CNF and the actual behaviour it implements is a bunch of manipulation and transport of that information, if you can get into that and change its behaviour the CNF will misbehave, possible severely'

Another user story would go something like 'I write this clever CNF where you give it a bunch of rules, it compiles those rules into machine code and ships them out to its forwarding elements.  Someone gets in there and replaces that code with code of their own.  When that code is run, it could...?' - as a non-root you still have management network access, you can still contend on poorly defended shared resources (which aren't supposed to exist, but hey, containers); but for more fun you would have to escalate privileges much more than if you were container root with the rights that go along with that.

2021-09-30 22:28 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +A container's root user has fewer Linux Kernel privileges and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
I replaced privileges with capabilities @michaelspedersen

2021-09-30 22:29 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
Replaced these user stories with new ones seen in https://github.com/cncf/cnf-wg/pull/193

2021-09-30 22:30 UTC, taylor commented
@ildikov  
> I have only one nit pick in line, please check.

fixed thanks.

> This patch also seem to contain quite some unrelated changes. I don't know if that's because of a rebase or it's intentionally addressing multiple issues, it would be great to avoid this in the future if possible as it makes reviewing harder.

Yes, that was a rebase. I hoped to avoid updates that were already accepted. Unfortunately, we ended up with more changes showing :/

2021-09-30 22:32 UTC, taylor commented on cbpps/0002-no-root-in-containers.md
> +The root user in a container has fewer Linux Kernel capabilities and may be distinct from the platform's root (if the container runtime enables user namespaces remap feature).
@pgoyal01 there was a request to change some of these things to capabilities so it did not cause confusion with privilege=true/false for containers.

2021-09-30 23:23 UTC, ildikov approved these changes
Thanks for the quick fix, it looks good to me now.

I also think it might be worthwhile to merge this and have follow up PRs in case there are still other bits to fix to avoid it picking up more unrelated changes.

2021-10-01 07:08 UTC, michaelspedersen commented on cbpps/0002-no-root-in-containers.md
> +Unfortunately, the latest set of rules include an exploit while still passing validation by the external system and the firewall CNF itself. The firewall downloads the newly defined rules with the ex
I can see you already had a good discussion. As mentioned by @iawells, the examples are likely still relevant for other BPs. I agree with replacing them with the supply chain user stories.

2021-10-01 07:39 UTC, michaelspedersen approved these changes

2021-10-04 16:20 UTC, electrocucaracha requested changes

2021-10-04 16:20 UTC, electrocucaracha commented on user-stories/supply-chain-attacks.md
> +In this case, if the operator ensures that processes in the container will be run as a normal conatiner user without extra rights, the malicious code will have a very limited ability to do dangerous
```suggestion
In this case, if the operator ensures that processes in the container will be run as a normal container user without extra rights, the malicious code will have a very limited ability to do dangerous things.  It will be harder for it to try to escalate its privileges, it has no rights outside of the container, it cannot change files within the container that could cause more damage (such as root-owned settings files in /etc).
```

2021-10-04 16:20 UTC, electrocucaracha commented on user-stories/supply-chain-attacks.md
> +As an example: the configuration of a CNF might allow the operator to determine paths where a log file is written.  If this path is set to a protected file, then the conatiner root user has the right
```suggestion
As an example: the configuration of a CNF might allow the operator to determine paths where a log file is written.  If this path is set to a protected file, then the container root user has the rights necessary to overwrite that file.  This could be exploited to change configuration and settings files within the container image and subvert it.
```

2021-10-04 16:24 UTC, electrocucaracha approved these changes

2021-10-04 16:32 UTC, merged