added configuration best practices page for Kubernetes system components
lfn-cnti/bestpractices pull request #212
Opened 2022-02-28 15:38 UTC by slashben

2022-03-07 16:14 UTC, iawells commented
1. This is a best practice, not a user story
2. I don't think it's necessary for approval, but if we have some references as to why these are the best practices we choose, that would help
3. We should check our template.  The text is fine but the template has additional sections to fill in.

2022-03-07 16:19 UTC, iawells commented on user-stories/configuration-best-practices.md
> +Allowing anonymous (unauthenticated users) is a bad practice in any production environment. Make sure `--anonymous-auth` is set to false in the API server configuration.
Dupliocate of 'disabling anonymous requests'?

2022-03-07 16:22 UTC, iawells commented on user-stories/configuration-best-practices.md
> +An operator must be able to manage authentication credentials and be able to revoke or rotate them. This is a must since different human errors can lead to leaks or theft, or simply access needs to b
'Not a shared secret' seems to be the most important thing here.

2022-03-07 17:59 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +Kubernetes API server can be configured to accept requests from unauthenticated sources. Anonymous requests have a username of system:anonymous, and a group name of system:unauthenticated and they ca
Can we change this to such that it is only discussing disabling anonymous and unauthorized access?  The default Kubernetes API server configuration permits such access -- it doesn't have to be configured.
```suggestion
Kubernetes API server must be configured to reject requests from unauthenticated/anonymous sources; the default configuration allows such requests. Only authenticated users should be able to make requests to the API server. Set `--anonymous-auth` to `false`.
```

2022-03-07 18:00 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +API server audit logging is the functionality which enables operators to keep a record of external requests to the cluster. It records the requests together with the initiator identity therefore enab
```suggestion
API server audit logging is the functionality that enables operators to keep a record of requests to the cluster. It records the requests together with the initiator identity, therefore, enabling security teams to track events happening in the system.
```

2022-03-07 18:01 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +API server configuration enables versatile configuration of audit logs which can both be delivered to a file or a webhook. See `--audit-log-path` or `--audit-policy-file` configuration.
```suggestion
API server configuration enables versatile configuration of audit logs which can be delivered to a file or a webhook. See `--audit-log-path` or `--audit-policy-file` configuration.
```

2022-03-07 18:09 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +* Attribute-Based Access Control (ABAC) mode allows you to configure policies using local files.
the main point of ABAC is not configuring using local files but finer-grained control of access on resource types rather than user role as in RBAC.

2022-03-07 18:15 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +API server supports multiple client authentication technologies. These technologies answer different authentication needs and therefore there is not a single choice which can be considered a “best pr
is there a verb missing in "... and paramount the security of the API server"

2022-03-07 18:16 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +Different authentication methods support this functionality at different levels. Static token authentication requires restarts to the API server every time a token is revoked. Client certificate auth
does this belong under "API server client authentication" above?

2022-03-21 06:01 UTC, slashben commented on user-stories/configuration-best-practices.md
> +Allowing anonymous (unauthenticated users) is a bad practice in any production environment. Make sure `--anonymous-auth` is set to false in the API server configuration.
It is, I wanted to make a reference to this issue in the context of authentication settings. We can either:
* remove the sentence and just put a reference here
* remove the "disabling anonymous requests" paragraph and move it to here completely

2022-03-21 06:03 UTC, slashben commented on user-stories/configuration-best-practices.md
> +An operator must be able to manage authentication credentials and be able to revoke or rotate them. This is a must since different human errors can lead to leaks or theft, or simply access needs to b
I am not sure about your point here. Do you mean that the most important that the API server has no access to the client secret?

2022-03-21 06:04 UTC, slashben commented on user-stories/configuration-best-practices.md
> +API server audit logging is the functionality which enables operators to keep a record of external requests to the cluster. It records the requests together with the initiator identity therefore enab
Valid point!

2022-03-21 06:26 UTC, slashben commented on user-stories/configuration-best-practices.md
> +* Attribute-Based Access Control (ABAC) mode allows you to configure policies using local files.
Yes, but the point here is rather the ability to manage access control. With ABAC you need to manage configuration file(s) as opposed to RBAC where you manage it through API.

2022-03-21 06:45 UTC, slashben commented on user-stories/configuration-best-practices.md
> +API server supports multiple client authentication technologies. These technologies answer different authentication needs and therefore there is not a single choice which can be considered a “best pr
I am fixing these sentences

2022-03-21 06:46 UTC, slashben commented
> 1. This is a best practice, not a user story
> 2. I don't think it's necessary for approval, but if we have some references as to why these are the best practices we choose, that would help
> 3. We should check our template.  The text is fine but the template has additional sections to fill in.

I will incorporate your comments and fixes then I will move it to the right place

2022-03-21 06:52 UTC, slashben commented on user-stories/configuration-best-practices.md
> +Different authentication methods support this functionality at different levels. Static token authentication requires restarts to the API server every time a token is revoked. Client certificate auth
Well, it is under the section "API server client authentication"

2022-03-21 13:53 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +* Attribute-Based Access Control (ABAC) mode allows you to configure policies per user. The configuration is done using local files of the API server. This means that in order to change these policie
Whether the ABAC configuration uses local files or non-local files is an implementation detail. Are there specific access rights needed for these configuration files?

2022-03-21 14:47 UTC, slashben commented on user-stories/configuration-best-practices.md
> +* Attribute-Based Access Control (ABAC) mode allows you to configure policies per user. The configuration is done using local files of the API server. This means that in order to change these policie
You need access rights at the file system level, but this was not my point. I meant that ABAC policies cannot be managed via API

2022-03-21 15:22 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +* Attribute-Based Access Control (ABAC) mode allows you to configure policies per user. The configuration is done using local files of the API server. This means that in order to change these policie
@slashben Thanks -- then please state that. For example,
Attribute-Based Access Control (ABAC) allows you to configure fine-grained access control policies per user, environment or resource attributes. The ABAC policies are specified in files; can't be managed using APIs. This means that in order to change these policies, the operator needs to be able to access these files.

2022-03-21 16:22 UTC, taylor commented on user-stories/configuration-best-practices.md
> +Allowing anonymous (unauthenticated users) is a bad practice in any production environment. Make sure `--anonymous-auth` is set to false in the API server configuration.
@iawells

2022-03-21 16:23 UTC, taylor commented on user-stories/configuration-best-practices.md
> +An operator must be able to manage authentication credentials and be able to revoke or rotate them. This is a must since different human errors can lead to leaks or theft, or simply access needs to b
@iawells can you clarify? Do you have a suggested change?

2022-03-21 16:42 UTC, electrocucaracha commented
@slashben can you also include the following words in the [wordlist](https://github.com/cncf/cnf-wg/blob/main/.github/.wordlist.txt) file?

```text
ABAC
AlwaysAllow
Kubelets
OpenID
RBAC
RoleBinding
Webhook
auth
webhook
cgroups
```

I usually keep them in alphabetical order? `sort -o .github/.wordlist.txt .github/.wordlist.txt`

2022-03-21 17:37 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +An operator must be able to manage authentication credentials and be able to revoke or rotate them. This is a must since different human errors can lead to leaks or theft, or simply access needs to b
This statement is about revoking and rotating credentials -- both capabilities are needed and so "or" should be replaced by "and". Secondly, the statement after "since" is not really a justification for the need to rotate and revoke credentials; human errors can occur even if the best practices for revocation and rotation of credentials are followed.
```suggestion
An operator must be able to manage authentication credentials and be able to revoke and rotate them. This is a must best security practice. Rotation reduces the risk of misuse of long unchanged credentials (become widely available) while revocation of credentials needs to be performed for users who no longer need them,
```

2022-03-21 17:56 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +Kubernetes API server must be configured to reject requests from unauthenticated/anonymous sources; the default configuration allows such requests. Only authenticated users should be able to make req
minor typo
```suggestion
The Kubernetes API server must be configured to reject requests from unauthenticated/anonymous sources; the default configuration allows such requests. Only authenticated users should be able to make requests to the API server. Set `--anonymous-auth` to `false`.
```

2022-03-21 18:01 UTC, pgoyal01 commented on user-stories/configuration-best-practices.md
> +Different authentication methods support this functionality at different levels. Static token authentication requires restarts to the API server every time a token is revoked. Client certificate auth
@slashben Sorry my mistake -- didn't see the levels. Thanks.

2022-03-28 14:58 UTC, jeffsaelens reviewed
I think this is a really good start. I'll need to review it once or twice more before adding some more thoughts. At a high level though I'd like to discuss on the Monday call about how we make this slightly more CSP and/or provider specific.

2022-03-28 16:16 UTC, jeffsaelens approved these changes
I'm updating my review to approve. I think its in a good starting spot and mergeable. Additionally, I think from there we provide additional context on how these practices are specifically relevant to CSPs, CNF operators and CNF developers and add section on K8s networking security as it impacts our use cases quite a bit.

2022-05-02 16:20 UTC, taylor requested changes
Rename file to: api-server-configuration-best-practices.md
Fix PR check failures (eg. linting)

2022-05-03 20:10 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +* AlwaysAllow allows all requests to be accepted (practically bypass access control)
typo - missing "."
```suggestion
* AlwaysAllow allows all requests to be accepted (practically bypass access control).
```

2022-05-03 20:11 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +The recommended way is to use “Role-based access control” since it gives a rich and manageable way to define access control in Kubernetes. Beyond the security perspective, this also makes the cluster
Should this be a separate bullet by itself -- independent of the "AlwaysAllow" bullet.

2022-05-03 20:14 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +Private key (client certificate authentication)
```suggestion
* Private key (client certificate authentication)
```

2022-05-03 20:14 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +Tokens
```suggestion
* Tokens 
```

2022-05-03 20:15 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +Passwords
```suggestion
* Passwords
```

2022-05-03 20:16 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +Revocation and rotation of authentication credentials
Is this supposed to be a sub-section or some dort of heading? As of now, it is part of a paragrapgh.

2022-05-03 20:19 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +An operator must be able to manage authentication credentials and be able to revoke and rotate them. This is a must best security practice. Rotation reduces the risk of misuse of long unchanged crede
minor typo's
```suggestion
An operator must be able to manage authentication credentials and be able to revoke and rotate them. This is a must best security practice. Rotation reduces the risk of misuse of long unchanged credentials (become widely available),  while revocation of credentials needs to be performed for users who no longer need them.
```

2022-05-03 20:23 UTC, pgoyal01 commented on cbpps/0003-api-server-configuration.md
> +It is very important for the operator to prepare the system with this requirement in mind and prepare for these.
with what requirement?

There is no recommended best practice here? Best practice for revocation of credentials within x hours after <specify even>. Best practice for rotation within z days.

2022-05-03 20:40 UTC, tomkivlin reviewed
couple of minor edits suggested and some duplicate content

2022-05-03 20:40 UTC, tomkivlin commented on cbpps/0003-api-server-configuration.md
> +This is a bad practice and only authenticated users should be able to make requests to the API server. Set `--anonymous-auth` to `false`.
Seems like a duplicate / different version of the above line?
```suggestion

```

2022-05-03 20:40 UTC, tomkivlin commented on cbpps/0003-api-server-configuration.md
> +Allowing anonymous (unauthenticated users) is a bad practice in any production environment. Make sure `--anonymous-auth` is set to false in the API server configuration.
This seems like a duplicate of L3-4 above:

> ## Disabling anonymous requests 
> The Kubernetes API server must be configured to reject requests from unauthenticated/anonymous sources; the default configuration allows such requests. Only authenticated users should be able to make requests to the API server. Set `--anonymous-auth` to `false`.

2022-05-03 20:40 UTC, tomkivlin commented on cbpps/0003-api-server-configuration.md
> +Revocation and rotation of authentication credentials
I think this makes more sense as a header?

```suggestion

### Revocation and rotation of authentication credentials
```

2022-05-08 13:00 UTC, slashben commented on cbpps/0003-api-server-configuration.md
> +The recommended way is to use “Role-based access control” since it gives a rich and manageable way to define access control in Kubernetes. Beyond the security perspective, this also makes the cluster
I have separated it

2022-05-08 14:15 UTC, slashben commented on cbpps/0003-api-server-configuration.md
> +It is very important for the operator to prepare the system with this requirement in mind and prepare for these.
I am rephrasing the whole paragraph, after all the changes it makes no sense

2022-05-08 14:15 UTC, slashben commented on cbpps/0003-api-server-configuration.md
> +Revocation and rotation of authentication credentials
Fixing it

2022-05-09 06:50 UTC, CsatariGergely requested changes
I think this is irrelevant in the CNF WG as "The focus of the CNF WG is to define the process around evaluating the cloud nativeness of networking applications, aka CNFs" and not the platform itself. 
On the other side this would be very relevant content to Anuket RA2 :)

2022-05-09 06:53 UTC, tomkivlin commented
> I think this is irrelevant in the CNF WG as "The focus of the CNF WG is to define the process around evaluating the cloud nativeness of networking applications, aka CNFs" and not the platform itself. On the other side this would be very relevant content to Anuket RA2 :)

Just on the security part I noticed this the other day (shared in Slack already), which seems to cover the security parts of this doc, and I imagine will be useful for Anuket too @CsatariGergely. https://docs.google.com/spreadsheets/d/1H9J0phBbg47fsyiLNG1-5NXms46KKxTH9ZjcU07no6A/edit?usp=sharing

2022-05-09 14:53 UTC, electrocucaracha reviewed
Linting issues

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +# Kubernetes API server security best practices!
```suggestion
# Kubernetes API server security best practices
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +The Kubernetes API server must be configured to reject requests from unauthenticated/anonymous sources; the default configuration allows such requests. Only authenticated users should be able to make
```suggestion
## Disabling anonymous requests

The Kubernetes API server must be configured to reject requests from unauthenticated/anonymous sources; the default configuration allows such requests. Only authenticated users should be able to make requests to the API server. Set `--anonymous-auth` to `false`.
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +API server audit logging is the functionality that enables operators to keep a record of requests to the cluster. It records the requests together with the initiator identity, therefore, enabling sec
```suggestion
## Enabling audit logging

API server audit logging is the functionality that enables operators to keep a record of requests to the cluster. It records the requests together with the initiator identity, therefore, enabling security teams to track events happening in the system.
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +* Attribute-Based Access Control (ABAC) allows you to configure fine-grained access control policies per user, environment or resource attributes. The ABAC policies are specified in files; can't be m
```suggestion
## API authorization configuration

Kubernetes API server supports multiple authorization plug-ins:

* Attribute-Based Access Control (ABAC) allows you to configure fine-grained access control policies per user, environment or resource attributes. The ABAC policies are specified in files; can't be managed using APIs. This means that in order to change these policies, the operator needs to be able to access these files.
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +Kubernetes role based access control has its limitations. For example, if an entity has rights to create PODs it eventually gets full control over nodes running the cluster. This happens due to the f
```suggestion
## Extending API access control limits with admission controllers

Kubernetes role based access control has its limitations. For example, if an entity has rights to create PODs it eventually gets full control over nodes running the cluster. This happens due to the fact that RBAC does not differentiate between a common POD and a privileged POD which has direct access to the host resources.
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +API server supports multiple client authentication technologies. These technologies answer different authentication needs. There is not a single choice that can be considered a “best practice”. Howev
```suggestion
## API server client authentication

API server supports multiple client authentication technologies. These technologies answer different authentication needs. There is not a single choice that can be considered a “best practice”. However, there are best practices that can be applied to multiple authentication technologies. These settings are paramount to the security of the API server and to the cluster in general.
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +* Tokens
```suggestion
### Authentication credentials confidentiality

All authentication methods require some kind of client credentials to authenticate against. Known credential are:

* Private key (client certificate authentication)
* Tokens
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +An operator must be able to manage authentication credentials and be able to revoke and rotate them. This is a must best security practice. Rotation reduces the risk of misuse of long unchanged crede
```suggestion
### Revocation and rotation of authentication credentials

An operator must be able to manage authentication credentials and be able to revoke and rotate them. This is a must best security practice. Rotation reduces the risk of misuse of long unchanged credentials (become widely available),  while revocation of credentials needs to be performed for users who no longer need them.
```

2022-05-09 14:53 UTC, electrocucaracha commented on cbpps/api-server-configuration-best-practices.md
> +
```suggestion
## References

* [kube-apiserver configuration reference](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)
* [securing Kubernetes system components](https://www.cncf.io/blog/2021/08/20/how-to-secure-your-kubernetes-control-plane-and-node-components/)
* [kube-apiserver access security blog 1](https://goteleport.com/blog/kubernetes-api-access-security/)
* [kube-apiserver access security blog 2](https://developer.okta.com/blog/2021/12/02/k8s-security-best-practices)
```

2022-05-09 16:15 UTC, electrocucaracha approved these changes

2022-05-09 16:15 UTC, taylor approved these changes
lgtm

2022-05-09 16:15 UTC, Smitholi67 approved these changes
/lgtm

2022-05-09 16:17 UTC, taylor commented
+1 from @ildikov on cnf wg call

2022-05-09 16:17 UTC, ildikov approved these changes

2022-05-09 16:19 UTC, merged