Create best_practice.yaml - issue template
lfn-cnti/bestpractices pull request #245
Opened 2022-12-21 08:21 UTC by tomkivlin

Signed-off-by: Tom Kivlin <52716470+tomkivlin@users.noreply.github.com>

Created in parallel to a google doc version, so we can see which works best: https://docs.google.com/document/d/1FbEeaF9ztJecWaVekQ4pm2JvkJLOyoI5nzevGXcD9sE/edit#

2022-12-21 22:06 UTC, lixuna requested changes

2022-12-21 22:06 UTC, lixuna commented on .github/ISSUE_TEMPLATE/best_practice.yaml
> +      placeholder: A summary of the best practice - couple of sentances.
```suggestion
      placeholder: A summary of the best practice - couple of sentences.
```

2023-01-09 16:14 UTC, electrocucaracha approved these changes

2023-01-23 16:32 UTC, taylor approved these changes
lgtm

2023-01-23 16:32 UTC, merged