Create 0005-single-concern-per-container.md
lfn-cnti/bestpractices pull request #267
Opened 2023-09-07 22:11 UTC by taylor

Adding the initial version of best practice recommending using a single concern (or single process type) per container

A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per container. The process(es) in the container should not spawn other process types (e.g. executables) as a way to contribute to the workload but rather should interact with other processes through a microservice API.

Co-authored with: @Smitholi67 and @electrocucaracha

2023-09-11 08:34 UTC, tomkivlin reviewed
Some minor readability / understanding comments.

2023-09-11 08:34 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +Ideally in a container the process 1 (init process) should be the single application running in the container. When multiple processes are started it is recommended to use a non-home-grown supervisor
Perhaps add some of the additional context that was provided in the discussion, e.g.

```suggestion
Ideally in a container the process 1 (init process) should be the single application running in the container, as the container runtime monitors the PID 1 application process and uses its signals to report events, knowing when a container has stopped. When multiple processes are started it is recommended to use a non-home-grown supervisor such as http://supervisord.org/.  See discussion here https://github.com/cncf/cnf-wg/discussions/264
```

2023-09-11 08:34 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +    - CNFs with multi-concerned containers have a larger surface area for security attacks and production bugs
Should we add a "may" here, as it's not a given?

```suggestion
    - CNFs with multi-concerned containers may have a larger surface area for security attacks and production bugs
```

2023-09-11 08:34 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Reduced visibility of communication and activity of services in the multi-concerned container
Suggest adding a "because" statement to aid understanding, e.g.

```suggestion
    - Reduced visibility of communication and activity of services in the multi-concerned container, as the container runtime will only be monitoring the init process within the container for signals (unless you're using a custom supervisor)
```

2023-09-11 08:34 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Security vulnerabilities in one process type effect all other processes in the same container
```suggestion
    - Security vulnerabilities in one process type are likely to effect all other processes in the same container
```

2023-09-11 08:34 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Resource utilization is less efficient in multi-concerned containers, which require allocation for all components rather than individual microservices requirements.
This might be contentious (see https://github.com/cncf/cnf-wg/issues/242#issuecomment-1363755449).  I think we should soften the statement a little, e.g.

```suggestion
    - Resource utilization is likely to be less efficient in multi-concerned containers, as the container runtime will look to allocation infrastructure resources for all components rather than individual microservices requirements.
```

2023-09-11 08:34 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +An SMF with different services providing the communication between AMF, UPF, PCF and other services in an environment with many new sessions being initiated sessions and ending during peak times may
This is a long sentence and I'm not sure it reads right for me. Maybe the following?

```suggestion
An SMF with different services providing the communication between AMF, UPF, PCF and other services in an environment where many new sessions are initiated and end during peak times. This may require scaling of the service responsible for communication with the AMF and UPF faster than the service communicating with the PCF. If the services are split into their own containers they can be scaled independently.  
```

2023-09-11 15:41 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Resource utilization is less efficient in multi-concerned containers, which require allocation for all components rather than individual microservices requirements.
No objections on cnf wg call.  accepting

2023-09-11 15:44 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - CNFs with multi-concerned containers have a larger surface area for security attacks and production bugs
@tomkivlin by definition two process types will increase the surface area for attacks and bugs vs a single process type in a container.

2023-09-11 15:45 UTC, nickolaev commented on doc/cbpps/0005-single-concern-per-container.md
> +    - A high degree of test coverage with a complex and tightly coupled CNF is difficult to achieve
Enables "polyglot" designs where e.g. the fronted of a service can be written in NodeJS, while your backend is in Erlang!

2023-09-11 15:47 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Security vulnerabilities in one process type effect all other processes in the same container
```suggestion
    - Security vulnerabilities in one process type may effect all other processes in the same container
```

2023-09-11 15:47 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Security vulnerabilities in one process type effect all other processes in the same container
@tomkivlin I think this should be "may effect" to make it lighter

2023-09-11 15:50 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Security vulnerabilities in one process type effect all other processes in the same container
```suggestion
    - Security vulnerabilities in one process type affect all other processes in the same container
```

2023-09-11 15:51 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Reduced visibility of communication and activity of services in the multi-concerned container
@tomkivlin, @electrocucaracha and I think the 
> (unless you're using a custom supervisor)
is not needed. The custom supervisor would still limit general observability as well and may require custom logging and service exposure...  If we have it please add to the definitions section for the custom supervisor.

2023-09-11 15:53 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +An SMF with different services providing the communication between AMF, UPF, PCF and other services in an environment with many new sessions being initiated sessions and ending during peak times may
Accepted during cnf wg call

2023-09-11 15:55 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +Ideally in a container the process 1 (init process) should be the single application running in the container. When multiple processes are started it is recommended to use a non-home-grown supervisor
Accepted during cnf wg call?

2023-09-11 15:57 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - A high degree of test coverage with a complex and tightly coupled CNF is difficult to achieve
@nickolaev please do a suggest edit, this is a good one.

2023-09-11 16:06 UTC, nickolaev commented on doc/cbpps/0005-single-concern-per-container.md
> +
```suggestion
    - Enable "polyglot" software designs, where the decoupled entities are developed in entirely different frameworks and even computer languages
```

2023-09-11 16:17 UTC, nickolaev commented on doc/cbpps/0005-single-concern-per-container.md
> +
```suggestion
Depending on the specifics of the implemented functionality, the resulting split may have requirements towards the locality of the resulting multiple containers. It may require certain functions to be deployed on the same worker node or allow for distributing them amongst different worker nodes. The cloud-native principles, and the need for a horizontal scaling does imply the latter, i.e. no locality restrictions. However, due to the specifics of the Telco workloads, such limitations might be necessary for the operation of the particular functionality.
In some cases, the workload distribution can span multiple data-centers and geographic locations. The edge deployments are exemplifying such application designs.

```

2023-09-11 16:28 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +
agreed, lgtm

2023-09-11 16:30 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +
lgtm for notes section.  

@nickolaev this topic would be interesting to explore to see how to give recommendations for the workloads that should allow running on multiple nodes and the ones that can not or are more difficult to do so.  For the ones that can not be split we should look at alternative best practices to help them

2023-09-12 08:17 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Reduced visibility of communication and activity of services in the multi-concerned container
@taylor ok, understood. I've updated the suggestion accordingly.

2023-09-12 08:17 UTC, tomkivlin commented on doc/cbpps/0005-single-concern-per-container.md
> +    - CNFs with multi-concerned containers have a larger surface area for security attacks and production bugs
OK, happy to withdraw this one.

2023-09-12 08:18 UTC, tomkivlin approved these changes
lgtm once @nickolaev's changes are incorporated.

2023-09-12 19:29 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Reduced visibility of communication and activity of services in the multi-concerned container
lgtm

2023-09-12 21:09 UTC, nickolaev approved these changes

2023-09-13 05:39 UTC, CsatariGergely commented
I think this is not a best practice for CNF-s. Restricting to single concern or process type per container results in too many API calls in the architecture what gives a too big overhead to the latency sensitive CNF-s.

2023-09-13 05:51 UTC, CsatariGergely requested changes

2023-09-13 05:51 UTC, CsatariGergely commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per contain
I would not bound to this to the process structure. It is more important to group the processes of the same functionality to a container, than the process structure. 
Using the process type results in too many unnecessary containers what creates unnecessary overhead and stresses the limits of container orchestration in stead of benefiting from the Linux kernel process scheduling capabilities.

2023-09-13 05:51 UTC, CsatariGergely commented on doc/cbpps/0005-single-concern-per-container.md
> +    - If you have more than one process type in a container, you will have to manage the lifecycle of the secondary concerns within the container, which effectively means creating an orchestrator wit
this is not entirely true. Processes are well managed by the Linus kernel, there is no need for a separate orchestrator even if there are multiple process types in a container.

2023-09-13 05:51 UTC, CsatariGergely commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Response time of multi-concerned containers is increased as scaling is required for the combined services rather than the individual services needing scaling.
On the other hand there is an overhead of the separation of processes to containers.

2023-09-13 14:55 UTC, jeffsaelens requested changes
I think this is an excellent read. I put in a few thoughts but overall I think that its in a really good place.

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per contain
This is slightly subjective. What constitutes "too many" containers? There is definitely a breaking point where the burden of the platform overhead outweighs the advantages gained from the platform itself, but how do we know the default in this scenario will be that we have too many containers? The opposite POV is that we have "too few containers" where big bloated VM like containers are being pushed across the network and when it goes down the failure domain is increased. 

I think your concern is valid, but I think the notion of responsibly thinking about what processes you map to a container and sticking to the UNIX principles here are still valid. There is a happy medium somewhere in here, and striving towards a best practice isn't the same as being beholden to an ironclad rule.

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +_“It’s best practice to separate areas of concern by using one service per container. That service may fork into multiple processes (for example, the Apache web server starts multiple worker processe
```suggestion
_“It’s a best practice to separate areas of concern by implementing one service per container. That service may fork into multiple processes (I.E. an Apache web server starts multiple worker processes). It is acceptable to have multiple processes running in a container; however, to get the maximum benefit out of a container runtime environment, avoid one container being responsible for multiple aspects of your overall application.”_
```

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - If you have more than one process type in a container, you will have to manage the lifecycle of the secondary concerns within the container, which effectively means creating an orchestrator wit
Where should we define separation of concerns in your opinion? The kernel is indeed a work horse but when its stated there is no need for separate orchestration, wouldn't we at that point just run bare metal implementations leveraging packages and package managers?

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Resource utilization is likely to be less efficient in multi-concerned containers, as the container runtime will look to allocation infrastructure resources for all components rather than indiv
```suggestion
    - Resource utilization is likely to be less efficient in multi-concerned containers, as the container runtime will look to allocate infrastructure resources for all components rather than individual microservices requirements.
```

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - CNFs with multi-concerned containers have a larger surface area for security attacks and production bugs
```suggestion
    - CNFs with multi-concerned containers have a larger surface area for cyber-attacks and production bugs
```

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - CNFs with multi-concerned containers have a larger surface area for security attacks and production bugs
We might want to add some sub-bullets to this such as expanding on what the attack surface enables attackers to achieve. The ability to move laterally (especially if privilege is established)

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Increase the use of Kubernetes orchestration capabilities instead of using additional container orchestration solutions
I question this goal. Is our end state K8s adoption or better software practices? I'm tracking the CNCF is our backer here, but I hesitate to specifically state we are pushing a purely K8s centric approach vs just trying to optimize orchestration in a cloud native manner. What if the CNCF or another opensource group provides an outstanding K8s alternative sometime in the near future? 

I think this main goal should be more focused on simplifying (or making more consistent) the approach to orchestration via adopting the principle.

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +        - Make it easier to reason the best way to scale a CNF based on anticipated load by reducing the complexity of service concerns and allowing focus on each container (or Pods) anticipated need
I don't think PODs fits here. I think its another construct that allows us to more safely implement the best practice proposed here. I also think the notion of a pod "potentially" address some of @CsatariGergely 's concerns as it allows us to package multiple containers (E.G. processes in this case) together. 

That said, pods for the most part are a K8s resource which I hesitate to fully hitch my wagon to.

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +- Security
Increases confidentiality by creating clearly defined boundaries (defense in depth) and allows for "need to know" access to be employed via the interfaces you've previously called out. 
Increases integrity (this is covered by the points you have listed)
Increases availability (also by the points you you've laid out but I think we should tie this in).

I don't think we need to go nuts here, but tying this back to the CIA triad will earn us some browning points with the true security wonks I think.

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Simplifying troubleshooting and readability of log output. It is easier to reason about the log messages that come from one concern or process type than log messages that are interleaved with o
```suggestion
    - Simplifying troubleshooting and readability of log output. It is easier to consume log messages and reason about their output when they come from one concern or process type as opposed to when they are interweaved with other concerns. This is even more true in a container that prints all log messages to standard out, such as described in the 12-factor cloud native app.
```

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF with multiple concerns should split services (or process types) for each of its concerns into separate containers. Service dependencies should be handled between containers through well-defined
Should this really be phrased around course/fine grain packaging with containers given as an example? I think this principle applies to VMs and BM workloads as well. We don't shove 5 mission critical monolith applications onto a single server these days because we know bad things happen when that server goes down or gets hacked.

2023-09-13 14:55 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +All pod types should implement this best practice.
confused on what we mean by pod type here. This was mostly container focused and now we are saying the implementation happens at the pod level? (could be I just lack context here)

2023-09-13 15:46 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per contain
@CsatariGergely the main intent is **single concern** per container and process type happens to often align with concerns. See references for reasons for this (which is also a principle -- single concern principle) such as Docker on containers, Intel and Ericsson on flexible and programmable networks supporting automation.

The is a best practice suggested for *most* cases not a hard requirement for all cases. When there are specific cases where the benefits of having a multi-concerned container (with multiple process types) leveraging Linux kernel process scheduling outweigh splitting the concerns into multiple containers then simply do not follow this best practice.  Note why that *specific* case is not followed.

2023-09-13 16:03 UTC, electrocucaracha commented on doc/cbpps/0005-single-concern-per-container.md
> +_“It’s best practice to separate areas of concern by using one service per container. That service may fork into multiple processes (for example, the Apache web server starts multiple worker processe
@jeffsaelens this paragraph is a quote, which it was taken as it is. Even when your suggestion improves its readability, it breaks its traceability.

2023-09-13 16:06 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +_“It’s best practice to separate areas of concern by using one service per container. That service may fork into multiple processes (for example, the Apache web server starts multiple worker processe
@jeffsaelens this was a direct quote.  Should we fix the grammar?

2023-09-13 16:06 UTC, electrocucaracha commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Increase the use of Kubernetes orchestration capabilities instead of using additional container orchestration solutions
So, do you suggest removing the word `Kubernetes` from the paragraph or remove the goal entirely?
```suggestion
    - Increase the use of orchestration capabilities instead of using additional container orchestration solutions 
```

2023-09-13 16:10 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +_“It’s best practice to separate areas of concern by using one service per container. That service may fork into multiple processes (for example, the Apache web server starts multiple worker processe
If it's being leveraged as a quote then it should not be changed. I didn't see a citation though, hence the suggestion. I think we either paraphrase and clean it up, or reference who is being quoted.

2023-09-13 16:10 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - If you have more than one process type in a container, you will have to manage the lifecycle of the secondary concerns within the container, which effectively means creating an orchestrator wit
@CsatariGergely this is about dealing with processes dying and restarting, scaling the processes appropriately within the container, etc.

2023-09-13 16:13 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Response time of multi-concerned containers is increased as scaling is required for the combined services rather than the individual services needing scaling.
@CsatariGergely this can be a suggested addition (use the GitHub suggestion feature in the PR) to the Notes/Caveats section.  Something like:

> For some applications and use cases there may be an increased overhead as a result separation of processes into different containers

2023-09-13 16:16 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - CNFs with multi-concerned containers have a larger surface area for security attacks and production bugs
@jeffsaelens please change it to cyberattack without the hyphen.

2023-09-13 16:17 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Increase the use of Kubernetes orchestration capabilities instead of using additional container orchestration solutions
@jeffsaelens Maybe it should say leverage the platforms orchestration capabilities?

2023-09-13 16:19 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +        - Make it easier to reason the best way to scale a CNF based on anticipated load by reducing the complexity of service concerns and allowing focus on each container (or Pods) anticipated need
@jeffsaelens I think "(or Pods)" can be removed an the goal is still good enough for the intent of this best practice.  Please make a suggest edit.

2023-09-13 16:19 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +- Security
@jeffsaelens I agree.  Suggest edit?  :)

2023-09-13 16:23 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Increase the use of Kubernetes orchestration capabilities instead of using additional container orchestration solutions
```suggestion
    - Simplify and consolidate the use of orchestration capabilities instead of adding additional container orchestration solutions 
```

2023-09-13 16:24 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +All pod types should implement this best practice.
This is based on what we have used for other best practices.  Pod type was part of the context.  I like this definition

> Pod is a set of Linux namespaces, cgroups, and potentially other facets of isolation - the same things that isolate a [container](https://kubernetes.io/docs/concepts/containers/). 

from https://kubernetes.io/docs/concepts/workloads/pods/#what-is-a-pod

For some best practices we thought they should not apply to K8s core-system Pod types. 

In any case we could have other things here such as control and user plane applications if desired.

2023-09-13 16:46 UTC, jeffsaelens reviewed
I'll work on a security/triad edit here shortly.

2023-09-13 16:46 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Increase the use of Kubernetes orchestration capabilities instead of using additional container orchestration solutions
I think just dropping K8s from the first makes it mildly confusing. I don't know if the suggestion above is really it either, but I took a stab at it.

2023-09-13 16:46 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +        - Make it easier to reason the best way to scale a CNF based on anticipated load by reducing the complexity of service concerns and allowing focus on each container (or Pods) anticipated need
```suggestion
        - Make it easier to reason the best way to scale a CNF based on anticipated load by reducing the complexity of service concerns and allowing focus on each container's anticipated needs 
```

2023-09-13 16:46 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +_“It’s best practice to separate areas of concern by using one service per container. That service may fork into multiple processes (for example, the Apache web server starts multiple worker processe
ignore last, I'm looking at the chopped up reviewers view and missed the reference and formatting. When I looked at the finished view, its very obvious this is a quote. Disregard this.

2023-09-13 16:46 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +All pod types should implement this best practice.
If we stay K8s centric I think it makes sense. If we are more generic, I'm iffy.

2023-09-13 16:53 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per contain
Remember this is a *cloud native* best practice for applications.  This is not trying to be the best practice for all things.  It may not be a practice that fits every situation, but that does not change if it is a *cloud native* best practice or not.

2023-09-13 16:55 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +All pod types should implement this best practice.
These are currently in the vast majority of cases applied to K8s environments.  We can shift to something more generic later as needed. All of these practices may be modified as needed going forward.

2023-09-13 16:56 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +All pod types should implement this best practice.
```suggestion
All Kubernetes Pod types should implement this best practice.  This best practice applies to control and user plane applications.
```

2023-09-13 17:24 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Security vulnerabilities in one process type effect all other processes in the same container
```suggestion
    - Security vulnerabilities in one process type may affect all other processes in the same container
```

2023-09-13 17:29 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +All pod types should implement this best practice.
Suggested update added

2023-09-13 17:31 UTC, electrocucaracha commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per contain
Containers, among other things, provide isolation (namespaces) and resources control (cgroups). Having a group of different process in the same container provides the same limit resource, e.g. CPU time-share. A `sshd` process type may require much higher CPU share than the rest of processes. In the other hand, inter-containers communication can also be accomplished by using shared files on the disk.

2023-09-13 17:33 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - If you have more than one process type in a container, you will have to manage the lifecycle of the secondary concerns within the container, which effectively means creating an orchestrator wit
The [previous reminder](https://github.com/cncf/cnf-wg/pull/267#discussion_r1324803547), about this being a cloud native best practice, applies here as well.

2023-09-13 17:41 UTC, taylor commented
> I think this is not a best practice for CNF-s. Restricting to single concern or process type per container results in too many API calls in the architecture what gives a too big overhead to the latency sensitive CNF-s.

This applies to the majority of applications including networking-focused applications.  Specifically, it is a **cloud native** best practice for the majority of networking applications.

For latency-sensitive applications, specifically the individual services (and their processes) within the application that are latency sensitive, when this best practice's benefits are outweighed by the other practices meeting latency requirements an exception in following this best practice should be made for that specific application's services (and their processes).  

This information is a good candidate for the NOTES and caveats section.

2023-09-13 17:46 UTC, electrocucaracha commented on doc/cbpps/0005-single-concern-per-container.md
> +1. https://techcommunity.microsoft.com/t5/azure-for-operators-blog/what-is-the-5g-session-management-function-smf/ba-p/3693852
I found another interesting article from Mirantis
```suggestion
1. https://techcommunity.microsoft.com/t5/azure-for-operators-blog/what-is-the-5g-session-management-function-smf/ba-p/3693852
1. https://www.mirantis.com/blog/multi-container-pods-and-container-communication-in-kubernetes/
```

2023-09-13 18:23 UTC, jeffsaelens commented on doc/cbpps/0005-single-concern-per-container.md
> +- Security
I made a PR against this branch with an attempt.

2023-09-13 21:01 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +- Security
https://github.com/cncf/cnf-wg/pull/269

2023-09-13 21:42 UTC, Smitholi67 approved these changes
lgtm

2023-09-13 22:03 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +- Security
merged

2023-09-13 22:09 UTC, lixuna requested changes

2023-09-13 22:09 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Limit the number of process types and their dependencies such as additional binaries/libraries
```suggestion
    - Limits the number of process types and their dependencies such as additional binaries/libraries  
```

2023-09-13 22:09 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Prevent unnecessary access to data via shared filesystems
```suggestion
    - Prevents unnecessary access to data via shared filesystems
```

2023-09-13 22:09 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Implement finer grained attribute-based controls between processes and systems
```suggestion
    - Allows for finer grained attribute-based controls to be implemented between processes and systems
```

2023-09-13 22:09 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Protect containers from interfering with one another by leveraging the container namespace system and cgroup implementations
```suggestion
    - Protects containers from interfering with one another by leveraging the container namespace system and cgroup implementations
```

2023-09-13 22:09 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Remove the risk of multiple critical processes terminating simultaneously
```suggestion
    - Removes the risk of multiple critical processes terminating simultaneously
```

2023-09-13 22:09 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Define access methods via established interfaces
```suggestion
    - Defined access methods via established interfaces
```

2023-09-13 22:11 UTC, lixuna commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Define access methods via established interfaces
```suggestion
    - Defines access methods via established interfaces
```

2023-09-13 22:15 UTC, taylor commented on doc/cbpps/0005-single-concern-per-container.md
> +    - Define access methods via established interfaces
```suggestion
    - Defines access methods via established interfaces
```

2023-09-13 22:24 UTC, lixuna approved these changes
lgtm

2023-09-14 00:05 UTC, jeffsaelens approved these changes
Updates are solid. LGTM

2023-09-14 00:31 UTC, agentpoyo approved these changes
LGTM :+1:

2023-09-14 02:59 UTC, electrocucaracha approved these changes
/lgtm

2023-09-14 05:53 UTC, CsatariGergely commented on doc/cbpps/0005-single-concern-per-container.md
> +A CNF’s microservice(s) should follow the single concern principle. To help achieve this goal, a CNF’s microservice(s) should have only one process type (or set of parent/child processes) per contain
Thanks for the reactions. 
@jeffsaelens I agree that this is subjective and we need to find a medium. I think connecting directly to process types is a bit to rigid practice. I see now that this we corrected. 

@taylor Thanks for the updates. I think we should put more emphasis on having the same service or functionality in a container than process types.

2023-09-14 07:23 UTC, nickolaev approved these changes

2023-09-14 15:37 UTC, sparso approved these changes
LGTM

2023-09-14 20:12 UTC, taylor commented
Thanks for everyone's reviews, suggest edits, and comments.  There are no remaining items left and we have more than met the minimum approvals for merging so I will squash and merge.

2023-09-14 20:14 UTC, rich-l approved these changes

2023-09-14 20:20 UTC, merged

2023-09-14 21:19 UTC, ildikov approved these changes