Create first iteration of Accelerating Cloud Native in Telco whitepaper
lfn-cnti/bestpractices pull request #272
Opened 2023-11-03 18:43 UTC by taylor

The first iteration of the whitepaper "Accelerating Cloud Native in Telco" on the Challenges of Cloud Native Telco Transformation today and how to overcome them - A CSP perspective

Contributors and co-authors include:

* Bell Canada 
    * Daniel Bernier, Technical Director
    * Roger Lupien, Sr. Mgr - Enterprise Architecture, Cloud Transformation
* Charter Communications
    * Mohammad Zebetian, Head of Cloud, Network, Edge, and Infrastructure Architecture
* Deutsche Telekom Technik
    * Vuk Gojnic, Cloud Native Telco Platform Lead
    * Nathan Rader, VP Service and Capability Exposure
* DNA Oyj
    * Johanna Heinonen, Development Manager
* Orange
    * Philippe Ensarguet, VP of Software Engineering
    * Guillaume Nevicato, Network Anticipation & Research Manager
* Swisscom
    * Ashan Senevirathne, Product Owner Mobile Cloud Native Orchestration
    * Josua Hiller, Product Manager Mobile Data Services
* TELUS
    * Andrei Ivanov, Principal Technology Architect 
    * Sana Tariq, Ph.D - Principal Technology Architect | Cloud and Service Orchestration
* Vodafone
    * Tom Kivlin, Principal Cloud Architect
    * Riccardo Gasparetto Stori, Principal Cloud Architect

@vukg @tomkivlin

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
Remove "Support for SR-IOV and…"

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       user sessions without interruptions)
add full stop

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Upgrade procedures on CNF shall also follow rolling-upgrade principles and shall be done in-service
add full stop

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs should expose their state (e.g. health) in a cloud native way
add full stop

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. _The application should follow the Principle of Least Privilege_
remove _italic_ format

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. The application must be isolated with Namespaces and not use the default namespace
add full stop

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure)
add full stop

2023-11-03 19:35 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs use cloud native principles (e.g. Kubernetes capabilities) when implementing resilience architecture without
add full stop

2023-11-03 19:38 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
@ashanvbs you can use the suggest edit capability 
<img width="394" alt="image" src="https://github.com/cncf/cnf-wg/assets/26697/cbcd37fe-aa90-4486-a662-165ebabe5646">

2023-11-03 19:39 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
Also are we just missing text and need to add the rest @ashanvbs?

2023-11-03 19:39 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. _The application should follow the Principle of Least Privilege_
```suggestion
    1. The application should follow the Principle of Least Privilege
```
Removing italic at @ashanvbs suggestion

2023-11-03 19:40 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       user sessions without interruptions)
```suggestion
       user sessions without interruptions).
```

2023-11-03 19:40 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs should expose their state (e.g. health) in a cloud native way
```suggestion
    1. CNFs should expose their state (e.g. health) in a cloud native way.
```

2023-11-03 19:42 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       human-readable open formats
```suggestion
    1. RBAC definitions must declare the minimal set of rights needed for the application to function The application should not request open-ended / all rights in its RBAC definitions.
    1. Applications should not require privileges to run including privileged pods and cluster roles.
    1. Applications that require privileges must declare which components require privileges in both machine-readable and human-readable open formats.
```

full-stop (period)

2023-11-03 19:42 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. The application must be isolated with Namespaces and not use the default namespace
```suggestion
    1. The application must be isolated with Namespaces and not use the default namespace.
```

2023-11-03 19:42 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs use cloud native principles (e.g. Kubernetes capabilities) when implementing resilience architecture without
```suggestion
    1. CNFs use cloud native principles (e.g. Kubernetes capabilities) when implementing resilience architecture without.
```

2023-11-03 19:43 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure)
```suggestion
       fully focusing on 3GPP (e.g. CNFs do not rely solely on robust infrastructure).
    1. CNFs are resilient to network corruption / poor quality network connection (e.g. packet drops, high latency, etc.).
    1. CNFs are resilient to complete loss of network connection.
    1. CNFs are resilient to poor-quality storage connection (e.g. high latency, read/write performance degradation, etc.).
    1. CNFs are resilient to complete loss of storage connection.
    1. CNFs are resilient to storage disks being full.
    1. CNFs are resilient to CPU stresses.
    1. CNFs are resilient to Memory stresses.
    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
```

2023-11-03 19:46 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Upgrade procedures on CNF shall also follow rolling-upgrade principles and shall be done in-service
```suggestion
    1. Upgrade procedures on CNF shall also follow rolling-upgrade principles and shall be done in-service.
```

2023-11-03 19:59 UTC, ashanvbs commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
No its already covered

2023-11-03 20:00 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
So resolve this?

2023-11-03 20:45 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
```suggestion
       they are available. For example support for multiple CNIs vs a single CNI.
```

other example not complete. removed

2023-11-03 20:46 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       they are available. For example support for multiple CNIs vs a single CNI. Support for SR-IOV and…
@ashanvbs https://github.com/cncf/cnf-wg/pull/272/files#r1382126142

2023-11-03 21:01 UTC, Nery44 approved these changes

2023-11-03 21:35 UTC, ashanvbs approved these changes

2023-11-05 13:28 UTC, vukg approved these changes
I left one more significant and one costemic comment. However, all in all I approve the the draft.

2023-11-05 13:28 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   1. Each CNF shall be validated, including the implementation of any adaptations that may be required, within 3 months of
3 months might be too ambitious. I suggest to increase to 4 months, the same as K8s release cadence.

2023-11-05 13:28 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +* Deutsche Telekom Technik
Pls correct this section and replace it with:

Deutsche Telekom (DT)
    * Vuk Gojnic, Cloud Native Telco Platform Lead, DT Technik
    * Nathan Rader, VP Service and Capability Exposure, DTAG

2023-11-05 23:00 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   1. Each CNF shall be validated, including the implementation of any adaptations that may be required, within 3 months of
```suggestion
   1. Each CNF shall be validated, including the implementation of any adaptations that may be required, within 4 months of
```

@vukg @tomkivlin

2023-11-05 23:01 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +* Deutsche Telekom Technik
```suggestion
* Deutsche Telekom (DT)
```

2023-11-05 23:01 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +* Deutsche Telekom Technik
@vukg ☝🏻 👇🏻

2023-11-05 23:02 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    * Nathan Rader, VP Service and Capability Exposure
```suggestion
    * Vuk Gojnic, Cloud Native Telco Platform Lead, DT Technik
    * Nathan Rader, VP Service and Capability Exposure, DTAG
```

2023-11-06 07:57 UTC, vukg approved these changes

2023-11-06 12:46 UTC, tomkivlin commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   1. Each CNF shall be validated, including the implementation of any adaptations that may be required, within 3 months of
OK, make if 4.   I am concerned though, as I suspect many CNFs already do this.  It is the next phase of validation against e.g. Tanzu, OpenShift, etc. etc. etc. that takes the time that needs reducing.

2023-11-06 13:08 UTC, tomkivlin approved these changes

2023-11-06 15:15 UTC, jeffsaelens requested changes
Really solid document. The last thing I think is missing is an acknowledgement from the providers that they are going to provide a solid cloud environment to host in. The CSP's cloud native abstraction layer is mentioned multiple times as if its ubiquitous (the small disclaimers each CSP is different notwithstanding), but we all know that not all environments are created equal. 

If providers want CNF vendors to provide what's outlined in this doc, there has to be a meeting at the halfway point with an acknowledgement that they can produce a consistent hosting experience. The "Resilience" section covers some of this, but it mostly just says vendor's need to build an app for an imperfect world. While this is 100% true, there are limits to what is a reasonable expectation of resilience.

2023-11-06 15:15 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +The document presented here is a product of the initial joint work of several Communication Service Providers (CSPs) who are active in Cloud Native Computing Foundation (CNCF)’s Cloud Native Network
```suggestion
The document presented here is a product of the initial joint work of several Communication Service Providers (CSPs) who are active in Cloud Native Computing Foundation (CNCF)’s Cloud Native Network Function Working Group (CNF WG), NGMN Alliance, and projects like Linux Foundation (LF) Europe’s Sylva and Linus Foundation Networking (LFN) Anuket. It is a draft that has been published with the goal of inviting feedback from other CSPs and motivating discussion and improvements in the broader telecommunication industry. We are hoping that through public discourse we can make the document more complete, relevant, and ready for final release. If you would like to contribute to the discussion and document please feel free to open an issue or create a pull request.
```

2023-11-06 15:15 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +The document presented here is a product of the initial joint work of several Communication Service Providers (CSPs) who are active in Cloud Native Computing Foundation (CNCF)’s Cloud Native Network
CSP and CNCF are spelled out at least once before the doc swaps to the shortened version. We should do the same for LF and LFN the first time as well.

2023-11-06 15:15 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
There is no mention here of what it means to be the "Prime". I feel that if we are going to push vendors to do better, we need to also acknowledge that owning the overarching SLA to a heterogenous deployment is a daunting task. The notion of tiered SLAs is something that I've been noodling on. NEP likely has the SLA to the CSP. What type of SLAs are the platform providers providing the NEP? A shared stack is going to require some shared risk.

2023-11-06 15:15 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
I think there is some over correction here. Assuming "Pinning" is bad is a miss in my opinion. Physics still gets a vote in how electrons move about the motherboard. Instead of saying something like pinning is bad, I feel focusing on the 1+1 redundancy model mentioned and bad operational practices in general ("statically pinning" workloads for instance) is where the focus should be. Who cares if I pin to a NUMA zone if I can do it declaratively and the app allows for the scheduler to work its magic? App goes down, or the node is tainted, if it can dynamically look for the next 4 physical cores available in a single NUMA boundary and come back up without human intervention, has the app broke the principles?

2023-11-06 16:23 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +traditional tapping setup is not configurable or capable enough,it is practically impossible to create reasonable port mirroring
nit
```suggestion
traditional tapping setup is not configurable or capable enough, it is practically impossible to create reasonable port mirroring 
```

2023-11-06 16:28 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
Or maybe it has to give explanation why it's bad, like `Pinning is bad when your infrastructure doesn't have support for NUMA`

2023-11-06 18:40 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
An attempt to address this aspect is in requirement section 3, points ii & iii. Can you relate with this?

2023-11-06 18:49 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
I agree in principle with comment from @jeffsaelens. However the borderlines are thin here and is easy to tap into bad operational practices. The goal this is promoting is let the cloud be generic in first line and do not differentiate between the nodes, CPUs, cores etc for functioning. In the domain of performance fine-tuning we could open the room for  some optimization like NUMA etc.

2023-11-06 19:27 UTC, vukg commented
> consistent hosting experience

The common denominator for hosting experience are major upstream components, in first line Kubernetes and things around networking. The paper is calling for unifying around conformance and consistency with upstream (reference) to cover 90% of hosting experience and build the flexibility for local adaptation for remaining 10% instead of trying to converge on opinionated blueprints. We can remember lesons from VNFO failure.

2023-11-06 19:43 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
Even "cloud friendly" applications have an endless amount of documentation on performance tuning. A poorly deployed database, an unoptimized content delivery platform, etc... are examples of non-NF applications that also expect some level of infra tuning. Simply consuming more resources in the cloud as the answer to all bottlenecks is not a great path forward (or cost effective). One big difference though is that these examples typically can take advantage of what the cloud offers. Tuning doesn't suddenly block you from horizontally scaling, bursting capacity, etc... which is key.

I think we have to walk that fine line between generic infra and garbage infra. There are a lot of "premium" services in the hyperscalers for tweaking performance and ensuring a better outcome. We just don't balk as hard at those because the hyperscalers don't break their consumption model to enable said services. A lot of us have a ton of scar tissue from broken OpenStack and VMware environments that had so many knobs turned that we consistently engineered ourselves into corners. If we don't break the community's principles though, I don't think we should immediately dismiss implementations unless we've tested and documented the best practice against them.

2023-11-06 19:58 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
I agree with the points in those sections, but I don't think they address the concern above. Assuming we are talking the adaptations and validations sections, then I agree with notion of how CNFs are delivered, that the black box approach era is hopefully coming to an end, and that we should validate in customer environments. 

Most of my concern is the lack of concrete day-2 implications. LCM is touched on and well-articulated, but if we use the validation example (pre-validation vs validating on a customer prem), what assurances does the CNF provider (doesn't even have to be a vendor, could be the CDN software a different internal team provides) have that the lab, stage and prod environments have parody? This is not to say that I think the points aren't valid, they 100% are imho. I only think that that the cloud/devOps/SRE teams need to also provide assurances should the devs meet the demands laid out. How many internal teams claim they need to go to a hyperscaler because the NetOps environments don't provide what they need? 

Basicaly, if a dev provides an SLA, what assurances do they get in return should they move away from the blackbox approach?

2023-11-07 13:07 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
@vukg it's probably a miswording, but it's not a problem of "fine-tuning". I'm sure we all understand that a badly placed "data plane" workload (think far from its PCI NIC and/or allocated memory) can dramatically drop its throughput, introduce all kinds of latency and jitter issues and so on. As @jeffsaelens said above, we can not change physics to be cloud-native, but instead, we can expose the physical constraints in a cloud-native, decalrative way.

2023-11-07 13:15 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +1. **Validation.** CNFs shall be delivered with a series of automated tests that can be used to validate the CNF on the spot in
```suggestion
1. **Validation.** CNFs shall be delivered with a series of automated tests that can be used to validate the CNF operation on the spot in
```

2023-11-07 13:19 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       side.
```suggestion
       side.
    1. The validation tests  shall cover CNF basic functionality, lifecycle and disaster recovery
```

2023-11-07 14:17 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
To me, this is too broad term `mainstream available hardware`? 

- I am sure in a telco DC, one can find hardware that is not typically available in any "mainstream DC". Think of a Smart NIC or an FPGA card. 
- If we get down to the CPU - are we expecting every CNF to be equally performant on an AArch64 server?

2023-11-07 14:22 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       production.
This sounds good in theory, but I am not sure how it will work in practice. It is very often when different NIC vendors (or OEMs) are providing their firmware releases while using the same packet processing chip. So the only option that the CNF vendor has is to pin a particular SKU in their requirements.

2023-11-07 14:24 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +which are not covered by vanilla Kubernetes.
Kubernetes is getting secondary interfaces probably next-year. The problem here is the direct VF device attachment, which skips any management layer.

2023-11-07 14:30 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
Wow, these are quite challenging requirements, even for a simple web server. I agree that this could be the definition of the perfect CNF, but can we split these requirements in two: Perfect level and OK level. If I recall correctly, there was something similar with the CNF testing suite - different levels of certification.

2023-11-07 14:34 UTC, nickolaev reviewed
I agree with most of the statements here. However, at times it feels like we're painting here a perfect world, which in general is OK to strive for, but maybe we can be a bit more practical. I left my thoughts in the relevant sections.
Great initiative, hope it helps move the ecosystem forward!

2023-11-07 17:31 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +which are not covered by vanilla Kubernetes.
@nickolaev any suggest edits?

2023-11-07 17:33 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       side.
@nickolaev I like the idea of this one.. it might be too vague though.  Could it be expanded and each point be covered?

2023-11-07 17:35 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
@nickolaev have suggestions to find a compromise in wording? Something about being vendor neutral between options for the telco DC hardware needed? 

@vukg @pensarguet @tomkivlin

2023-11-07 17:39 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
@nickolaev at the moment you could think of this as the entire list... a test suite covering all items could break things into levels of importance/priority. A certification using the testing could have levels as well.

Maybe the wording needs to use "MUST, SHOULD, MAY".  @tomkivlin @Nery44 @pensarguet @vukg @electrocucaracha

2023-11-07 17:47 UTC, rgstori approved these changes

2023-11-07 19:21 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       production.
Do you refer here to HW SKU or SW SKU or both?

2023-11-07 19:23 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +which are not covered by vanilla Kubernetes.
that would be great, but realistically it will likely take 2 years or longer until it comes to Beta state usable in production. It is long period over which the requirement could become irrelevant as CNFs could regulate that on its level.

2023-11-07 19:24 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
it is actually referring more to ability of CNF to recover on its own after problematic condition occur instead of remaining broken.

2023-11-07 19:35 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
what about having another mutual acceptance process with clear conditions for validity of SLA?

2023-11-07 19:41 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
sure, we shall not single out pinning as bad practice per default. As long as it is possible to manage it in declarative way that relies on general capability of underlying cloud-native infra, instead on particular instance, it shall be ok.

2023-11-07 19:42 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       production.
I was thinking HW when I wrote it, but maybe SW makes sense too.

2023-11-07 20:11 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
I can propose to have a separate paragraph describing "Mainstream Telco Hardware". Let me share some thoughts:

First I think we should explicitly call x86-64/amd64 as a defacto standard in the DC server platforms. Any CPU from 2019 and newer should be supported.
Then we can pin it to a 2-socket, NUMA-enabled HW architecture.
Regarding NICs - to me, the golden standard here is the DPDK drivers list (https://doc.dpdk.org/guides/nics/). Any decent CNF should be able to run with any NIC that is based on these chips. Of course, those that are x86-64 compatible. Even if the CNF can take advantage of a chip-specific HW acceleration, it should be able to deliver at least 60% of its fine-tuned performance on any of the said NICs.
Regarding more specific HW accelerators - these should be an optional requirement. The CNF should provide a decent software implementation to replace them, which can deliver at least 25% of the HW accelerated performance.

2023-11-07 20:20 UTC, nickolaev commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +which are not covered by vanilla Kubernetes.
```suggestion
which are often directly assigned to the CNF, skipping the host kernel drivers. This is specifically true for user plane CNFs like a UPF, Firewall or Internet Gateway.
```

2023-11-07 20:22 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
I like it. It's basically providing an acknowledgement to CNF devs that the environments will meet certain parameters as well. A little give and take.

2023-11-07 20:31 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
I think this ties into the earlier comments around SLAs, Primes and the like. If the infra is providing a certain level of guarantee, then the CNFs should as well from a fault tolerance standpoint. 

Example, we talk about K8s being the defacto here, but we are sort of assuming operators have deployed it in a sane way. K8s CP is expected to handle a node failure, but that is on the pretense that someone has provided the nodes needed for a taint to take place and service migrated. If the infra is in fact meeting "infra level SLAs" though then it's also reasonable to expect for the CNF to have a solid level of fault tolerance. To support @vukg 's point, if a node fails, the CNF should be able to handle the pods being rescheduled and allow for services to be reestablished.

2023-11-07 21:49 UTC, pgoyal01 commented
@taylor Thanks for alerting me to the WP.

Kudos to the contributors.

There are a couple of typos, and I will make some minor language suggestions. May I suggest that all acronyms be defined when first used and for some claims, relevant source material be linked.

My main concern is that reference is made to "challenges and pain" but aren't listed. More importantly, CSPs may have predictable network function performance requirements, and that creates dependencies such as CPU Pinning, and NUMA Alignment.

Are CSPs willing to accept CNFs from different vendors collocated on the same bare metal nodes without the isolation provided by VMs? I believe that the complexity of validating CNFs from different vendors for such coexistence is quite hard.

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +The document presented here is a product of the initial joint work of several Communication Service Providers (CSPs) who are active in Cloud Native Computing Foundation (CNCF)’s Cloud Native Network
```suggestion
This document is a product of the initial joint work of several Communication Service Providers (CSPs) who are active in the Cloud Native Computing Foundation (CNCF)’s Cloud Native Network Function Working Group (CNF WG), NGMN Alliance, and projects like Linux Foundation (LF) Europe’s Sylva and Linux Foundation Networking (LFN) Anuket project. It is a draft that has been published with the goal of inviting feedback from other CSPs and motivating discussion and improvements from the broader telecommunication industry. We hope that through public discourse we can make the document more complete, relevant, and ready for final release. If you would like to contribute to the discussion and document, please feel free to open an issue or create a pull request.
```

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +commenced in many Communication Service Providers (CSPs). Practical challenges and pain points on this journey,
Can the list of the challenges and pain points be shared or referenced?

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
While CNF suppliers may not have been able to "comply with the cloud native and openness requirements of CSPs", the reason attributed, with conviction ("reason is"), to such non-compliance may not be valid.

- Has the WG or CSP's verified with the CNF vendors their reason for non-compliance? 
- Until very recently, did CSPs have well-defined and stated requirements? Consistent across the CSPs?

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNFs (see Annex 1 and Reference 5), that can be supported by changing existing commercial models that could greatly benefit CSPs and
"that can" and then "that could" -- this sentence can do with simplification

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
```suggestion
automation, and operationalizing work. There is a need to evolve network functions into cloud native architecture, largely based on 12-factors for 
```

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
Instead of in context what vendors must provide, it would be beneficial to have a well-defined list in its own section/sub-section.

```suggestion
and vendors alike to create a new win-win. Vendors must provide open APIs, clear documentation, and cloud native 
```

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architectures and implementations that empower CSPs with self-service capabilities in the cloud ecosystem. This will help drive
If "self-service capabilities" are a requirement then the required capabilities need to be specified? 
Is this only for "cloud ecosystem"?

2023-11-07 22:39 UTC, pgoyal01 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +agility and innovation, and reduce Opex costs within CSP. CNF vendors can monetize the value of openness to evolve business models
How do open APIs help drive "agility" or "reduce OPEX costs"? There are many reasons for high CSP Opex costs including the inability of CSPs to modify their operational processes and other things.

May I suggest, the WP doesn't need to delve into the CNF vendor business models.

2023-11-13 16:08 UTC, tomkivlin commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
> @nickolaev at the moment you could think of this as the entire list... a test suite covering all items could break things into levels of importance/priority. A certification using the testing could have levels as well.
> 
> Maybe the wording needs to use "MUST, SHOULD, MAY". @tomkivlin @Nery44 @pensarguet @vukg @electrocucaracha

I would read this list as an example, as you say even a "perfect" list.  As I added at the top of this section ([here](https://github.com/cncf/cnf-wg/blob/whitepaper-accelerating-cloud-native-in-telco/doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md?plain=1#L157-L159)), we need to work with established communities and publications to get them discussed and added, rather than starting Yet Another List.

2023-11-14 17:00 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
Do we need to add anything to this whitepaper about this mutual acceptance process?  If so can a suggest-edit be made? @vukg @jeffsaelens

2023-11-14 17:03 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +which are not covered by vanilla Kubernetes.
@pensarguet @vukg @ashanvbs 👆🏻

2023-11-14 17:05 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +commenced in many Communication Service Providers (CSPs). Practical challenges and pain points on this journey,
@vukg @tomkivlin @pensarguet @ashanvbs 👆🏻

2023-11-14 17:13 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
Hmm. "architecture" sounds strange to me in this sentence. Maybe something like:
> There is a need to evolve network functions to fully support and integrate into cloud native environments

@pgoyal01 @jeffsaelens @nickolaev

2023-11-14 17:17 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
@pgoyal01 I think you added an extra "and"

The "equilibrium" can be used but the phrasing needs updating. Maybe:
> ... that could greatly benefit CSPs and vendors alike to create a new win-win equilibrium.

@pensarguet @vukg

2023-11-14 17:20 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architectures and implementations that empower CSPs with self-service capabilities in the cloud ecosystem. This will help drive
@pgoyal01 I think this is intentionally left open. The vendors can create new self-service capabilities as offerings. The CSPs can request things they want.

Please keep in mind this whitepaper is a follow-up to the NGMN manifesto adding more details and steps, but it is not claiming to have the totality of all requirements from any given CSPs. 

In fact the idea, as far as I know, is that this is a base list which CSPs will each build from based on their own internal requirements.  We can of course expand on the list of items that the majority of CSPs agree are common.

2023-11-14 17:44 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +agility and innovation, and reduce Opex costs within CSP. CNF vendors can monetize the value of openness to evolve business models
@pgoyal01 this is mainly an acknowledgment that vendor's need a business model that can align and work with the CSP's cloud native requirements and path.  A few ideas were put forth, but they are not the focus of the WP of course.  

This whitepaper may not be the place to go into explanations for every claim, as it is primarily CSPs communicating their challenges and what *they want to see* going forward for the transformation. They have asked for open APIs. 

I think we can have an entire whitepaper on why open APIs can help drive "agility" or "reduce OPEX costs". 🤔 💭 

The short response from me on APIs is to start with the sentence they wrote which says APIs will help 
> empower CSPs with self-service capabilities in the cloud ecosystem.

This is just one example and others related items are in the document. self-service is about agility and faster response to changing needs.  Vendor-neutral interoperability to help with the large-scale integration needs of CSPs is another area.  Automation across all of the environments and components. Open APIs help with all of this. Open APIs are part of open standards (often the driver for those standards such as  [rfc9260 Stream Control Transmission Protocol (SCTP)](https://datatracker.ietf.org/doc/html/rfc9260) or the [Kubernetes APIs](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) which being open allows anyone to write extensions and integrate with K8s in a way that ensures the extension+integration should work with every K8s environment adhering to those open standards.

I want to point out that the open standards are driven and continue to stay relevant (and living) because of open  APIs supporting transparent testing and working implementations using those open APIs (platforms + applications).

2023-11-15 11:27 UTC, tomkivlin commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +commenced in many Communication Service Providers (CSPs). Practical challenges and pain points on this journey,
@pgoyal01 @taylor that's what this document (the "## Challenges in Cloud Native Telco Transformation Today" section) describes.

2023-11-15 11:30 UTC, tomkivlin commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
> I can propose to have a separate paragraph describing "Mainstream Telco Hardware". Let me share some thoughts:
> 
> First I think we should explicitly call x86-64/amd64 as a defacto standard in the DC server platforms. Any CPU from 2019 and newer should be supported. Then we can pin it to a 2-socket, NUMA-enabled HW architecture. Regarding NICs - to me, the golden standard here is the DPDK drivers list (https://doc.dpdk.org/guides/nics/). Any decent CNF should be able to run with any NIC that is based on these chips. Of course, those that are x86-64 compatible. Even if the CNF can take advantage of a chip-specific HW acceleration, it should be able to deliver at least 60% of its fine-tuned performance on any of the said NICs. Regarding more specific HW accelerators - these should be an optional requirement. The CNF should provide a decent software implementation to replace them, which can deliver at least 25% of the HW accelerated performance.

Agree re. the NICs. Disagree re. the 2-socket.  There are many benefits to single socket servers, in particular around not having to mess around with NUMA pinning etc.

2023-11-15 11:46 UTC, pensarguet approved these changes
ok for me

2023-11-16 09:42 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +which are not covered by vanilla Kubernetes.
fine by me!

2023-11-16 09:45 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
looks good!

2023-11-16 09:58 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
I am fine with that.

2023-11-16 10:02 UTC, vukg commented
All looks good to me with comments above. There are only few points left to be resolved and merged before final publishing.

2023-11-17 18:26 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
System is likely a more accurate word here.

2023-11-17 18:28 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
```suggestion
systems approach is revenue from professional service that allows them to create business models on CNF deployments,
```

2023-11-17 18:29 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
I think some of these other items need to be resolved first.

2023-11-18 00:24 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Microservices should be loosely coupled with NO tight dependency on each other, to ensure scalability and ease of deployment,
A little redundant
```suggestion
    1. Microservices should be loosely coupled (with NO tight dependency on each other) to ensure scalability and ease of deployment,
```

2023-11-18 00:26 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. All configurations shall be done via Configmaps and/or similar cloud native constructs (eg. Kubernetes Resource Models)
nit:
```suggestion
    1. All configurations shall be done via Configmaps and/or similar cloud native constructs (e.g. Kubernetes Resource Models) 
```

2023-11-18 00:30 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
What about to use `Commercial Off-The-Shelf (COTS)` term instead of `Mainstream`?

2023-11-18 00:33 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. When performance is a requirement, the application should utilize open standards for adapters where possible at all levels
I'd add a request for defining `limits` and `request` values on their Pod definitions

2023-11-18 00:35 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1.  CNFs can share databases, load balancers, business logic, and common services and become fully disaggregated.
nit:
```suggestion
    1. CNFs can share databases, load balancers, business logic, and common services and become fully disaggregated.
```

2023-11-18 00:49 UTC, electrocucaracha approved these changes

2023-11-20 16:22 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +commenced in many Communication Service Providers (CSPs). Practical challenges and pain points on this journey,
Resolving

2023-11-20 23:49 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
@sanatariq610 @pensarguet @vukg

2023-11-20 23:56 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
@jeffsaelens it seems like this phrasing is an area that can specify the need for the entire system to move towards cloud native
- CSP platform + environment + operational practices
- NF provider/integrator applications
- Hyperscaler offerings for telecom orgs

Not only do the NFs need to evolve to work in a cloud native system/architecture, but the system they run on will ned to evolve.  This is a collaboration between all parties to move things forward.

Thoughts on wording here taking that into context (which you were thinking should be addressed in the document)?

2023-11-23 06:49 UTC, nickolaev approved these changes

2023-11-23 19:23 UTC, sanatariq610 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
I suggest:  "Solution approach is revenue from professional services that allows them to create business models centered on CNF deployments,"  Refers to the problem as cultural, business, and technology-centric and a model around that has to change so its a new solution approach ...

2023-11-23 19:24 UTC, sanatariq610 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
Fine with suggested modification..

2023-11-23 19:25 UTC, sanatariq610 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
I am good with @pgoyal01 proposal " ... that could greatly benefit CSPs and vendors alike to create a new win-win equilibrium"

2023-11-23 19:26 UTC, sanatariq610 commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +agility and innovation, and reduce Opex costs within CSP. CNF vendors can monetize the value of openness to evolve business models
Agree with @pgoyal01

2023-11-24 17:42 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
I'm ok with the proposal from Sana

2023-11-24 17:43 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
ok for me as well

2023-11-24 17:47 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
I do agree with @vukg

2023-11-27 20:27 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
@taylor I feel like I opened up a can of worms when I didn't intend to. I think a simple line or two throughout the document stating that "CSPs are evolving their approach to infrastructure at both the organizational level and technical level to ensure resilient and consistent experiences when deploying cloud native applications". 

Basically, a slight nod to the fact that we learned our lessons during the OpenStack/LTE era and our asks for well designed software is justified given the paradigm shifts taking place on the operator side. I think getting someone like @vukg @tomkivlin or @pensarguet 's take here for the wording and placement in the doc would be more appropriate. They may collectively decide to veto the idea as well.

2023-11-27 22:01 UTC, jeffsaelens approved these changes

2023-11-29 15:51 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
@vukg mutual SLA?

2023-11-29 20:20 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
+1

2023-11-29 20:20 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
+1

2023-11-29 20:21 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
+1

2023-11-29 20:28 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
+1 for NIC, but for CPU I would set single socket x86/amd64 as golden standard

2023-11-30 19:33 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
The statements were from the CSP POV.  It's all been updated though. Review.  Resolving this one for now.

2023-11-30 19:34 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
@taylor  looks like there is agreement here. Commit and resolve?

2023-11-30 19:34 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNF suppliers have not been able to comply with the cloud native and openness requirements of CSPs and one reason for that closed
Resolving with updates based on our convo @jeffsaelens .  If you have further concerns please add a new comment with suggestions

2023-11-30 19:35 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
Resolving with updates based on our convo @jeffsaelens and the latest updates from @vukg.  If you have further concerns please add a new comment with suggestions

2023-11-30 19:35 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +advance for that peak load.
@vukg 's recent PR into this doc changes the language to leave more wiggle room. I'm good with this. @nickolaev can we resolve this comment?

2023-11-30 19:36 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Alternatively it shall equally support all the mainstream available hardware.
@electrocucaracha @nickolaev please check latest updates from @vukg.  If that does not resolve these items please make a suggest edit.

2023-11-30 19:36 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +       production.
@vukg @nickolaev did latest update cover these?

2023-11-30 19:37 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. When performance is a requirement, the application should utilize open standards for adapters where possible at all levels
@electrocucaracha suggest edit please.

2023-11-30 19:41 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
@nickolaev @vukg @jeffsaelens The latest updates covered some mutual accountability for the transformation.. which includes SLA stuff.. do we need any more changes here? If so can someone please provide a suggest edit.  Otherwise I want to resolve this.

2023-11-30 19:44 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
@vukg 's recent additions meet what I was after. Other than changing "are" to "should be" or "must be" I'm fine with things as they are. This is ultimately a list of what "ideal" looks like to a CSP, so I'm not sure watering it down gains us anything. 

The notion of the platform also providing guarantees I think makes it reasonable to expect things from the software in return.

2023-11-30 19:46 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
```suggestion
CNFs (see Annex 1 and Reference 5), that can be supported by changing existing commercial models that could greatly benefit CSPs and vendors alike to create a new win-win equilibrium. Vendors must provide open APIs, clear documentation, and cloud native 
```

2023-11-30 19:47 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
@sanatariq610 @pensarguet @vukg @jeffsaelens here is my suggested alternative (in the comments https://github.com/cncf/cnf-wg/pull/272/files#r1392952690)

2023-11-30 19:47 UTC, jeffsaelens commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
+1

2023-11-30 19:48 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +vendors alike to create a new equilibrium in win-win. Vendors must provide open APIs, clear documentation, and cloud native
@jeffsaelens the agreement is on the alternative I suggested. I have added a suggest-edit https://github.com/cncf/cnf-wg/pull/272/files#r1411186228

2023-11-30 19:54 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
```suggestion
architecture and solution approach is revenue from professional services that allows them to create business models centered on CNF deployments,,
```
Suggestion from @sanatariq610

2023-11-30 19:54 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
Suggest-edit created for @sanatariq610 https://github.com/cncf/cnf-wg/pull/272/files/14a5a779cb079e27ac5861e5d112a58e73202a08#r1411193399

2023-11-30 20:45 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. CNFs are resilient to the complete loss of underlying infrastructure resources (e.g. a node failure).
we can probably change a lot of the wording to be must, should, optional etc. let's do that in another round

2023-11-30 20:46 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNFs (see Annex 1 and Reference 5), that can be supported by changing existing commercial models that could greatly benefit CSPs and
Please provide a suggest edit of you have an idea for simplification. closing this for now.

2023-11-30 20:46 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CNFs (see Annex 1 and Reference 5), that can be supported by changing existing commercial models that could greatly benefit CSPs and
@pgoyal01

2023-11-30 20:59 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +automation, and operationalizing work. There is a need to evolve into cloud native architecture, largely based on 12-factors for
This has been reworded in latest update:
> This hesitance cannot override a CSP's need to evolve towards a cloud native architecture, largely based on 12-factors

the intention is to include all layers not just NFs (or networking applications).

2023-12-01 03:26 UTC, ildikov reviewed
The paper looks good overall, I added a few comments and suggestions in line.

Thanks,
Ildikó

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +doesn't readily support reconciliation and depends on orchestration entities operating externally to Kubernetes "out-of-band."
Will this paper be released in a Kubernetes context? Or will it also be distributed and intended to be consumed standalone?

In case of the latter, I think it would be beneficial to clarify at the beginning that this paper assume Kubernetes as the container orchestration system.

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +**Lifecycle.** Kubernetes occupies a central place in cloud native infrastructure by following the paradigm of ephemeral resources
```suggestion
**Lifecycle.** Kubernetes occupies a central place in the end-to-end infrastructure stack, while following the paradigm of ephemeral resources
```

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
In my opinion the term 'cloud native infrastructure' is confusing. I would just stick to saying 'cloud infrastructure', 'container orchestration system' or other more specific terms to describe which component of the stack the paper talks about..

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +on service quality, as small disruptions which are normal in cloud native infrastructures result in problems within the CNFs.
Same comment about 'cloud native infrastructure' as above,, although, this statement here is true for any kind of infra not just cloud, the question is how the disruptions are handled on the various layers.

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +**Resilience.** In contrast to traditional expectations within the telecommunications domain, one important property of the cloud
This section feels a little redundant to what's described in 'Architecture' above.

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   which is the upstream Kubernetes and components from the CNCF ecosystem.
```suggestion
   which is upstream Kubernetes and further components from the CNCF ecosystem.
```

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   the Kubernetes release.
```suggestion
   a new Kubernetes release.
```

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   the Kubernetes release.
This requirement is a little confusing to me. Does this mean that a CNF has to and can only be validated against Kubernetes release(s) that are no more than 4 months old?

I also wonder if this bullet point might go one step too far into the details for a whitepaper? As something as concrete as '4 months' might get updated in the future, which would create confusions if the whitepaper is not immediately updated.

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   vendor’s delivery team to adapt them to align the deployments to the local specifics of CSP (e.g. Policy, RBAC, Compatibility)
```suggestion
   vendor’s delivery teams to adapt them to align the deployments to the local specifics of CSP (e.g. Policy, RBAC, Compatibility)
```

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +1. **Adaptations.** CNF artifacts (e.g. YAML manifests, Helm charts, NFVO descriptors) shall become open for CSP’s DevOps or
Would it be better to say 'made available' as opposed to 'become open'? It reads confusing in the sense whether the expectation is to make these artifacts open source, or just accessible to the teams that will need them.

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. This validation shall count as only relevant one, preceding any pre-validation or lack of it.
This bullet point reads confusing to me. Does this mean that this 'validation' replaces the 'pre-validation', if it was performed at all?

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. Mainstream open source deployment tools from CNCF ecosystems, like FluxCD or ArgoCD, shall be supported per default.
```suggestion
    1. Mainstream open source deployment tools from the CNCF ecosystem, like FluxCD or ArgoCD, shall be supported per default.
```

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   declarative cloud native mechanisms like GitOps.
I think it would be useful to add references that describe what tools and mechanisms the paper is referring to here, for those who are not yet familiar.

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +1. **Lifecycle.** CNFs have to be constructed in a way to fully tolerates graceful cluster rolling upgrade procedures without
```suggestion
1. **Lifecycle.** CNFs have to be constructed in a way that fully tolerates graceful cluster rolling upgrade procedures without
```

2023-12-01 03:26 UTC, ildikov commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +These principles and requirements address the systemic challenges listed above. They are intended to serve as the guardrails
The way how this section is structured, it doesn't allow for separation between challenges, principles and requirements. I think it would be beneficial to separate those at one point, to make it clear what the principles are, how they address challenges, and what requirements need to be fulfilled for compliance.

2023-12-01 06:38 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
I'm not sure about this, Cloud Native infrastructure is about infrastructure implementing the cloud native principle. I think it's important to use the word to emphasize that it's not about cloud (i.e. VM-centric initial world). BTW, it's implicit in the principles you mention. Otherwise, it's perhaps I'm spending most of my time there, and I'm biased. At the end, we are talking about Cloud Native Network function...

2023-12-01 06:40 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +doesn't readily support reconciliation and depends on orchestration entities operating externally to Kubernetes "out-of-band."
Good point of clarification as I had also the question on my side. We have to be precise and stating K8S at the very beginning, even if it turns obvious by reading after.

2023-12-01 06:43 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +**Lifecycle.** Kubernetes occupies a central place in cloud native infrastructure by following the paradigm of ephemeral resources
We need to be consistent with what we will end up with based on the previous comment. I prefer to stick to cloud native as end to end is too generic here for me.

2023-12-01 06:44 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +on service quality, as small disruptions which are normal in cloud native infrastructures result in problems within the CNFs.
ok, but the title of the white paper is "Challenges of Cloud Native Telco Transformation today and how to overcome them"

2023-12-01 06:50 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   the Kubernetes release.
4 months if we are considering the rolling release of K8S seems to not be a bad timeframe according me. Anyway, whether it is 3 or 4 or 5 months, the level of automation and integration that is needed to perform what is waited should be exactly the same.

2023-12-01 16:38 UTC, vukg commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. This validation shall count as only relevant one, preceding any pre-validation or lack of it.
It means that if pre-validation that CNF Vendor does in its labs is good indication, but shall not be blocker for CNF release to be deployed in some environment that was not pre-validated. For example CNF vendor has pre-validated on OpenShift that uses K8S 1.26, while CSP has upstream K8S 1.27. The vendor shall not say "I have pre-validated in only on OpenShift with K8S 1.26 so I can not support that CNF on K8S 1.27". Instead, if the validation and e2e tests on CSP premisses are passed, CNF shall be automatically supported in that environment.

2023-12-01 17:41 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. When performance is a requirement, the application should utilize open standards for adapters where possible at all levels
```suggestion
    1. When performance is a requirement, the application should specify the resource `request` values and utilize open standards for adapters where possible at all levels
```

2023-12-01 18:15 UTC, electrocucaracha commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architectures and implementations that empower CSPs with self-service capabilities in the cloud ecosystem. In order for new model to work the vendors and CSPs must provide mutual SLAs: the CSP must g
nit
```suggestion
architectures and implementations that empower CSPs with self-service capabilities in the cloud ecosystem. In order for the new model to work, vendors and CSPs must provide mutual SLAs: the CSP must guarantee a certain level of quality at the platform layer, while CNF vendors need to guarantee that the application will perform on the platform with SLAs that meet defined KPIs. This will help drive 
```

2023-12-01 18:48 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +doesn't readily support reconciliation and depends on orchestration entities operating externally to Kubernetes "out-of-band."
@pensarguet @vukg can you make a suggest-edit for the introduction statements? 

I think cloud native principles can be applied to other orchestration systems (including VM systems), but the requirements list is focused on K8s so that should be pointed out.

2023-12-01 18:51 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +These principles and requirements address the systemic challenges listed above. They are intended to serve as the guardrails
@vukg I like the idea in general, but that seems like a major update.  Maybe that should happen in a v1.1 version of this whitepaper?  @pensarguet @tomkivlin @ashanvbs

2023-12-01 18:52 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +These principles and requirements address the systemic challenges listed above. They are intended to serve as the guardrails
@ildikov unless you want to provide a version in a pull request that does that separation?

2023-12-01 20:23 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +These principles and requirements address the systemic challenges listed above. They are intended to serve as the guardrails
I do agree with @taylor, it's too close to GA 1.0 for so big change that will request confirmations from all that already did the review. The material is here but need a reshuffling to answer this.

2023-12-01 21:26 UTC, nickolaev approved these changes

2023-12-02 18:13 UTC, pensarguet commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +doesn't readily support reconciliation and depends on orchestration entities operating externally to Kubernetes "out-of-band."
I suggest we could add a final sentence in the intro like this one : In this whitepaper, we are defining Kubernetes as the de-facto runtime environment for hosting the cloud native network functions (CNFs). 
@vukg @taylor @ildikov What's your thought ?

2023-12-04 17:48 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +doesn't readily support reconciliation and depends on orchestration entities operating externally to Kubernetes "out-of-band."
Added K8s info to address issue in latest merge

2023-12-04 17:51 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +**Lifecycle.** Kubernetes occupies a central place in cloud native infrastructure by following the paradigm of ephemeral resources
@vukg when addressing the term in the pre-validation this sentence should be consistent.

2023-12-04 17:52 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
@vukg see https://github.com/cncf/cnf-wg/pull/272/files#r1414271022 for a sentence that needs to be consistent with this pre-validation

2023-12-04 18:00 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +on service quality, as small disruptions which are normal in cloud native infrastructures result in problems within the CNFs.
@vukg review this for any updates with the term expansion/changes in the pre-validation

2023-12-04 18:16 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +**Resilience.** In contrast to traditional expectations within the telecommunications domain, one important property of the cloud
Architecture can be too broad. Maybe it all needs to be broken down into sections.  I'm resolving this until someone puts a suggestion forward.

2023-12-04 18:57 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
Reference https://www.linkedin.com/feed/update/urn:li:activity:7135612657306374144/

2023-12-04 19:10 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
> “Cloud native” is a loaded term. As much as it has been hijacked by marketing departments, it still can be meaningful for engineering and management. To us, it is the evolution of technology in the world where public cloud providers exist.
> Cloud native infrastructure is infrastructure that is hidden behind useful abstractions, controlled by APIs, managed by software, and has the purpose of running applications. Running infrastructure with these traits gives rise to a new pattern for managing that infrastructure in a scalable, efficient way.
> Abstractions are useful when they successfully hide complexity for their consumer. They can enable more complex uses of the technology, but they also limit how the technology is used. They apply to low-level technology, such as how TCP abstracts IP, or higher levels, such as how VMs abstract physical servers. Abstractions should always allow the consumer to “move up the stack” and not reimplement the lower layers.”

(2018) Cloud Native Infrastructure by Justin Garrison & Kris Nova - Chapter 1: What Is Cloud Native Infrastructure?

2023-12-04 19:12 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
> Is Kubernetes Cloud Native Infrastructure?
> Kubernetes is a framework that makes managing applications easier and promotes
> doing so in a cloud native way. However, you can also use Kubernetes in a very uncloud-native way.
> Kubernetes exposes extensions to build on top of its core functionality, but it is not
> the end goal for your infrastructure. Other projects (e.g., OpenShift) build on top of it
> to abstract away Kubernetes from the developer and applications.
> Platforms are where your applications should run. Cloud native infrastructure sup‐
> ports them but also encourages ways to run infrastructure.
> If your applications are dynamic but your infrastructure is static, you will soon reach
> an impasse that cannot be addressed with Kubernetes alone.
-  (2018) Cloud Native Infrastructure by Justin Garrison & Kris Nova -  Chapter 2: When to Adopt Cloud Native

2023-12-04 19:14 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
<img width="668" alt="image" src="https://github.com/cncf/cnf-wg/assets/26697/3776515d-7749-4b8a-93b6-17139dcf068a">
(2018) Cloud Native Infrastructure by Justin Garrison & Kris Nova

2023-12-04 19:22 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
Maybe we should add this somewhere:

> “Cloud native infrastructure is not a solution for every problem, and it is your respon‐
sibility to know if it is the right solution for your environment (see Chapter 2). How‐
ever, its success is evident in the companies that created the practices and the many
other companies that have adopted the tools that promote these patterns.”
- (2018) Cloud Native Infrastructure by Justin Garrison & Kris Nova - Chapter 1: What Is Cloud Native Infrastructure?

2023-12-04 19:39 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
Cloud-native infrastructure, and specifically infrastructure built using the K8s framework, is designed to promote managing applications in a cloud native way along with ways of running the infrastructure itself in a cloud native manner.  This is important because you are free to use Kubernetes (and other "cloud native" technologies) in a very uncloud-native way.

Our longer-term goal, underlying this whitepaper, is for all layers of the environment to encompass the cloud native principles from infrastructure allocation + management, through the application workloads.

2023-12-04 19:55 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
For the purpose of this whitepaper you can think about cloud native infrastruture as the layer that abstracts the infrastructure at as a service that hyperscalers provide or the similar layer for bare metal private clouds.  

A high-level and generalized list of the layers are: application (including workloads), cloud native infrastructure, infrastructure as a service, infrastructure resources including compute, storage, network. (just as seen in the diagram above)

2023-12-04 20:07 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +CSPs. This creates problems in the adoption of those CNFs as CSPs generally prefer to each have a unified cloud native infrastructure
@ildikov See Introduction where the definitions have been set for this whitepaper.  Her is a copy of the section as of today:

>  We also use the term cloud-native infrastructure in broader context for the infrastructure that abstracts Infrastructure-as-a-Service (IaaS) layer, that has Kubernetes in its core with useful API abstractions on top of it as as well as auxiliary systems all as a framework that makes managing applications easier and promotes doing so in a cloud native way. 
> This is important because you are free to use Kubernetes (and other "cloud native" technologies) in a very uncloud-native way. Our longer-term goal, underlying this whitepaper, is for all layers of the environment to encompass the cloud native principles from infrastructure allocation + management, through the application workloads. A more in-depth analysis of these terms can be found in the book "Cloud Native Infrastructure" by Justin Garrison and Chris Nova.

2023-12-04 20:08 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +on service quality, as small disruptions which are normal in cloud native infrastructures result in problems within the CNFs.
This is now addressed in the introduction: 

>  We also use the term cloud-native infrastructure in broader context for the infrastructure that abstracts Infrastructure-as-a-Service (IaaS) layer, that has Kubernetes in its core with useful API abstractions on top of it as as well as auxiliary systems all as a framework that makes managing applications easier and promotes doing so in a cloud native way. 
> This is important because you are free to use Kubernetes (and other "cloud native" technologies) in a very uncloud-native way. Our longer-term goal, underlying this whitepaper, is for all layers of the environment to encompass the cloud native principles from infrastructure allocation + management, through the application workloads. A more in-depth analysis of these terms can be found in the book "Cloud Native Infrastructure" by Justin Garrison and Chris Nova.

2023-12-04 20:24 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   declarative cloud native mechanisms like GitOps.
GitOps is not a single product, plugin, or platform. While the practices and patterns in GitOps existed before Cloud Native (and the term GitOps), they happen to be a great match for cloud native applications and infrastructure alike.

Here are some principles for GitOps (as define by the Open GitOps org - https://opengitops.dev/):
- Declarative - A [system](https://github.com/open-gitops/documents/blob/v1.0.0/GLOSSARY.md#software-system) managed by GitOps must have its desired state expressed [declaratively](https://github.com/open-gitops/documents/blob/v1.0.0/GLOSSARY.md#declarative-description).
- Versioned and Immutable - Desired state is [stored](https://github.com/open-gitops/documents/blob/v1.0.0/GLOSSARY.md#state-store) in a way that enforces immutability, versioning and retains a complete version history.
- Pulled Automatically - Software agents automatically pull the desired state declarations from the source.
Continuously Reconciled - Software agents [continuously](https://github.com/open-gitops/documents/blob/v1.0.0/GLOSSARY.md#continuous) observe actual system state and [attempt to apply](https://github.com/open-gitops/documents/blob/v1.0.0/GLOSSARY.md#reconciliation) the desired state.

Here are some GitOps references:
- https://opengitops.dev/
-  https://www.gitops.tech/
- https://github.com/readme/featured/defining-gitops
- https://www.atlassian.com/git/tutorials/gitops
- https://www.redhat.com/architect/understanding-gitops
- https://about.gitlab.com/topics/gitops/

2023-12-04 20:30 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +**Lifecycle.** Kubernetes occupies a central place in cloud native infrastructure by following the paradigm of ephemeral resources
definition added to intro

2023-12-04 21:24 UTC, lixuna requested changes

2023-12-04 21:24 UTC, lixuna commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +1. **Adaptations.** It shall possible for CSP’s DevOps or vendor’s delivery team to adapt CNF artifacts (e.g. YAML manifests, Helm charts, NFVO descriptors) to align the deployments to the local spec
```suggestion
1. **Adaptations.** It shall be possible for CSP’s DevOps or vendor’s delivery teams to adapt CNF artifacts (e.g. YAML manifests, Helm charts, NFVO descriptors) to align the deployments to the local specifics of CSP (e.g. Policy, RBAC, Compatibility) without special Change Requests or involving complex R&D processes.
```

2023-12-04 22:59 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   declarative cloud native mechanisms like GitOps.
Added as annex 2 at end of doc

2023-12-04 23:08 UTC, lixuna approved these changes
lgtm

2023-12-05 00:22 UTC, merged

2023-12-05 01:43 UTC, SaadUSheikh reviewed
my inputs for the document

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +The document presented here is a product of the initial joint work of several Communication Service Providers (CSPs) who are active in Cloud Native Computing Foundation (CNCF)’s Cloud Native Network
Linus Foundation Networking (LFN) should be changed to Linux  Foundation Networking (LFN)

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +elements. Although large parts of CNFs do not have problems with that cloud native lifecycle approach, we are experiencing that
LCM is a separate topic , similarly Resilience (improve HA design) and Reliability . These all three should be placed as separate points for challenges .

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
I believe this is a bit skewed view and touches only SI activities , ideally we should phrase it on 

[Architecture]
1. Architecture complexity (Separation of concerns) between Infra and App is not well qunatified , e.g for Infra we settle cloud infra but SLA/KQI promised by Infra to App are not defined leaving this interpretation open to App.
2. There is a similar effort done in ETSI TST06 specs but again it do not co-relate or map Infra to App 

[Operational complexity]
1. common operating models between infra and App are not defined or at least still not mature enough for brownfield 
(We can allude to Nephio app and infra LCM to share our view)
2. SI activities are very complex to apply in operations because the DIY means always some issues do not pass regressive testing pipeline

[Business risk]
1. Bigger challenge is here SLA/contract , there are too many if/buts and causing major issue in service fulfillment
2. Cost efficiency is not proven for scalable deployment

[Observability and monitoring]
1. There are silo ways to monitor and observe which are becoming a break point to deliver value from automation . also co-relation mechanism between Infra and App is largely a role of SMO/NFVO which are designed  for apps . it means end-to-end desired state is hard to achieve 

[Application benchmarking]
CNF designs still not follow 12 factor app but there are gaps in industry alignment to benchmark telco Apps this way . One prime reason is CNF app dev is basically a black box activity .  The right challenge here is not 12 factor but ability to benchmark it and give a score gokld/bronze/silver agreed and endorsed in industry

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   1. Each CNF shall be validated, including the implementation of any adaptations that may be required, within 3 months of
why 3months and how we can ensure , can we make it more clear

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. The validation shall be a continuous process and shall be instantly done on any change be it on CNF or on the infrastructure
There needs to clarify on scope of activities in both pre-validation and validation with out this whether they deliver outcome will be a challenge

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +1. **Resilience.**  High-quality CNFs should be resilient to underlying infrastructure issues including complete failure,
Sugges to add one item on "Testing framework" i.e idea is all points above can be tested in an automated fashion and how we can achieve it

2023-12-05 01:43 UTC, SaadUSheikh commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +1. **Resilience.**  High-quality CNFs should be resilient to underlying infrastructure issues including complete failure,
Add two more section on how to solve it

1. operational readiness 
e.g in brownfield how we can integrate , co-exist it with existing tools and align with processess

2.  Commercial models
do local tuning is a great way for Telco clouds but with Edge/RAN it is important that we test once and deploy in a scalable manner , even those deployments need to be tested . so defining what are those models of scale are key to success .
For procurement, right TCO and most important automation at scale is vital here

2023-12-11 21:58 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +architecture and solution approach is revenue from professional service that allows them to create business models on CNFs deployment,
See newer version of whitepaper

2023-12-11 21:59 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +   1. Each CNF shall be validated, including the implementation of any adaptations that may be required, within 3 months of
@SaadUSheikh See comments from @pensarguet and @vukg. Also read newest version of paper

2023-12-11 21:59 UTC, taylor commented on doc/whitepaper/Accelerating_Cloud_Native_in_Telco.md
> +    1. The validation shall be a continuous process and shall be instantly done on any change be it on CNF or on the infrastructure
If you have suggestions please specify those clearly.