Update 0001-cnf-conformance-definition-proposal-process.md
lfn-cnti/bestpractices pull request #29
Opened 2020-12-09 22:15 UTC by jeffsaelens

First pass here before looking at the template itself. I really think that a best practice should lay out to type of workload or container it applies to. OSS/BSS, NF and infra containers may have best practices applied to them in unequal measure depending on their desired outcome. A container specifically designed to provision infra will need privilege for example, while a container hosting BGP would not. 

They alternative to this approach is for the definition of a CNF to be formalized (producing this is listed as a group outcome in our charter) and have its scope limited. From there we clarify that the best practices specifically apply to these "types" of workloads/containers.

2020-12-10 01:10 UTC, taylor requested changes
@jeffsaelens seeming like the terminology could support "infra" and "application" CNFs.

2020-12-10 01:10 UTC, taylor commented on ccdps/0001-cnf-conformance-definition-proposal-process.md
> +
@jeffsaelens can you provide some examples of different types?

2020-12-10 01:10 UTC, taylor commented on ccdps/0001-cnf-conformance-definition-proposal-process.md
> +Context should be provided for the type of workload/container this best practice applies to. The context, of an individual best practice, should illustrate the specific type of workload most likey to
```suggestion
Context should be provided which includes the type of CNF, workload, and CNF component (eg. Pod, container, Operator) this best practice applies to. The context, of an individual best practice, should illustrate the specific type of workload most likely to take advantage of the benefits listed. When applicable, it should also provide a warning if the practice would be a determent to a divergent type of workload.
```

2020-12-10 14:53 UTC, jeffsaelens commented on ccdps/0001-cnf-conformance-definition-proposal-process.md
> +
Sure, infrastructure/orchestration/provisioning style workloads. One that we do actually want to have some type of privilege as they are interacting with systems on our behalf. The core network functions themselves. These ones may need no privilege but have unique dos/don'ts from a NAT, ingress/egress etc... perspective. OSS/BSS containers, logging/monitoring (most likely to be bundled in by the dev to ensure the appropriate metrics are actually captured). The list could go on. One issue is we don't have a proper definition of what a CNF is. Is it a single container that has nay sort of NF living inside? Is it a suite of microservices that make up the whole? My main fear is we describe some of these best practices as one size fits all and end up with ETSI MANO again where things are a little too broad and begin to lose value.

2020-12-17 22:33 UTC, taylor commented on ccdps/0001-cnf-conformance-definition-proposal-process.md
> +
@jeffsaelens these examples would be a good addition to the document.

We'll address what a CNF is in some of the primary docs (eg. README, charter) partially based on discussions in https://github.com/cncf/cnf-wg/discussions/27 and recent ones in Slack.

2020-12-17 22:37 UTC, taylor commented
@rabi-abdel, @vukg

2020-12-21 16:24 UTC, tomkivlin approved these changes
lgtm

2021-01-12 11:08 UTC, xmulligan commented
@fkautz what do you think?

2021-01-25 16:07 UTC, taylor approved these changes

2021-01-25 16:14 UTC, xmulligan commented
From 2021-01-25 meeting
[Shane] is it a single container or multiple
[Jambi] Should this be a drop down vs a free form?

2021-01-25 16:14 UTC, merged