Update bestpractices doc README.md
lfn-cnti/bestpractices pull request #333
Opened 2024-03-04 22:37 UTC by lixuna

Ref #330

2024-03-15 22:44 UTC, jeffsaelens requested changes
Focus group, Best Practices focus area, etc... are all pretty cumbersome from a mouthful perspective. Is this standard wording for LFN or could we look for potential options to streamline these phrases a smidge?

Maybe CNTI Community vs focus group as an example?

2024-03-15 22:44 UTC, jeffsaelens commented on doc/README.md
> +The goal of the Cloud Native Telecom Initiative (CNTI) Best Practices focus area is to define a set of practices to evaluate the extent to which a CNF is [cloud native](https://github.com/cloud-nativ
goal of -> focus area reads a little wonky

2024-03-15 22:44 UTC, jeffsaelens commented on doc/README.md
> +The CNTI Best Practices focus group will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of
are we a focus group? once again, the wordiness of the line makes it difficult to consume. Not 100% sure how to condense this and still capture the point you were aiming for.

2024-03-15 22:44 UTC, jeffsaelens commented on doc/README.md
> +The current focus of CNTI Best Practices Focus Area is to define the best practices for the development and deployment of CNFs. Other areas are left for future focus.
```suggestion
The current goal of CNTI Best Practices Focus Area is to define the best practices for the development and deployment of CNFs. Other areas are left for future focus.
```

2024-03-15 22:44 UTC, jeffsaelens commented on doc/cbpps/0001-cnf-best-practice-proposal-process.md
> +An important goal of the CBPP process is ensuring that the process for submitting the content is both clear and efficient. The CBPP process is intended to create high-quality, uniform design document
focus group?

2024-03-15 22:44 UTC, jeffsaelens commented on doc/cbpps/README.md
> +CBPP shall always refer to at least one of the CNF use cases. Those use cases serve as the practical and concrete basis for deriving, discussing and evaluating the best practices for CNFs. Their valu
```suggestion
CBPP shall always refer to at least one CNF use case. These use cases serve as the practical and concrete basis for deriving, discussing and evaluating the best practices for CNFs. Their value is in providing context and a reality check for CBPPs. With help of use cases we make sure that CBPPs are addressing a specific problem or need from the real world. Please use the [Use Case Template](../use-case/NNNN-UC-template.md) to contribute a use case.
```

2024-03-19 21:56 UTC, taylor commented on doc/README.md
> +The CNTI Best Practices focus group will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of
@jeffsaelens the focus group or focus area are words that do not have baggage in LF(N)/CNCF like project and initiative. We have the overall effort (CNTi) and the sub-thing or focus area for best practices (previously called CNF WG)

2024-03-19 21:57 UTC, taylor commented on doc/README.md
> +The CNTI Best Practices focus group will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of
@lixuna Maybe this should say focus area instead of focus group

2024-03-19 21:59 UTC, taylor commented on doc/README.md
> +The CNTI Best Practices focus group will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of
```suggestion
The CNTI Best Practices focus area will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of "cloud native" in relation to the telecom industry.
```

2024-03-19 22:01 UTC, taylor commented on doc/README.md
> +The goal of the Cloud Native Telecom Initiative (CNTI) Best Practices focus area is to define a set of practices to evaluate the extent to which a CNF is [cloud native](https://github.com/cloud-nativ
@jeffsaelens If you don't have a grammar alternative suggestion we will leave it like this for now.

2024-03-19 22:01 UTC, lixuna commented on doc/README.md
> +The CNTI Best Practices focus group will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of
```suggestion
The CNTI Best Practices focus area will rely on other industry initiatives (such as [NGMN](https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html) to come up with a definition of "cloud native" in relation to the telecom industry.
```

2024-03-19 22:04 UTC, merged