initial content for framework
lfn-cnti/bestpractices pull request #34
Opened 2020-12-17 11:14 UTC by rabi-abdel

2020-12-17 12:04 UTC, CsatariGergely requested changes
I do not think that we need DS_Store and please commit also the source of the image.

2020-12-17 12:04 UTC, CsatariGergely commented on doc/README.md
> +The goal of this group is to define set of practices in which CNF can be evaluated on to dtermine how cloud native a CNF is (based on those best practices). CNF can be evaluated against those best pr
dtermine -> determine
thourhg -> through

2020-12-17 12:04 UTC, CsatariGergely commented on doc/README.md
> +<p align="center"><b>Figure 1-1:</b> Current Scope of CNF-WG</p>
I think not all of the CNF is in the scope of CNF WG. I would put everything related to the interaction with the infrastructure to the scope of CNTT RA2.

2020-12-17 12:27 UTC, tomkivlin commented on doc/best_cnf_dev.md
> +### BEST_CNF_DEV_1001: Application is configured via standard, automated, and repeatable way.
Can I suggest that each one of these entries covers a single thing only.  i.e. this one has a list of three characteristics, "standard, automated, and repeatable" and the next has two, "membership of the tier and is discoverable".  I think it'll mean each specific attribute of the CNF is testable, rather than combing multiple things into one test.

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +The goal of this group is to define set of practices in which CNF can be evaluated on to dtermine how cloud native a CNF is (based on those best practices). CNF can be evaluated against those best pr
```suggestion
The goal of this group is to define a set of practices against which CNFs can be evaluated to determine how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) native a CNF is based on those best practices. CNFs can be evaluated against those best practices throught test cases that are developed by other complimentary open source projects like the [CNF Test Suite](https://github.com/cncf/cnf-conformance/blob/master/README-testsuite.md)
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +The goal of this group is to define set of practices in which CNF can be evaluated on to dtermine how cloud native a CNF is (based on those best practices). CNF can be evaluated against those best pr
```suggestion
The goal of CNF Working Group (WG) is to define set of practices in which CNF can be evaluated on to dtermine how cloud native a CNF is (based on those best practices). CNF can be evaluated against those best practices thourhg test cases that are developed by other complimentary open source projects.
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +The goal of CNF-WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
```suggestion
The goal of CNF WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +The goal of CNF-WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
Can you expand on this a little more?

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +
```suggestion
Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. While it may be impossible for anything to be completely cloud native, implementing even one best practice can help improve business outcomes for everyone involved. Implemting more of them can have an even greater impact. However, depending upon the type of CNF, different best practices may have a greater or smaller impact on the ultimate business outcome. 
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +- **MUST NOT**:
Rather than having this, one idea was to have scoring whereby people using a test suite can provide different weights depending upon how important different aspects of cloud native are. @rabi-abdel what do you think of this?

https://github.com/cncf/cnf-conformance/blob/master/scoring_config/points_v1.yml

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +
```suggestion
As the telco industry transitions to cloud native ways of thinking, working, and operating, these best practices will serve as the industry gold standard of what cloud native means in practice. They can be for a variety of purposes including being used in RFPs, to guide daily operations, and to do internal testing.
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +As demonstrated by **Figure 1-1** below, When it comes to Cloud Native Network Functions (CNFs), there are many areas that can be foucused on in order to determine different best practices for differ
```suggestion
As demonstrated by **Figure 1-1** below, When it comes to Cloud Native Network Functions (CNFs), there are many areas that can be focused on in order to determine different best practices for different Actors. They are:
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +The current focus of CNF-WG is to define the best practices for the Development of CNFs. Other areas are left for future focus.
```suggestion
The current focus of CNF WG is to define the best practices for the Development of CNFs. Other areas are left for future focus.
```

2020-12-17 13:26 UTC, xmulligan commented on doc/README.md
> +<p align="center"><b>Figure 1-1:</b> Current Scope of CNF-WG</p>
I think that is what he is saying below.

2020-12-17 13:26 UTC, xmulligan commented on doc/best_cnf_dev.md
> +### BEST_CNF_DEV_1001: Application is configured via standard, automated, and repeatable way.
@rabi-abdel what do you think of the proposal template? https://github.com/cncf/cnf-wg/blob/master/ccdps/NNNN-ccdp-template.md

2020-12-17 13:33 UTC, tomkivlin commented on doc/README.md
> +The goal of CNF-WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
@xmulligan there is a second instance of `CNF-WG` on that line.

2020-12-17 13:34 UTC, tomkivlin commented on doc/README.md
> +The goal of CNF-WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
(and multiple elsewhere in the doc - we should look to be consistent throughout)

2020-12-17 14:54 UTC, xmulligan commented on doc/README.md
> +The goal of CNF-WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
Thanks, I tried to be consistent throughout as not having the dash, but I missed this one.

2020-12-18 09:26 UTC, rabi-abdel commented on doc/README.md
> +The goal of this group is to define set of practices in which CNF can be evaluated on to dtermine how cloud native a CNF is (based on those best practices). CNF can be evaluated against those best pr
done

2020-12-18 09:33 UTC, rabi-abdel commented on doc/best_cnf_dev.md
> +### BEST_CNF_DEV_1001: Application is configured via standard, automated, and repeatable way.
@xmulligan i like the template, i think then what we can do is keeping a very short version of the best practice in here and putting a link to the template (source) of it explaining the stories, details, etc. 

For @tomkivlin point, i agree. we might also have one more best practice covered by one template (source). but we spell them out as appropriate in here.

happy to reflect the changes if you agree

2020-12-18 09:40 UTC, rabi-abdel commented on doc/README.md
> +<p align="center"><b>Figure 1-1:</b> Current Scope of CNF-WG</p>
@CsatariGergely comments addressed

2020-12-18 11:09 UTC, xmulligan commented on doc/best_cnf_dev.md
> +### BEST_CNF_DEV_1001: Application is configured via standard, automated, and repeatable way.
ok, totally makes sens to me now. I really like the idea and will give us a better way to organize the proposals. People will be able to skip around to the sections they care about and find the proposals there rather than having to search through everything.

2020-12-18 11:42 UTC, rabi-abdel commented on doc/best_cnf_dev.md
> +### BEST_CNF_DEV_1001: Application is configured via standard, automated, and repeatable way.
I have placed a link to CCDP file for best practices. i think this model is scalable. people can work on CCDP for best practices they like to include and once approved and agreed on, they can be placed here with the right ref.

2020-12-18 11:51 UTC, rabi-abdel commented on doc/README.md
> +The goal of CNF-WG is not trying to define what cloud native for netowrk function is. CNF-WG will rely on other industry inititaves (such as CNCF TUG) to define that.
have added a diagram.

2020-12-18 11:52 UTC, rabi-abdel commented on doc/README.md
> +- **MUST NOT**:
makes sense.

2020-12-21 16:19 UTC, tomkivlin approved these changes

2021-01-05 21:07 UTC, vukg requested changes

2021-01-05 21:07 UTC, vukg commented on doc/README.md
> +
We need to be more concrete and explicit in showing the purpose of this recommendations and other outcomes and show the basic value add.

Usage for RFPs is certainly very good point in that direction.

To make it stronger I would formulate following "These recommendations shall serve as generic contract between CNFs and cloud native infrastructure / platforms. If both any CNF and any platform follow these recommendations it should be assured that they will run nicely together out-of-box. In a sense fulfilling this contract represents implicit (pre)certification that the combination can be used in the production."

This would be very powerful and motivating contract and goal to reach.

2021-01-05 21:07 UTC, vukg commented on doc/README.md
> +- **Building of CNF Infrastructure**: Set of best practices that helps CNF Infra Vendors to build and develop CNF Infrastucture in a cloud native way.
Add CNF Infra Vendors and Developers as not all Infra comes from vendors. Some are using directly upstream with some integrations and sys engineering (DT case), while others are developing their own OSS projects (e.g. ATT with Airship)

2021-01-05 21:07 UTC, vukg commented on doc/README.md
> +The current focus of CNF WG is to define the best practices for the Development of CNFs. Other areas are left for future focus.
Development is done in order that something gets deployed so it in turns helps deployment. This is where CNF-Infra contract aspect comes into play. I would recommend to include that.

2021-01-06 13:06 UTC, xmulligan commented on doc/README.md
> +The current focus of CNF WG is to define the best practices for the Development of CNFs. Other areas are left for future focus.
Do you have a suggested wording?

2021-01-06 13:07 UTC, xmulligan commented on doc/README.md
> +- **Building of CNF Infrastructure**: Set of best practices that helps CNF Infra Vendors to build and develop CNF Infrastucture in a cloud native way.
```suggestion
- **Building of CNF Infrastructure**: Set of best practices that helps CNF Infra Vendors and developers to build and develop CNF Infrastucture in a cloud native way.
```

2021-01-06 13:08 UTC, xmulligan commented on doc/README.md
> +- **Development of CNFs**: Set of best practices that helps CNF Vendors to develop their CNFs in a cloud native way.
```suggestion
- **Development of CNFs**: Set of best practices that helps CNF Vendors and developers to build their CNFs in a cloud native way.
```

2021-01-06 13:08 UTC, xmulligan commented on doc/README.md
> +- **Building of CNF Infrastructure**: Set of best practices that helps CNF Infra Vendors to build and develop CNF Infrastucture in a cloud native way.
added suggestions

2021-01-06 13:10 UTC, xmulligan commented on doc/README.md
> +
```suggestion

These recommendations can serve as a generic contract between CNFs and cloud native infrastructure. If both a CNF and a platform follow these recommendations, they can run more smoothly together out-of-box. In a sense fulfilling this contract represents implicit (pre)certification that the combination can be used in the production.
```

2021-01-06 15:07 UTC, vukg commented on doc/README.md
> +The current focus of CNF WG is to define the best practices for the Development of CNFs. Other areas are left for future focus.
long version:
"The current focus of CNF WG is to define the best practices for the Development & Deployment of CNFs which can be used as guidelines for development of efficient CNFs and cloud native infra/platforms for CNFs. These best practices represent in turn a generic contract between CNFs and cloud native infa/platforms that can be widely used to certify if CNF can run as expected on the platform or vice versa if the platform is suitable for CNFs that follow the best practices. Other areas are left for future focus."

short version:
"The current focus of CNF WG is to define the best practices for the Development & Deployment of CNFs. Other areas are left for future focus."

2021-01-06 15:10 UTC, vukg commented on doc/README.md
> +- **Building of CNF Infrastructure**: Set of best practices that helps CNF Infra Vendors to build and develop CNF Infrastucture in a cloud native way.
why not generalizing and staying on roles of individuals instead of organizations. Eliminate terms vendors, SPs and others and keep only CNF developers, platform developers, CNF operators, platform operators.

2021-01-06 15:12 UTC, vukg reviewed
+1

2021-01-06 23:37 UTC, taylor commented on doc/README.md
> +- **Development of CNFs**: Set of best practices that helps CNF Vendors to develop their CNFs in a cloud native way.
```suggestion
- **Development of CNFs**: Set of best practices that helps CNF Developers to build their CNFs in a cloud native way.
```

2021-01-11 12:22 UTC, xmulligan commented on doc/README.md
> +The current focus of CNF WG is to define the best practices for the Development of CNFs. Other areas are left for future focus.
```suggestion
The current focus of CNF WG is to define the best practices for the development and deployment of CNFs. Other areas are left for future focus.
```

2021-01-11 16:05 UTC, claudiobartolini approved these changes

2021-01-11 16:34 UTC, pgoyal01 commented on doc/README.md
> +The goal of this group is to define a set of practices against which CNFs can be evaluated to determine how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is
This sentence can be simplified.
```suggestion
The goal of this group is to define a set of practices that can be used for evaluating of how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF. CNFs can be evaluated against those best practices through test cases that are developed by other open source projects like the [CNF Test Suite](https://github.com/cncf/cnf-conformance/blob/master/README-testsuite.md)
```

2021-01-11 16:37 UTC, pgoyal01 commented on doc/README.md
> +The goal of CNF WG is not trying to define what cloud native for netowrk function is. CNF WG will rely on other industry inititaves (such as CNCF TUG) to define that.
Could we turn this positive? For example,
```suggestion
CNF WG will rely on other industry initiatives (such as CNCF TUG) to define the characteristics of a "cloud native" artifact.
```

2021-01-11 16:40 UTC, pgoyal01 commented on doc/README.md
> +As the telco industry transitions to cloud native ways of thinking, working, and operating, these best practices will serve as the industry gold standard of what cloud native means in practice. They
```suggestion
As the telco industry transitions to cloud native ways of thinking, working, and operating, these best practices will serve as the industry gold standard of what cloud native means in practice. They can be used for a variety of purposes including in RFPs, to guide daily operations, and to do internal testing.
```

2021-01-11 16:43 UTC, pgoyal01 commented on doc/README.md
> +Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. W
Is this is not somewhat contradictory from what is stated previously? "gold standard of what cloud native means in practice",

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +The goal of CNF WG is not trying to define what cloud native for netowrk function is. CNF WG will rely on other industry inititaves (such as CNCF TUG) to define that.
Besides there is a typo
```suggestion
The goal of CNF WG is not trying to define what cloud native for network function is. CNF WG will rely on other industry initiatives (such as CNCF TUG) to define that.
```

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. W
```suggestion
Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. While it may be impossible for anything to be completely cloud native, implementing even one best practice can help improve business outcomes for everyone involved. Implementing more of them can have an even greater impact. However, depending upon the type of CNF, different best practices may have a greater or smaller impact on the ultimate business outcome. 
```

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +- **Consumption of CNFs**: Set of best pracitices that helps Customers/Consumers to consume and use CNFs in a cloud native way.
```suggestion
- **Consumption of CNFs**: Set of best practices that helps Customers/Consumers to consume and use CNFs in a cloud native way. 
```

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +- **Consumption of CNFs**: Set of best pracitices that helps Customers/Consumers to consume and use CNFs in a cloud native way.
I'd suggest to change `best practices` for `expectations` or `behaviors` given that they only define requirements.
```suggestion
- **Consumption of CNFs**: Set of behaviors expected by Customers/Consumers when CNFs are consumed in a cloud native way. 
```

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +- **Operation of CNFs**: Set of best practices that helps CNF Operators to deploy and manage CNFs in a cloud native way.
Ideally(in a state of the art CNF) this set of practices doesn't have to exist , isn't it? Auto-healing, auto-scaling, CI/CD, etc pretend to eliminate any kind of operation.

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +- **Operation of CNF Infrastructure**: Set of best practices that helps CNF Infra Operators to deploy and manage CNF infrastucture in cloud native way.
```suggestion
- **Operation of CNF Infrastructure**: Set of best practices that helps CNF Infra Operators to deploy and manage CNF infrastructure in cloud native way.
```

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +* [Installable and Upgradeable](./best_cnf_dev.md#2.0)
Shouldn't be better to use `Day 1` and `Day 2` operations terms here?

2021-01-12 00:51 UTC, electrocucaracha commented on doc/README.md
> +## Best Practices for CNF Developers
Can we include `Portability` as a best practice for CNFs?

2021-01-12 13:21 UTC, rabi-abdel commented on doc/README.md
> +
Address in https://github.com/cncf/cnf-wg/pull/34/commits/afe6763e5bb42aee7a8076cc605fe9822db1a2df

2021-01-12 13:26 UTC, rabi-abdel commented on doc/README.md
> +- **Consumption of CNFs**: Set of best pracitices that helps Customers/Consumers to consume and use CNFs in a cloud native way.
we used best practices in everywhere. i suggest sticking to it.

2021-01-12 13:27 UTC, rabi-abdel commented on doc/README.md
> +* [Installable and Upgradeable](./best_cnf_dev.md#2.0)
i wont encourage it. this will open a can of worm :) there is not industry wide agreement of Days and what they mean.

2021-01-12 13:27 UTC, rabi-abdel commented on doc/README.md
> +## Best Practices for CNF Developers
Yes, this can be submitted though a template.

2021-01-12 13:30 UTC, rabi-abdel commented on doc/README.md
> +Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. W
not sure about minimum characteristics. everything that is proven to be best practice though user stories, test cases, results will qualify.

2021-01-12 13:30 UTC, tomkivlin commented on doc/README.md
> +- **Consumption of CNFs**: Set of best pracitices that helps Customers/Consumers to consume and use CNFs in a cloud native way.
@rabi-abdel agreed. Can we correct the spelling though :)
```suggestion
- **Consumption of CNFs**: Set of best practices that helps Customers/Consumers to consume and use CNFs in a cloud native way. 
```

2021-01-12 14:42 UTC, Smitholi67 commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluating how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be eval
Change evaluating to evaluate

2021-01-12 14:50 UTC, Smitholi67 commented on doc/README.md
> +As the telco industry transitions to cloud native ways of thinking, working, and operating, these best practices will serve as the industry gold standard of what cloud native means in practice. They
Maybe add that it also helps to guide CNF design/development

2021-01-12 14:56 UTC, xmulligan commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluating how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be eval
```suggestion
The goal of this group is to define a set of practices that can be used to evaluate how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be evaluated against those best practices through test cases that are developed by other open source projects like the [CNF Test Suite](https://github.com/cncf/cnf-conformance/blob/master/README-testsuite.md)
```

2021-01-12 15:32 UTC, Smitholi67 commented on doc/README.md
> +* [Stateless](./best_cnf_dev.md#6.0)
There are CNFs that have a role in managing state such as the CHF (Charging Function) as part of a 5G Core.  I certainly understand the point of developing stateless microservices but I feel we ALSO need to address how state can be managed in acceptable cloud native ways when necessary.  This type of guidance would be especially valuable for those applications (CNFs) that are managing state under very high transaction volumes (10-100k's of TPS) - again think of the CHF as just one example.

2021-01-12 15:56 UTC, tomkivlin commented on doc/README.md
> +* [Stateless](./best_cnf_dev.md#6.0)
I just think we need to be clear the difference between application state and transaction / session state and so having a series of stateless microservices (which are therefore immutable) deal with stateful transactions (where that state is held in e.g. CHF) isn't necessarily a problem.

2021-01-12 16:55 UTC, Smitholi67 commented on doc/README.md
> +* [Stateless](./best_cnf_dev.md#6.0)
Maybe CHF is not the best example.  Let's take the CCS or UDR.  Both of these are the source of state for other NFs in the 5G Core.  They not only are state aware is my point, they own the state.  So if you are vendor designing one of these functions (or a service provider looking to buy one of these functions) then best practices for how state should be maintained for these types of NFs is going to be very valuable/important.

2021-01-12 17:13 UTC, tomkivlin commented on doc/README.md
> +* [Stateless](./best_cnf_dev.md#6.0)
I don't disagree - but even with those applications there will be stateful components (e.g. datastore) and stateless components that simply process transactions and perform logic.  But as a whole the CCS application is stateful, from the point of view of customer state.  But many components within CCS will be stateless from the point of view of needing to have prior knowledge of that customer state to be able to process transactions and perform business logic - they just accept an API instruction and product a response.

2021-01-13 21:52 UTC, taylor commented
@pgoyal01 I think your items have been addressed. Please re-review

2021-01-13 22:06 UTC, pgoyal01 commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluate how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be evalua
The CNF Test Suite doesn't specifically set out to test the [Cloud Native principles](https://github.com/cloud-native-principles/cloud-native-principles/blob/master/cloud-native-principles.md). In fact, Majority of the conformance tests are for Kubernetes rather than cloud native.

2021-01-13 22:08 UTC, pgoyal01 commented on doc/README.md
> +Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. W
I think there have to be some principles designated as being required for something to be cloud native. Otherwise, anything and everything could be made out to be cloud native.

2021-01-14 11:31 UTC, xmulligan commented on doc/README.md
> +As the telco industry transitions to cloud native ways of thinking, working, and operating, these best practices will serve as the industry gold standard of what cloud native means in practice. They
```suggestion
As the telco industry transitions to cloud native ways of thinking, working, and operating, these best practices will serve as the industry gold standard of what cloud native means in practice. They can be used for a variety of purposes including guiding CNF design and development, in RFPs, to guide daily operations, and to do internal testing.
```

2021-01-18 14:36 UTC, Smitholi67 commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluate how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be evalua
Suggest to rewrite as:  The goal of this group is to define a set of practices to evaluate the extent to which a CNF is  [cloud native](https://github.com/cloud-native-principles/cloud-native-principles).

2021-01-20 08:53 UTC, rabi-abdel commented on doc/README.md
> +Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. W
@pgoyal01 i think the point here is as long as it proves to be best practices, backed up with data and user story, it indeed can be considered cloud native as there is no strict definition of what is cloud native.

2021-01-20 08:55 UTC, rabi-abdel commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluate how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be evalua
Yes, like the change. done in https://github.com/cncf/cnf-wg/pull/34/commits/ad22897069f83f0ac72aadf7d3c6b2ebce49b8f4

2021-01-20 08:56 UTC, rabi-abdel commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluate how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be evalua
@pgoyal01 i believe the plan is to expand the scope of cnf-conformance to implement those best practices we define here.

2021-01-20 15:06 UTC, pgoyal01 commented on doc/README.md
> +Cloud native is not set point. The industry, technology, and best practices will continually evolve with each other. Thus, being cloud native should not be seen as pass/fail, but rather a spectrum. W
@rabi-abdel Agree that there is no strict definition of cloud-native and that is why it is important to not just list them and state that even if one practice is adopted that is good enough. We could have the situation with widely different CNFs for the same NF depending upon the vendor or version.

Wouldn't it be better, if a required set of practices is defined to qualify as cloud-native?

2021-01-20 15:09 UTC, pgoyal01 commented on doc/README.md
> +The goal of this group is to define a set of practices that can be used to evaluate how [cloud native](https://github.com/cloud-native-principles/cloud-native-principles) a CNF is. CNFs can be evalua
Wnen we say, "how cloud native" are we going to specify something like Bronze, Silver, Gold?

2021-01-25 16:19 UTC, xmulligan commented on doc/best_cnf_dev.md
> +## 9.0 bservability
```suggestion
## 9.0 Observability
```

2021-01-25 16:28 UTC, iawells requested changes

2021-01-25 16:28 UTC, iawells commented on doc/README.md
> +The goal of CNF WG is not trying to define what cloud native for netowrk function is. CNF WG will rely on other industry inititaves (such as CNCF TUG) to define that.
I don't think there is a good definition of cloud native for a network function elsewhere.  We've discussed in the channel among ourselves what matters and doesn't matter, and none of that is yet written down.  So I don't think we can or should rule ourselves out of documenting it.

2021-01-25 16:28 UTC, iawells commented on doc/best_cnf_dev.md
> +### BEST_CNF_DEV_1002: Applicaation announces it's own membership of the tier to it's peers.
Application / its

2021-01-25 16:28 UTC, xmulligan commented on doc/README.md
> +* [Stateless](./best_cnf_dev.md#6.0)
```suggestion
* [State](./best_cnf_dev.md#6.0)
```

2021-01-25 16:28 UTC, xmulligan commented on doc/best_cnf_dev.md
> +* [6.0 Stateless](#6.0)
```suggestion
* [6.0 State](#6.0)
```

2021-01-25 16:29 UTC, xmulligan commented on doc/best_cnf_dev.md
> +## 6.0 Stateless
```suggestion
## 6.0 State
```

2021-01-25 16:30 UTC, xmulligan commented
[Bryan] We should change it from "Stateless" to "State" because not everything is stateless and the larger discussion is around state.

2021-01-25 16:31 UTC, merged