Update Readme file
lfn-cnti/bestpractices pull request #364
Opened 2024-07-08 15:01 UTC by Smitholi67

Added new link for how to contribute to CNTi.

2024-07-08 15:12 UTC, rich-l approved these changes
lgtm

2024-07-08 16:43 UTC, taylor approved these changes
Lgtm

2024-07-09 12:40 UTC, martin-mat requested changes

2024-07-09 12:40 UTC, martin-mat commented on README.md
> +Learn more on how to get involved by visiting the [CNTi Best Practices Wiki](https://wiki.lfnetworking.org/x/HAAxBw) and reading about ways to [contribute](https://github.com/lfn-cnti/cnti/blob/46c6c
https://github.com/lfn-cnti/cnti/blob/main/CONTRIBUTING.md

2024-07-09 13:09 UTC, martin-mat approved these changes
lgtm, thanks.

2024-07-09 13:34 UTC, merged