use case folder and README
lfn-cnti/bestpractices pull request #46
Opened 2021-01-25 17:17 UTC by taylor

How to contribute use cases

2021-01-26 16:55 UTC, xmulligan commented
Do we want to be anymore prescriptive on how people should submit their use cases?

2021-01-26 18:00 UTC, taylor commented
> Do we want to be anymore prescriptive on how people should submit their use cases?

I don't want to slow down contributions so I did not add a template or more prescriptive instructions.  If there is a useful template someone can contribute that. Otherwise we can organically become more prescriptive as use cases are submitted.

2021-01-26 18:20 UTC, iawells requested changes

2021-01-26 18:20 UTC, iawells commented on use-case/README.md
> +As part of any proposed best practices it is requested to provide 1 or more use cases showing where the best practice could be used.
No need to hedge in an instruction document.  If this document is accepted, it's no longer a suggestion.
```suggestion
Proposed best practices are rooted in our model of how CNFs are used.  A best practice is most clearly the right thing to do if it helps with a use case related to one or more of the actors.
```

2021-01-26 18:20 UTC, iawells commented on use-case/README.md
> +This folder contains different networking use cases, their description, example references, and other context for each.
I know we're thinking about networking, but things like usability also deserve their time in the sun.
```suggestion
This folder contains different use cases, their description, references, and other context.
```

2021-01-26 18:20 UTC, iawells commented on use-case/README.md
> +If you just have an idea for a use case feel free to add to the discussion topic [listing networking uses cases](https://github.com/cncf/cnf-wg/discussions/39)
```suggestion
If you just have a part-formed idea for a use case feel free to add to the discussion topic [listing networking uses cases](https://github.com/cncf/cnf-wg/discussions/39).  This is the best place to go if you aren't sure how to write up the use case.  We can help you expand that into a full description.
```

2021-01-26 18:20 UTC, iawells commented on use-case/README.md
> +If you have a new use case you would like to discuss, create a new [github discussion topic](https://github.com/cncf/cnf-wg/discussions) with the details you have including attachements and/or links
```suggestion
If you have a new use case you would like to discuss in more depth, create a new [github discussion topic](https://github.com/cncf/cnf-wg/discussions) with the details you have including attachments and/or links to any external content (eg. Google docs, hackmd, diagrams).
```

2021-01-26 18:20 UTC, iawells commented on use-case/README.md
> +- new use case folder with all content with a README.md as the starting point describing the use case
OK, we're going to want a template for this with basic points we need to see in a use case.

The problem is that we have both use cases and user stories here and I see I'm already confusing the two: a use case is probably more about 'this is what we already do in the world' and a user story is more 'a named actor needs to get from point A to point B'.  I don't see much point in separating them - they both underpin our recommendations - but it might mean we need two templates to choose from.

Can I draw a line between 'external content' and 'citations'?  If we're talking about a preliminary writeup in google docs, then that's 'external content' - it might go away, but it's optional.  However, diagrams crucial to the explanation want committing into this repo as they need change tracking.  Citations are also external references demonstrating that what's written is objectively correct (rather than someone's opinion), and they do (as far as possible) want to be permalinks, fixed up if they break.

2021-01-27 00:51 UTC, taylor commented on use-case/README.md
> +If you just have an idea for a use case feel free to add to the discussion topic [listing networking uses cases](https://github.com/cncf/cnf-wg/discussions/39)
@iawells partially-formed

2021-01-27 00:55 UTC, taylor commented on use-case/README.md
> +- new use case folder with all content with a README.md as the starting point describing the use case
@iawells I like the idea of 2 templates. Can we add those after this PR is merged?  If we have a PR before templates are created we can always either delay the merge or merge and update the use case to fit the new template(s) when they are created.

2021-01-27 00:59 UTC, taylor commented on use-case/README.md
> +- new use case folder with all content with a README.md as the starting point describing the use case
I agree that citations can be external, but context crucial to the use case or user story (committed to the repo) should have all content included (I count GitHub's CDN as included)

2021-01-27 01:33 UTC, electrocucaracha commented on use-case/README.md
> +- Relating best practices to real world use cases.
As it was mentioned before best practices provides well-known methods to solve a specific problem. Having a clear distinction between the problem and the solution can facilitate its understanding. So maybe separating this bullet can facilitate that.
```suggestion
- Relating real world use cases.
- Best practices proposed.
```

2021-01-27 18:18 UTC, taylor commented on use-case/README.md
> +- Relating best practices to real world use cases.
@electrocucaracha understood. This README is talking about goals for the use cases.  So best practices stand-alone does not make sense to me here.

It could be reworded though... hmmm

2021-01-27 18:21 UTC, taylor commented on use-case/README.md
> +- Relating best practices to real world use cases.
@electrocucaracha how about if we just delete the entire goals section? The wording before it seems to cover the intent.

2021-01-27 18:22 UTC, taylor commented on use-case/README.md
> +- Relating best practices to real world use cases.
```suggestion
```

Delete ^^^

2021-01-27 18:22 UTC, iawells commented on use-case/README.md
> +- Relating best practices to real world use cases.
The aim is to document best practices here so that we can relate use cases to them (in the future, from the other part of the repo).  Something spun along that line?

2021-01-27 18:25 UTC, taylor commented on use-case/README.md
> +- Relating best practices to real world use cases.
Originally I added the "Goal" section to communicate what the purpose of these use cases were. It seems like it is redundant and not needed right now.

I suggest deleting it at this point https://github.com/cncf/cnf-wg/pull/46/files#r565533928

2021-01-27 18:29 UTC, iawells requested changes

2021-01-27 18:29 UTC, iawells commented on use-case/README.md
> +This folder contains different use cases, their description, references, and other context.
```suggestion
This folder contains different use cases, their description, references, and other context.  The best practices, recorded elsewhere, refer back to these use cases for their justification.
```

2021-01-27 18:29 UTC, iawells commented on use-case/README.md
> +- new use case folder with all content with a README.md as the starting point describing the use case
```suggestion
- new use case folder with all content with a README.md as the starting point describing the use case.

if you're going to do this via a pull request you must have a complete description of the use case.   You should have gathered any information you need and included it by this point.  We will then discuss the merits of the use case during review of the pull request, but this is not the time to be writing large sections of it.
```

2021-01-27 18:33 UTC, taylor commented on use-case/README.md
> +- Relating best practices to real world use cases.
@iawells @electrocucaracha the purpose of the "Goal" section was to communicate why we were creating/documenting these use cases 

> Goal:
> 
> - Relating best practices to real world use cases.
> - Discussion of core features and functionality from use cases and their NFs.
> - Examination of existing use cases to discussion of kubenative implementations which provide the core features and functionality.

The first bullet point, "Relating best practices to real world use cases," is related to the description update you suggested @iawells 
> A best practice is most clearly the right thing to do if it helps with a use case related to one or more of the actors.


Maybe the first bullet point can be reworded to something like:

> Provide use cases for best practices to reference

2021-01-27 18:49 UTC, iawells commented
I am now a happy bunny.

2021-01-27 18:50 UTC, iawells commented on use-case/README.md
> +- new use case folder with all content with a README.md as the starting point describing the use case
Right - we have our plans for templates, but we won't put them in yet.  Let's accept some use case pull requests and use that to feed what the template needs to look like.

2021-01-27 19:07 UTC, iawells commented on use-case/README.md
> +- Relating best practices to real world use cases.
If you took the other change I think it's covered and you can drop it entirely, but your suggestions are fine.

2021-01-27 22:44 UTC, electrocucaracha commented on use-case/README.md
> +- Relating best practices to real world use cases.
@taylor agree, the main idea is to provide uses cases and document their best practices used, isn't it? but maybe they can be categorized by the problem that they're solving and help to support those best practices. So  adding information about the problem provides more context about the decision of choosing a set of best practices, e.g. "This use case requires high availability without low latency"

2021-01-28 00:09 UTC, taylor commented on use-case/README.md
> +- Relating best practices to real world use cases.
@electrocucaracha I'm up for having just

- Relating real world use cases.


and not using 

- Best practices proposed.

as a change in goals for the use case readme. The latter does not make sense stand alone to me.  (unfinished sentence/thought)

2021-01-28 00:10 UTC, taylor commented
> I am now a happy bunny.

@iawells great :)

Now mark the PR as approved ✔️ 🐰

2021-01-28 12:25 UTC, rabi-abdel reviewed
looks good.

2021-01-28 12:25 UTC, rabi-abdel commented on use-case/README.md
> +This folder contains different use cases, their description, references, and other context.  The best practices, recorded elsewhere, refer back to these use cases for their justification.
@taylor i think it will be useful to clearly specify what information we need to see in a use case, in a bullet list.

- Problem statment.
- impact to real-life actor.
-  etc.

2021-01-28 17:47 UTC, jeffsaelens requested changes
Makes sense overall, I think a little tweaking is in order. Additionally, after this PR (no need to bog this one down), we should either put a template in the directory, or add additional parameters to the README as suggested by others. There is parts in the README that call out the discussions section, but its somewhat fuzzy of when you post in in there vs drafting a doc here.

2021-01-28 17:47 UTC, jeffsaelens commented on use-case/README.md
> +Proposed best practices are rooted in our model of how CNFs are used.  A best practice is most clearly the right thing to do if it helps with a use case related to one or more of the actors.
The second sentence reads awkwardly. "Most Cleary" is very strongly worded. It sounds almost biblical... Can we go a little softer and pull in our subject domain?

"A best practice is agreed upon as the optimal course of action when it satisfies the needs of a Kubernetes use case related to one or more actors?" This isn't perfect, but it has a little less finality in it.

2021-01-28 17:47 UTC, jeffsaelens commented on use-case/README.md
> +This folder contains different use cases, their description, references, and other context.  The best practices, recorded elsewhere, refer back to these use cases for their justification.
To Rabi's point, at some point we'd probably want a template for use cases and a means of pointing back to them from the best practices (this could also be a one to many scenario so some thought might be needed). I know we are trying to keep people's creative spirits soaring, but we could also use the "discussions" feature for more free form thoughts on paper if people aren't ready for a drafted proposal.

2021-02-01 16:35 UTC, xmulligan commented on use-case/README.md
> +- Relating best practices to real world use cases.
```suggestion
- Relating to real world use cases.
```

2021-02-01 16:38 UTC, xmulligan commented on use-case/README.md
> +This folder contains different use cases, their description, references, and other context.  The best practices, recorded elsewhere, refer back to these use cases for their justification.
We will add the template late. Issue to be created

2021-02-01 16:38 UTC, taylor commented on use-case/README.md
> +This folder contains different use cases, their description, references, and other context.  The best practices, recorded elsewhere, refer back to these use cases for their justification.
@rabi-abdel @jeffsaelens can we create an issue to address this?

2021-02-01 16:39 UTC, iawells requested changes

2021-02-01 16:39 UTC, iawells commented on use-case/README.md
> +Proposed best practices are rooted in our model of how CNFs are used.  A best practice is most clearly the right thing to do if it helps with a use case related to one or more of the actors.
```suggestion
It's clearer that a best practice is a good course of action when it satisfies the needs of a Kubernetes use case related to one or more actors.```

2021-02-01 16:39 UTC, taylor commented on use-case/README.md
> +This folder contains different use cases, their description, references, and other context.  The best practices, recorded elsewhere, refer back to these use cases for their justification.
@jeffsaelens verbally said yes on the CNF WG call

@xmulligan will create a new issue

2021-02-01 16:41 UTC, merged

2021-02-01 16:56 UTC, iawells commented
I would focus on:

Organisations involved
- SP, platform vendor, telco vendor (the SP may not use vendors or they may), SI, ...

Roles:
- Network architect - planning out the network
- CNF dev - writes a component they would want to use
- Platform dev - writes an operable (i.e. deployable and upgradeable) platform
- SI - glues the CNF and platform network together per architect's design and maybe patches up things the operator requests afterward
- Operator - day to day person that runs the resulting network

Then a section per role; and include in that section a discussion of the perspectives the role brings (e.g. reliability, security).

That's less fine grained than Taylor has in actors but the perspectives should cover the rest.

Then some example assignments of roles to orgs and additional considerations for that sort of breakdown (e.g. communications between roles, purchasing, when CNF is bought in, implications of an RFP process) - this comes last because it's the one that diverts us from the more technical details.