Add CNF WG member roles to charter
lfn-cnti/bestpractices pull request #55
Opened 2021-02-04 21:27 UTC by taylor

Add CNF WG member roles to governance section of charter
- Chairs
- Tech Leads
- Everyone else

2021-02-05 00:37 UTC, iawells commented
LGTM

2021-02-05 04:29 UTC, jeffsaelens approved these changes
Clear and concise.

2021-02-05 05:39 UTC, electrocucaracha commented
/lgtm

2021-02-05 09:59 UTC, xmulligan approved these changes

2021-02-05 09:59 UTC, tomkivlin approved these changes

2021-02-05 13:24 UTC, Smitholi67 approved these changes

2021-02-05 15:11 UTC, rabi-abdel approved these changes

2021-02-05 15:13 UTC, rabi-abdel commented
is the plan to also include details for the election process? that certainly can be on a separate PR

2021-02-05 15:21 UTC, xmulligan commented
@rabi-abdel yes, that will be a separate PR

2021-02-05 19:21 UTC, iawells requested changes

2021-02-05 19:21 UTC, iawells commented on charter.md
>  - Charter Communications
```suggestion
- Charter Communications
- Cisco
```

2021-02-05 21:10 UTC, electrocucaracha commented on charter.md
>  - Charter Communications
Technically speaking, this suggestion should have its own PR

2021-02-07 07:42 UTC, vukg commented
/lgtm

2021-02-08 14:09 UTC, iawells commented on charter.md
>  - Charter Communications
I mean, I can put it in as another pull request but I'm not sure I see why it's worth the extra effort (and I can't put it up until this is committed, I think?).  As far as I can see there's nothing special about the participants list here (that stops us filling it out in the initial commit.

2021-02-08 15:09 UTC, CsatariGergely approved these changes

2021-02-08 16:35 UTC, merged