Voting
lfn-cnti/bestpractices pull request #71
Opened 2021-02-19 12:05 UTC by xmulligan

2021-02-19 15:53 UTC, electrocucaracha commented on charter.md
> +The chair nominee from each community with the most votes will be elected. Tech leads must win at least 60% of the votes cast to be elected.
Open Infra and OPNFV uses the [Ranked voting system](https://en.wikipedia.org/wiki/Ranked_voting) which in my opinion it's a good option. Shouldn't be better to use it here?

2021-02-19 17:00 UTC, Smitholi67 commented on charter.md
> +Chairs and tech leads will be elected for one year terms and may run for reelection.
It might be more clear to refer to these as Co-Chairs and not Chairs.

2021-02-19 17:01 UTC, Smitholi67 approved these changes

2021-02-19 17:39 UTC, xmulligan commented on charter.md
> +Chairs and tech leads will be elected for one year terms and may run for reelection.
Thanks for the catch!

2021-02-19 17:39 UTC, xmulligan commented on charter.md
> +Chairs and tech leads will be elected for one year terms and may run for reelection.
```suggestion
Co-chairs and tech leads will be elected for one year terms and may run for reelection. 
```

2021-02-19 17:40 UTC, xmulligan commented on charter.md
> +The chair nominee from each community with the most votes will be elected. Tech leads must win at least 60% of the votes cast to be elected.
Let's discuss this in the meeting on Monday. I'm not opposed to it.

2021-02-19 17:56 UTC, rannyh commented on charter.md
> +Each organization listed in the interested parties section has one vote. Any contributor from an organization may cast the vote for that organization. Each organization can cast one vote for a co-cha
We may want to better define "organization". It gets complicated when companies have subsidiaries or op-co's. ONAP had to deal with it a few years back and this is what we ended up with:
https://wiki.onap.org/display/DW/ONAP+Technical+Community+Document#ONAPTechnicalCommunityDocument-4.4.1.4SubcommitteeVoterEligibility

Also, are there any rules for adding an organization to the "interested parties" list? Or do we rely on the common sense of whoever reviews the PR for adding an organization?

2021-02-19 21:27 UTC, iawells commented on charter.md
> +Each organization listed in the interested parties section has one vote. Any contributor from an organization may cast the vote for that organization. Each organization can cast one vote for a co-cha
Also, how do you find out what the organisation-approved vote is?  And are all organisations created equal?

I know why this is in there - to control the possible risk of being overwhelmed by numbers from a specific organisation - but it's not really an open-source-centric model of control being in the hands of participating individuals (e.g committers, as with the OIF).

2021-02-19 21:30 UTC, iawells commented on charter.md
> +Individuals not associated with or employed by a company or organization are allowed one organization vote. Each company or organization (regardless of the number of maintainers associated with or em
Per comment below, this leads to very unbalanced representation.

2021-02-19 21:30 UTC, iawells commented on charter.md
> +The chair nominee from each community with the most votes will be elected. Tech leads must win at least 60% of the votes cast to be elected.
How do we define which community a candidate is in?  How do we define who should be voting for someone in a community?

This may all be a bit too much worrying if the chairs are basically just organisers, mind.

2021-02-22 23:11 UTC, claudiobartolini approved these changes

2021-02-22 23:12 UTC, claudiobartolini approved these changes

2021-02-24 18:38 UTC, taylor commented on charter.md
> +Each organization listed in the interested parties section has one vote. Any contributor from an organization may cast the vote for that organization. Each organization can cast one vote for a co-cha
@rannyh for the "interested parties" list common sense when reviewing the PR is used.

2021-02-24 19:57 UTC, taylor requested changes

2021-02-24 19:57 UTC, taylor commented on charter.md
> +Individuals not associated with or employed by a company or organization are allowed one organization vote. Each company or organization (regardless of the number of maintainers associated with or em
```suggestion
Individuals not associated with or employed by a company or organization are allowed one vote. Each company/organization, or related group of companies (regardless of the number of maintainers associated with or employed by that company/organization), will have a maximum of one-third representation in votes.  If the results of an election result in greater than 1/3 representation, the lowest vote getters from any particular company will be removed until representation on the committee is less than one-third.
```

Ref: https://github.com/kubernetes/steering/blob/master/elections.md#maximal-representation
>To encourage diversity there will be a maximum of one-third representation on the Steering Committee from any one company at any time. ...

2021-02-24 19:57 UTC, taylor commented on charter.md
> +Individuals not associated with or employed by a company or organization are allowed one organization vote. Each company or organization (regardless of the number of maintainers associated with or em
This is about voting. See new PR for representation in the elected roles https://github.com/cncf/cnf-wg/pull/75

2021-02-25 04:56 UTC, claudiobartolini approved these changes

2021-02-25 13:50 UTC, xmulligan commented on charter.md
> +The chair nominee from each community with the most votes will be elected. Tech leads must win at least 60% of the votes cast to be elected.
I would expect candidates to self identify and police. If the voters feels the candidate isn't representing the right community, then they can choose against electing them.

2021-02-25 13:53 UTC, xmulligan commented on charter.md
> +
```suggestion

For the purpose of this document, “Related Company” shall mean any entity (Company-A) which controls or is controlled by another entity (Company-B) or which, together, is under the common control of a third party (Company-C), in each case where such control results from ownership, either directly or indirectly, of more than fifty percent of the voting securities or membership interests of the entity in question; and “Related Companies” are entities that are each a Related Company as described above.

```

2021-02-25 14:01 UTC, xmulligan commented on charter.md
> +Each organization listed in the interested parties section has one vote. Any contributor from an organization may cast the vote for that organization. Each organization can cast one vote for a co-cha
@rannyh Thanks for the reference! I've added the wording to make it more clear
I've also added a comment about the interested parties to the PR approval discussion https://github.com/cncf/cnf-wg/discussions/74#discussioncomment-405553

2021-02-25 14:03 UTC, xmulligan commented on charter.md
> +The chair nominee from each community with the most votes will be elected. Tech leads must win at least 60% of the votes cast to be elected.
```suggestion
The chair for each community will be elected using [Ranked Choice Voting](https://en.wikipedia.org/wiki/Ranked_voting). Tech leads must win at least 60% of the votes cast to be elected.
```

2021-02-25 14:04 UTC, xmulligan commented on charter.md
> +The chair nominee from each community with the most votes will be elected. Tech leads must win at least 60% of the votes cast to be elected.
Thanks, just updated to Ranked Choice Voting

2021-02-25 19:08 UTC, rannyh approved these changes
Looks like this covers all the necessary definitions

2021-03-08 15:41 UTC, electrocucaracha approved these changes

2021-03-08 16:09 UTC, merged

2021-03-08 17:13 UTC, iawells commented
As an aside, note that this is more about the reputation of this group being co-opted in the future than it is about it being seen as a mouthpiece for a vested interest in the present.  If it's obviously a mouthpiece, that's an issue, but it will impact our reputation and therefore adoption of our recommendations.  If our group is co-opted in the future, however, then a group will be able to take advantage of our established reputation.

1. Define representation groups that we wish to control representation on.  For instance: one chair per independent organisation, 30% of community votes, 30% of tech leads (to avoid majorities of conspirators).
2. A organisation is defined as a single company.
3. If a member (define 'member') raises a concern of independence: first they must demonstrate a relationship between organisations that lead to the conclusion they should be treated as a single organisation (e.g ownership, contractor-contractee); second, the relationship will be debated, since this does not necessarily demonstrate that the organisations are acting together; and third, action will be taken only if a majority of uninvolved members (choose your membership set here) votes for it.  The action would be that the multiple entities would be considered one organisation under the charter.
4. If, through this process, an organisation is overrepresented, the seats in question will all be put up for a special election.  The seats are open to all members, both previous holders and any other nominees.
5. In any elections (presuming we use STV or something similar), the members with least votes in an overrepresented group will be excluded from election (this should already be in some other part of the charter).  Where there are multiple candidates with the same number of least votes, it's a coin toss.
6. The decision on independence or dependence may be revisited after a period of not less than three months.  A member may raise it for discussion and the process in point 3 shall be repeated.  No immediate re-election of members shall occur if the organisations now are deemed independent; this will be taken into consideration in the next natural election cycle.

To game the above rules, you'd require a majority of the membership conspiring against some part of the community that had overrepresentation if and only if it were considered a bloc, _and_ that bloc would need some corporate relationship, so it would be an unproductive thing to try and do unless a real concern existed.  (I can't claim 'everyone not in my company is conspiring against me', for instance, because I haven't got valid grounds to raise the concern.)