Create a glossary for CNF-WG
lfn-cnti/bestpractices pull request #89
Opened 2021-03-18 15:57 UTC by jeffsaelens

This is a first pass to get the basic layout put in place for a glossary. I kept things limited, so we can get the framework in place and then begin to fill in definitions as the group identifies unknown terms.

This PR is to begin work on issue #82

2021-03-18 16:18 UTC, iawells requested changes

2021-03-18 16:18 UTC, iawells commented on doc/glossary.md
> +**Cloud-Native** - Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. Containers, servi
Doesn't actually define what cloud native is, but what it does.  (Per my usual ranting.)  Can we do a little bit better and have the definition before the benefits and the techniques?  Something like 'Software primarily designed to run on a compute cloud and take advantage of functionality specific to running on a cloud.'

2021-03-18 16:18 UTC, iawells commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
Define 'network function' first?

2021-03-18 16:18 UTC, iawells commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
Anything that talks networking lives in the OSI model (it includes the application layer), so that's a tautology.  You have more specific information, but even that is a bit wonky; we would consider BGP a network function.

Proposal: 

Network functions [NB: separating this from CNF, so that we could define VNF or PNF if we had to] consist of components whose primary task is to enable the network to function and to control its behaviour.  This might include functionality transforming packets, such as network encaps, switching, routing, firewalls or NAT; information sharing systems propagating network information, such as BGP, DHCP or DNS; or systems for gathering network information, including SNMP and BGP-LS.  More complex network functions, such a mobile packet cores, may combine multiple behaviours.

Software network functions are a specific type of application with a focus on the behaviour of the network.

2021-03-18 16:18 UTC, iawells commented on doc/glossary.md
> +**Kube-Native** - TBD
A subset of cloud-native applications specifically designed to run ion Kubernetes and built to take advantage of its inbuilt features and functionality.

2021-03-18 16:41 UTC, jeffsaelens commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
I'm against redefining things over and over again. If we want it called out, we should link to something as network functionality is not a novel concept here.

2021-03-18 16:43 UTC, iawells commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
Well, you're attempting to define it here, and I'm not sure I have seen a good definition of it, so I actually do appreciate your attempt.

CNF brings 'network function' and 'cloud native' together, though, and would be a shorter definition and more comprehensible if it did refer out to both concepts.

2021-03-18 16:52 UTC, jeffsaelens commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
I don't think we need to define network functions themselves. Also, I hesitate to include a big list of features/protocols as they then require to be defined themselves. I agree that anything talking networking lives in the OSI model, but I don't see what is wrong with saying the software we are describing lives in the OSI model vs providing a bunch of references/mechanisms to how data is treated at the various layers changes of said model.

We can debate/change the definition above, but I don't think we should spend a lot of time defining things that aren't unique to the space we are exploring.

2021-03-18 16:54 UTC, jeffsaelens commented on doc/glossary.md
> +**Cloud-Native** - Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. Containers, servi
The principles repo, vendors docs and other credible sources provide concrete definitions we could pull from. I just fork-lifted this because for good or ill its the official definition provided by the CNCF and we are working under their umbrella.

2021-03-18 17:39 UTC, electrocucaracha commented on doc/glossary.md
> +These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust automation, they allow engineers to make high-impact changes frequently and predic
is this *robust automation* referring to the CI processes? if that is the case we can make it more explicit like:

```suggestion
These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with Continuous Integration processes, engineers can make high-impact changes frequently and predictably with minimal toil.
```

2021-03-18 17:39 UTC, electrocucaracha commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
Just move the place of the acronym 
```suggestion
**Cloud-Native Network Function (CNF)** - Delivers network functionality in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Model [9], which is used to define a network's stack. The lower layers (layers 1 and in some cases, layer 2) are provisioned for the higher layers (2-7) to provide transport. These higher layers in this instance act as applications that act upon a network payload (frames, packets datagrams etc). A physical layer 1 networking device should be "flashed" with a complete replacement of its artifacts for updates. The configuration for physical layer 1 is done with an atomic application of a versioned configuration file, which replaces the configuration on the device at once. Virtual Layer 1 (and some layer 2) is managed via templated images and bootstrapping. In contrast, layers 2 through 7 are managed by higher-level orchestration or an established control plane (an orchestrator pushing configuration versus a network protocol modifying a route table).
```

2021-03-18 17:39 UTC, electrocucaracha commented on doc/glossary.md
> +**Kube-Native** - TBD
Technically, we can have *docker-swarm-native* and *mesos-native* applications right?

2021-03-18 17:39 UTC, electrocucaracha commented on doc/glossary.md
> +### Communinty Definitions
```suggestion
### Community Definitions
```

2021-03-18 17:39 UTC, electrocucaracha commented on doc/glossary.md
> +CNF Working Group Glossary
I think that we can assume the context of this document
```suggestion
Glossary
```

2021-03-18 17:56 UTC, iawells commented on doc/glossary.md
> +These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust automation, they allow engineers to make high-impact changes frequently and predic
I think as things stand this is a C&P from the CNCF definition. If we are just going to quote it (and that seems to be somewhat at odds with @jeffsaelens' other comments we should reference things) we should not change it.

2021-03-18 17:57 UTC, iawells commented on doc/glossary.md
> +**Kube-Native** - TBD
We can have AWS-native and OpenStack-native.  Clouds are not 'things that run containers'.

2021-03-18 19:04 UTC, jeffsaelens commented on doc/glossary.md
> +These techniques enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust automation, they allow engineers to make high-impact changes frequently and predic
Everything was a quote. I pulled all three defs from the links down in the references. I'm down to modify these, but I just put them as a starting point mainly to get a template in place for us to submit PRs against to add terms. I intentionally did not include a ton of definitions in the first PR because this will be the 4th-5th time I've been in debates around what the majority of these terms mean. (without almost the same crowd of people)

I figured, just get the glossary place holder in the repo so that the battle of PRs could begin a new. I strongly suggest that going forward we limit a PR to a single term. That way terms not caught in philosophical debates can be merged quickly.

2021-03-19 07:24 UTC, CsatariGergely commented on doc/glossary.md
> +**Cloud-Native** - Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. Containers, servi
If we stick to the CNCF definition we should also put a reference to it. 

I agree with @iawells , that the current CNCF cloud native definition does not define what cloud native is...

2021-03-19 07:31 UTC, CsatariGergely commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
I like more the [CNCF TUG's 1st CNF definition](https://docs.google.com/document/d/1-zqxz5bdCLTuOEvi2ybADR3PcmzbBhNt6YkNnvx-KoA/edit#) "A Cloud Native Virtual Network Function - or CN F for short - is an implementation of a Virtual Network Function (as defined by ETSI GS NFV 003 V1.4.1 (2018-08) that adheres to the CNCF Cloud Native Definition. "
or maybe the [CNCF TUG's 2nd CNF definition](https://github.com/cncf/telecom-user-group/raw/master/whitepaper/CNCF%20_TUG_Cloud%20Native%20Thinking%20for%20Telecommunications.pdf) "A cloud native network function (CNF) is a cloud native application that implements network functionality. A CNF consists of one or more microservices and has been developed using Cloud Native Principles including immutable infrastructure, declarative APIs, and a “repeatable deployment process”.
An example of a simple CNF is a packet filter that implements a single piece of network functionality as a microservice. A firewall is an example of a CNF which may be composed of more than one microservice (i.e. encryption, decryption, access lists, packet inspection, etc.).
The CNFs themselves, by nature of following cloud native principles, are also composable and can implement and facilitate more complex network functionality if needed.
CNFs and cloud native principles can be used when implementing applications and network infrastructure which needs to meet standards such as 3GPP. For example, an Evolved Packet Core’s (EPC) Serving Gateway could be implemented as a CNF and support all 3GPP requirements (eg. S1 protocol stack) allowing integration with other EPC services."

I think we should not redefine network function as we clearly refer to VNF-s with the CNF definition and in ETSI NFV NF already have a definition.

2021-03-19 07:48 UTC, fkautz commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
We'd also like to have CNFs target enterprise organizations, which won't adhere to ETSI. I think it's ok to look there for inspiration, but we probably shouldn't tie it to "requires ETSI" or we'll lose that crowd.

2021-03-19 09:02 UTC, fkautz commented on doc/glossary.md
> +**Kube-Native** - TBD
Correct, but for the initial scope of this WG, I believe we're focusing on kube-native and will expand out later.

2021-03-19 15:52 UTC, jeffsaelens reviewed
I'm willing to scrap definitions and just change this to a list of place holders if needed. That way we could at least get the template in place.

2021-03-19 15:52 UTC, jeffsaelens commented on doc/glossary.md
> +**Cloud-Native** - Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. Containers, servi
References are in the bottom, but we could add citations to ensure the link is made for the reader.

2021-03-19 15:52 UTC, jeffsaelens commented on doc/glossary.md
> +**Kube-Native** - TBD
I actually like the "native landscape". Cloud Native has morphed into an impossible to reach, but always aspired to ideal in mind. Even the original thought of "it runs natively in a cloud and takes advantage of the services offered" was a loaded concept as no two clouds like the same. Specifying what the target platform is, while also striving to meet the holy grail that is cloud nativeness seems like a practical approach (though how tedious it is to scale is yet to be seen).

2021-03-19 17:20 UTC, iawells commented on doc/glossary.md
> +**Cloud-Native Network Function** - A CNF is network functionality delivered in software via cloud native development and delivery practices. This functionality lives within the layers of the OSI Mod
I don't want to go down the well-trodden path that we define CNFs by how they're implemented. We define them by what they do and get people who implement them to suggest what works best for their implementation. Our best practices are a means to record and share that.

A network function is a thing that does network stuff. A cloud native network function is one that does it while it runs on a cloud and has been designed to benefit from running on a cloud.

Its use of microservices should very likely be recommended by us as a best practice for CNF dev teams to implement (until someone comes up with a better design) because it has a lot of benefit when you run on the cloud, and that makes it a Best Practice. But that's not what makes it either a network function or cloud native, and so it doesn't belong in the glossary.

2021-03-22 16:26 UTC, xmulligan approved these changes

2021-03-22 16:27 UTC, taylor approved these changes
lgtm as a start

2021-03-22 16:28 UTC, taylor requested changes

2021-03-22 16:28 UTC, taylor commented on doc/glossary.md
> +**Kubernetes** - Kubernetes is a portable, extensible, open-source platform for managing containerized workloads and services, that facilitates both declarative configuration and automation. It has a
```suggestion
**Kubernetes** - Kubernetes is a portable, extensible, open-source platform for managing containerized workloads and services, that facilitates both declarative configuration and automation. It has a large, rapidly growing ecosystem. Kubernetes services, support, and tools are widely available. ref: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/
```

2021-03-22 16:30 UTC, taylor approved these changes
lgtm as start

2021-03-22 16:31 UTC, merged