New Use Case about CNF behavior in respect to infrastructure lifecycle events
lfn-cnti/bestpractices pull request #95
Opened 2021-03-22 16:23 UTC by vukg

Hello everybody,

here is the new use case that deals with relation of CNF and underlying cloud infrastructure during infrastructure lifecycle events.

Would be great to add this one as it is typical situation that creates a lot of friction when it comes to onboarding of CNFs and their operation on 3rd party infrastructure. 

-Vuk

2021-03-23 08:35 UTC, CsatariGergely requested changes

2021-03-23 08:35 UTC, CsatariGergely commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +- Cloud Native Platform - Platform that exhibits properties of the cloud on which CNF runs. For this use case Cloud Native Platform = Kubernetes cluste
```suggestion
- Cloud Native Platform - Platform that exhibits properties of the cloud on which CNF runs. For this use case Cloud Native Platform = Kubernetes cluster
```

2021-03-23 08:35 UTC, CsatariGergely commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +- [x] Lifecycle management
Is this LCM the LCM of the infrastructure or the application or both?

2021-03-23 08:35 UTC, CsatariGergely commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +It is expected that CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes. CNF shall be capable to bear, without visible impact on its function or perform
Maybe "replaced with fresh nodes" should be extended to "replaced with fresh nodes with similar or better capabilities"

2021-03-23 08:35 UTC, CsatariGergely commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +It is expected that CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes. CNF shall be capable to bear, without visible impact on its function or perform
CNF functionality can depend on not capabilities, like instruction sets or HW accelerators. In some cases these capabilities are available only in a group of nodes.

2021-03-29 15:13 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +- [x] Lifecycle management
It is infrastructure lifecycle management. It is suggested in the title.

2021-03-29 15:14 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +It is expected that CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes. CNF shall be capable to bear, without visible impact on its function or perform
correct!

2021-03-29 15:29 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +It is expected that CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes. CNF shall be capable to bear, without visible impact on its function or perform
true. the main point here is that if CNF pods run on such node e.g. with HW accelerators CNF will not have problems if that node disappears and node with same capabilities appears or if CNF pods are shifted by Kubernetes scheduler to another node with same capabilities.

2021-03-29 16:12 UTC, jeffsaelens requested changes
Great first PR. Lots of things to unpack here.

2021-03-29 16:12 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
"This means that it shall have automated test coverage at the level of 100%." 

I think we need to unpack this more.

2021-03-29 16:12 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers. They are frequently pinning the nodes. CNFs expect that the cluster nodes are long living, even hi
I think we need to explore the concept of pinning. Pinning is a loaded term, and I'm pretty sure you are referring to a pod/CNF having its life-cycle tightly coupled to a specific node. Therefore we lose the ability to taint nodes and redeploy, recover from failures etc...

I think though that "pinning" resources in a node is not a bad thing if we can do it in a cloud native way. If the labels are there, and I can still meet the early considerations in this doc (here is a new SRIOV capable node, and FPGA, or any other feature etc...). If you can jump from the driver seat of one Ferrari to another, I think the intent is met.

2021-03-29 16:12 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
I almost think a lot of this could be a use case in itself.

2021-03-29 19:05 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers. They are frequently pinning the nodes. CNFs expect that the cluster nodes are long living, even hi
Correct, I meant here "node pinning" which is blocking the node from being tainted and drained. 

CPU pinning within the node is separate use case that I am not discussing here.

2021-03-29 19:12 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
Please check the latest version

2021-03-29 19:13 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers. They are frequently pinning the nodes. CNFs expect that the cluster nodes are long living, even hi
I have sharpened it in the latest update. Please check if the additional wording makes it better.

2021-03-29 19:15 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
hm, could be. If somebody makes dedicated use case we could offload this one here. However I would rather go merge this soon and change later when/if new case appears.

2021-03-29 23:01 UTC, jeffsaelens reviewed
Solid improvements.

2021-03-29 23:01 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Each CNF shall come with suite of tests, testing scenarios and monitoring rules that CNF DevOps team can deploy in their continous testing pipeline and monitoring system to enable that CNF is verifie
I really like these changes. I'd split it into two sentences though; its a beast as one.

2021-03-29 23:01 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
Yea, not sure on this part. CNF/Platform certification seems like it should be a use case as its quite an involved topic. I'll see if I can pull one together before this is merged. If not, to your point, we can leave it in here and move it later. This definitely goes beyond LCM in my opinion though as its more than just can I upgrade/manipulate the infra. Its really how do I determine that this CNF can run on my platform, as wel as does my platform provide what it should.

2021-03-29 23:01 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers. They are frequently pinning the nodes meaning that the CNF workloads are blocking that node from b
Pinning nodes reads weird to me. I'd say something around the lines of tightly coupling the life-cycle of the work load to the underlying infra.

2021-03-29 23:01 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
Paints a clearer picture. Will do a quick editing pass, but the point is more distinct.

2021-03-30 06:56 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
more I think of that it looks to me like two distinct topics:
1. How to reliably and quickly determine that after infrastructure change a CNF that already runs on my platform still runs properly, so that I can promote infrastructure change to reference and ultimately to the production.
2. How do we certify that CNF can run on my platform and if the platform provides everything so that CNF vendor can offer certain SLA.

The later one will partially be one of the ultimate outcomes of CNF WG in a sense that if both CNF and infrastructure conform to set of best practices they will be able to run together.

2021-03-30 18:54 UTC, electrocucaracha reviewed
This Use case touches several interesting points. IMHO it should also respond these  additional questions: 
* Why Blue-Green deployments can't be used here? 
* How [Priority and Preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) affects the CNF rolling upgrade process?

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Cloud Native Platform DevOps (CNPD) teams regularly perform lifecycle operations on Cloud Native Platforms. These operations include both updates (no breaking changes are expected) and upgrades (ther
Just a wording suggestion
```suggestion
Cloud Native Platform DevOps (CNPD) teams regularly perform lifecycle operations on Cloud Native Platforms. These operations include both updates (no breaking changes are expected) and upgrades (there is possibility of breaking changes). For agile teams, these changes happen frequently. An average of 2 times per month is not unheard of. For this use case, we will assume that a Kubernetes cluster is the Cloud Native Platform which is hosting the CNF. In reality there are number of additional components involved.
```

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +It is expected that a CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes with same or better capabilities. Assuming that remaining capacity of the clus
@iawells I think this is good example of limiting the number of chars, it seems like Github can't highlight suggestions properly on paragraphs with long lines.

```suggestion
It is expected that a CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes with same or better capabilities. Assuming that remaining capacity of the cluster is allowing rescheduling CNF pods to other, equivalent nodes, the CNF should be capable of bearing, without visible impact on its own function or performance, the situations in which its workloads are shifted to those nodes. If, within the course of infrastructure lifecycle operations, the capacity of the cluster gets reduced but remains above minimally allowed level, CNF shall still function with graceful degradation of its performance in the worst case. It is an expected functionality, that a proper CNF is not tightly coupled to any single node in a cluster, or group of nodes in larger clusters. CNF can still demand that nodes with certain capabilities are present (e.g. SR-IOV, XDP, GPU etc). However it shall not have issues nor impact for the customers if its workloads are dynamically shifted by kube-scheduler from one to another node of such type.
```

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +It is expected that a CNF copes well with situations when one or more nodes in the cluster are replaced with fresh nodes with same or better capabilities. Assuming that remaining capacity of the clus
I think this use case is a perfect example for highlighting the portability as best practice.

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +A CNF DevOps team shall be in position to quickly determine if CNF is behaving and functioning propperly after lifecycle operation (i.e. change) on infrastructure is done. If all is ok it is confirma
```suggestion
A CNF DevOps team shall be in position to quickly determine if CNF is behaving and functioning properly after lifecycle operation (i.e. change) on infrastructure is done. If all is ok it is confirmation that it is ok to promote that change to next environment and ultimately to the production. With the normal lifecycle pace of Cloud Native Infrastructure CNF DevOps team needs to count that this has to be done 4-6 times a month for all transitions between the environments. Ideally, it shall be happen automatically with combination of application testing and monitoring where the results can be available next day to CNF DevOps team. If that is not feasible it would still be acceptable if CNF DevOps team does that within 7 days per lifecycle operation.
```

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Also, most of CNFs today are following systems integrated approach. This means that integration of CNF version X with Platform version Y has been tested separately, possily as part of periodic "plug
```suggestion
Also, most of CNFs today are following systems integrated approach. This means that integration of CNF version X with Platform version Y has been tested separately, possibly as part of periodic "plug tests" or the certification procedures. It is typically CNF vendor to Platform vendor activity. Upstream is missed out in these certifications. Unfortunately, systems integrated approach and periodic integration testing with frozen versions, do not work in cloud native scenario where change is only constant. Versions of components are changing frequently and not upgrading means only accumulating the risks and technical debt. This is very expensive from operations perspective. If changes are done less frequently they are typically bigger and bring higher probability of failures.
```

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
Maybe it's important to distinguish the Platform requirements in this use case. Kubernetes API provides a well defined version management for its resources (alpha, beta, v1). But if the CNF has some non-Kubernetes requirements like Kernel version, CPU/memory features and/or PCI devices those can be addressed by the [NFD](https://kubernetes-sigs.github.io/node-feature-discovery/v0.8/get-started/introduction.html#feature-discovery). Maybe the best practice here is to encourage to use pinned versions.

2021-03-30 18:54 UTC, electrocucaracha commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Each CNF shall come with suite of tests, testing scenarios and monitoring rules that CNF DevOps team can deploy in their continous testing pipeline and monitoring system to enable that CNF is verifie
```suggestion
Each CNF shall come with suite of tests, testing scenarios and monitoring rules that CNF DevOps team can deploy in their continuous testing pipeline and monitoring system to enable that CNF is verified and certified (in best case daily) on that particular state of infrastructure.
```

2021-04-13 11:54 UTC, CsatariGergely commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +## Challenges and limitations with Kube-native approach
Do we also define(d) Kube native on top of cloud native?

2021-04-13 11:54 UTC, CsatariGergely commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
[Anuket RA2](https://cntt.readthedocs.io/en/latest/ref_arch/kubernetes/) addresses the infrastructure related part of 2.
Kuberetes API defines only Kubernetes and tells nothing about different other capabilities of the cluster, so there is a need for more stuff to be defined.

2021-04-13 20:05 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +## Challenges and limitations with Kube-native approach
@CsatariGergely yes. that can go into the global glossary as its applicable across the board.

2021-04-13 20:50 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
@jeffsaelens resolving to focus comments on latest version.  Re-open if you think these conversation thread is relevant to the current version.

2021-04-13 20:53 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers. They are frequently pinning the nodes. CNFs expect that the cluster nodes are long living, even hi
@jeffsaelens it looks like this conversation is for the older version.  Please check to see if the wording (eg. pinning) and other items are addressed in the new version.  Marking this conversation as resolved.

2021-04-13 21:37 UTC, taylor requested changes
@vukg I added a commitable suggestion for the tightly coupled hardware item from @jeffsaelens as a replacement for the node pinning phrasing.

2021-04-13 21:37 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers. They are frequently pinning the nodes meaning that the CNF workloads are blocking that node from b
```suggestion
Most of today's (so called) CNFs are retrofitted VNFs that have been forklifted into the containers.  The forklifted CNF is frequently tightly coupled to the underlying infrastructure, including going as far as assigning the CNF to a specific node. This means CNF workloads are blocking these nodes from being drained in reasonably short timeframe. These type of CNFs expect that the individual cluster nodes are long living, even highly available. In Kube-native approach cluster nodes are actually ephemeral and relatively short living. They exist typically for couple of days to couple of weeks. In such situation CNFs are implicitly requiring that infrastructure is mutable and that Cloud Native Platform DevOps team keeps uptime of the cluster nodes high. This is neither practical at scale of CSPs nor it is conformant to cloud native practices.
```

@jeffsaelens how's this for removing pinning?

@vukg thoughts?

2021-04-13 21:37 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
@jeffsaelens what do you think about leaving the section on versions and system integration here and creating a new use case with that as a focus?  (eg. its okay for different uses to have common or duplicated content when it makes sense)

@vukg #2 this can be a focused use case where we talk about the different aspects of CNF and platform.  

Ideally a CNF is declares its needs and the platform will communicate what it can provide. The CNF then works with whats available. Of course there will be cases where a CNF may need specific features only available with K8s add-ons / extensions. The CNF declarations for these needs should exist, possibly with versions supported (ideally a version or any newer). The platform itself can be built following the same type of practices where the layers, add-ons/extensions, etc are all declared and versioned.

The long term goal is a negotiation of the application with the underlying platform to determine what is supported and adjust accordingly.

2021-04-13 21:37 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +## Challenges and limitations with Kube-native approach
@fkautz would you like to help contributing the kubenative definition to the glossary?

2021-04-14 10:42 UTC, xmulligan commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
@jeffsaelens just wanted to bump to see if you are happy with how it is now

2021-04-25 21:57 UTC, jeffsaelens approved these changes
I think we merge this now with its current write up, and then decide later if we want/need to refine.

2021-04-25 21:57 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
I think we are good to push this in its current state and continue to evaluate as we dive deeper.

2021-04-25 21:57 UTC, jeffsaelens commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
if we are ok with the duplications, then I'm down. At later dates, we could potentially make new PRs that link complimentary or parallel use cases.

2021-04-25 23:01 UTC, xmulligan commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +## Challenges and limitations with Kube-native approach
I created #159 to track this

2021-04-25 23:06 UTC, xmulligan commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
do we want to create issues for the other use cases so people can be inspired by them then resolve this conversation and get this PR merged?

2021-04-25 23:06 UTC, xmulligan approved these changes

2021-05-04 17:09 UTC, taylor requested changes

2021-05-04 17:09 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Each CNF shall come with suite of tests, testing scenarios and monitoring rules that CNF DevOps team can deploy in their continuous testing pipeline and monitoring system to enable that CNF is verifi
@vukg suggested update for https://github.com/cncf/cnf-wg/pull/95#discussion_r603664833

```suggestion
Each CNF shall come with a suite of tests, testing scenarios and monitoring rules that CNF DevOps team can leverage. A team can deploy the test suite tooling via their continuous testing pipeline and integrate the results with their monitoring systems. The end goal being to ensure that a CNF is verified and certified (the best case being daily) on that particular state of infrastructure.
```

cc: @jeffsaelens @lixuna

2021-05-07 14:41 UTC, sishbi commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +Each CNF shall come with suite of tests, testing scenarios and monitoring rules that CNF DevOps team can deploy in their continuous testing pipeline and monitoring system to enable that CNF is verifi
LGTM

2021-05-07 14:42 UTC, sishbi approved these changes

2021-05-10 06:58 UTC, vukg commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +
@taylor today we are doing this alignment of platform (offer) and CNF (needs) in a dialog between platform and CNF teams+vendors as part of onboarding process. It includes itterations of platform configuration/extension and CNF addaptations and is mostly collaborative process that takes couple of days. However there could be also some more programatic / automated approach in future as "best practice".

2021-05-10 16:10 UTC, taylor commented on use-case/0001-UC-lifecycle-of-infrastructure-where-CNF-is-running.md
> +## Glossary
```suggestion
## Glossary

```

2021-05-10 16:19 UTC, taylor approved these changes

2021-05-10 16:20 UTC, rabi-abdel approved these changes

2021-05-10 16:21 UTC, rannyh approved these changes
LGTM

2021-05-10 16:22 UTC, electrocucaracha approved these changes

2021-05-10 16:22 UTC, rabi-abdel approved these changes
approaved

2021-05-10 16:25 UTC, merged