Add rules of arbitration for representation limits
lfn-cnti/bestpractices pull request #99
Opened 2021-03-23 02:33 UTC by iawells

The first change in this pull request also includes some cosmetics on the wording of the charter.

NB: I have not yet changed the 'one company, one vote' rule, since we're about to start an election cycle.

2021-03-24 16:45 UTC, rabi-abdel approved these changes

2021-03-29 13:04 UTC, xmulligan approved these changes

2021-03-29 16:16 UTC, CsatariGergely approved these changes

2021-03-30 15:46 UTC, iawells commented
Merged with the changes in the original since the original pull request.

2021-03-30 16:55 UTC, electrocucaracha commented on charter.md
> +2.  Entities may potentially not be independent if:
nit: extra space
```suggestion
2. Entities may potentially not be independent if:
```

2021-03-30 16:59 UTC, electrocucaracha approved these changes

2021-03-30 20:07 UTC, taylor requested changes

2021-03-30 20:07 UTC, taylor commented on charter.md
> +    - setting the agenda for meetings
```suggestion
- The Chairs are responsible for ensuring that group meetings are planned and facilitated effectively, while also engaging group members in leadership roles. Effective facilitation includes (but is not limited to) the following activities:
```

Remove "setting the agenda for meetings"

2021-03-30 20:07 UTC, taylor commented on charter.md
> +The decision on independence or dependence of entities may be revisited after a period of not less than three months.  After this time, any member may raise it for discussion via the above process.
Where did the three month time limit come from?

2021-03-30 20:22 UTC, taylor requested changes

2021-03-30 20:22 UTC, taylor commented on charter.md
> +    - setting the agenda for meetings
```suggestion
- *Primary role of Chairs is governance of the group.*
- The Chairs are responsible for ensuring that group meetings are facilitated effectively, while also engaging group members in leadership roles. Effective facilitation includes the following activities:
```

2021-03-30 20:23 UTC, taylor commented on charter.md
> +    - setting the agenda for meetings
Update from https://github.com/cncf/cnf-wg/pull/98

2021-03-30 20:25 UTC, iawells commented on charter.md
> +    - setting the agenda for meetings
why?

2021-03-30 20:25 UTC, iawells commented on charter.md
> +The decision on independence or dependence of entities may be revisited after a period of not less than three months.  After this time, any member may raise it for discussion via the above process.
Arbitrary choice.

2021-03-30 21:25 UTC, iawells commented on charter.md
> +    - setting the agenda for meetings
ok, done in the other proposed change

2021-03-30 23:20 UTC, taylor approved these changes

2021-03-30 23:34 UTC, merged